### ISSUE TITLE
Native implementation of Privacy Redirect

### ISSUE THREAD

**Issue by hbarsaiyan** [bromite/bromite#1003]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
I don't know. Sorry 😅.

### Describe the solution you would like
A native implementation of privacy redirect, which redirects sites like Youtube, Twitter, Instagram, Reddit to their privacy friendly frontends like [Invidious](https://github.com/iv-org/invidious), [Nitter](https://github.com/zedeus/nitter), [Bibliogram](https://sr.ht/~cadence/bibliogram/), [libreddit](https://github.com/spikecodes/libreddit). So i mean a native implementation of something like this:

![Screenshot_20210314-113521_Ungoogled_Chromium_Extensions](https://user-images.githubusercontent.com/37732050/111059424-65680a00-84bb-11eb-8847-387081e4a47f.png)

### Describe alternatives you have considered
Using browser with extension support but experience not very smooth 😅.

**Comment by csagan5** [comment]
No, this cannot be maintained as part of Bromite.

**Comment by scraunt** [comment]
Hi @csagan5, I was about to submit a request for this but noticed this one exists already - would you be able to elaborate on your reasoning for not being able to maintain this as part of Bromite? 

As a bit of a layman I would assume the handling of URLs is deep within Chromium source - and likely not touched by yourself in your forking of the Chromium source.  

Would it even be possible, technically, to have a setting that allowed a custom domain overwrite? 

This issue is requesting an implementation of this specific addon (which I notice is explicitly denied in the template), however the actual result appears to be rather simple. With Twitter/Nitter as an example, my _ideal_ implementation of this would be to first define a domain to be replaced (twitter.com) and then define a domain for it to be replaced with (nitter.net). 

So when browsing to hxxp://twitter.com Bromite would silently and with no user interaction modify the URL to hxxp://nitter.net whilst keeping the resource part after the TLD intact. 

I believe this would be a great addition to the already powerful privacy enhancing features Bromite provides, not only through allowing users to browse these popular sites with privacy respecting front ends but also spreading awareness that these frontends exist in the first place. 


Can I also just give you (and uazo) a huge thanks for the diligent and detailed hard work you have put into the project. I have been following the issue tracker, changelog & project generally for some time now and I honestly could not imagine going back to anything else as my main browser. 

I will be donating as a matter of course as soon as I can in the future - unfortunately at point in time I am unable to make a contribution. 

Keep up the great work! 

scraunt

**Comment by csagan5** [comment]
> would you be able to elaborate on your reasoning for not being able to maintain this as part of Bromite?

The browser is ultimately an "user agent", that means something that acts on behalf of the user (you); the primary job of the browser is to do what you tell it to do, and not lie about it. If you tell the browser to go to reddit.com and it redirects somewhere else it is already breaking this principle.

This is the reason why such feature is not in line with the project goals.

There is no upstream extensions support in Chromium and thus none in Bromite as well; in future when #792 is solved you will probably have that as a venue to implement something like this.
