### ISSUE TITLE
Sites detecting Adblock

### ISSUE THREAD

**Issue by techsupportguy2018** [bromite/bromite#101]
Some sites detects adblock and don't work correctly for that reason.
Would it be possible implement Nano Defender (or filters) that sites won't see adblock.
Also would it be possible add option that will stop 3rd party scripts and frames (like in uBlock Origin)? It will improve privacy.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
