### ISSUE TITLE
Disable/Remove FLoC in Bromite

### ISSUE THREAD

**Issue by Github-com-foss** [bromite/bromite#1104]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
https://github.com/brave/brave-browser/issues/14942

### Describe the solution you would like
Remove Floc in Bromite

### Describe alternatives you have considered
Disable/remove

**Comment by Peacock365** [comment]
@csagan5 

Why was this closed? Disabling FLoC seems trivial, just apply the Vanadium patch to Bromite:

https://github.com/GrapheneOS/Vanadium/blob/11/patches/0078-disable-unused-FLOC-feature.patch

**Comment by uazo** [comment]
```
    {
      name: "InterestCohortAPI",
      origin_trial_feature_name: "InterestCohortAPI",
      origin_trial_allows_third_party: true,
    },
```
at https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/runtime_enabled_features.json5 
`origin_trial_feature_name` should also be modified so that blinks do not activate document.interestCohort

```
    // origin_trial_feature_name: "FEATURE_NAME" is used to integrate the
    // feature with the Origin Trials framework. The framework allows the
    // feature to be enabled at runtime on a per-page basis through a signed
    // token for the corresponding feature name. Declaring the
    // origin_trial_feature_name will modify the generation of the static
    // methods in runtime_enabled_features.h/cpp. The static method then allows
    // the feature implementation to check if the trial is enabled for the
    // current context.
    origin_trial_feature_name: {
    },

```

**Comment by Peacock365** [comment]
For completeness's sake, the related Brave patches:

https://github.com/brave/brave-core/pull/8468

https://github.com/brave/brave-core/commit/7e8ef34363ed801ffba11094fca6865cffad5165

**Comment by uazo** [comment]
currently FloC api may be active because under this if

```
bool PrivacySandboxSettings::IsPrivacySandboxAllowedForContext(
    const GURL& url,
    const base::Optional<url::Origin>& top_frame_origin,
    const ContentSettingsForOneType& cookie_settings) const {
  if (!base::FeatureList::IsEnabled(features::kPrivacySandboxSettings)) {
    // Simply respect cookie settings if the UI is not available. An empty site
    // for cookies is provided so the context is always as a third party.
    return cookie_settings_->IsCookieAccessAllowed(url, GURL(),
                                                   top_frame_origin);
  }
```

if the privacy sandbox is disabled (as in bromite), the third-party cookies flag is used

**Comment by uazo** [comment]
it would also be worth considering the hypothesis of not deactivating it, but of making sure that that value (FlocID) is regenerated every time

https://source.chromium.org/chromium/chromium/src/+/master:components/federated_learning/floc_id.cc;l=106;drc=221e331b49dfefadbc6fa40b0c68e6f97606d0b3;bpv=1;bpt=1

**Comment by Peacock365** [comment]
@uazo 

Why not just disable it (like Vivaldi & Brave did)? Genuinely curious.

**Comment by uazo** [comment]
to make bromite look like chrome works

**Comment by Peacock365** [comment]
Bromite can already be told apart from Chrome, this is pointless. I am all for disabling FLoC.

**Comment by csagan5** [comment]
> Why was this closed?

Because the author (and you) have not searched for 'FLoC' before posting.

The privacy sandbox feature is disabled by default; that includes FLoC.

> if the privacy sandbox is disabled (as in bromite), the third-party cookies flag is used

@uazo it is not, see https://github.com/chromium/chromium/blob/90.0.4430.92/chrome/browser/federated_learning/floc_id_provider_impl.cc#L138

**Comment by Peacock365** [comment]
OK, fine. Have my upvote. No need for rudeness though, @uazo and I are here to help. One suggestion: I think you should highlight the fact that the privacy sandbox (including FLoC) is disabled under the "Features" section of this GitHub page, this will prevent further irritations or users raising issues that are already resolved. Just an idea...

**Comment by uazo** [comment]
> @uazo it is not

follow `IsPrivacySandboxAllowed()` at https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/federated_learning/floc_id_provider_impl.cc;l=137;drc=4533298cd5be17abcbc030ef130a09eeb55fbed9;bpv=1;bpt=1

you will arrive
```
bool PrivacySandboxSettings::IsPrivacySandboxAllowed() {
  if (!PrivacySandboxSettingsFunctional()) {
    // Simply respect 3rd-party cookies blocking settings if the UI is not
    // available.
    return !cookie_settings_->ShouldBlockThirdPartyCookies();
  }

  return pref_service_->GetBoolean(prefs::kPrivacySandboxApisEnabled);
}
```

and `IsFlocAllowed()` to the method I mentioned earlier

**Comment by Peacock365** [comment]
@uazo 

So it is in fact still enabled? If so, we are back at square one.

**Comment by csagan5** [comment]
> OK, fine. Have my upvote. No need for rudeness though, @uazo and I are here to help. One suggestion: I think you should highlight the fact that the privacy sandbox (including FLoC) is disabled under the "Features" section of this GitHub page, this will prevent further irritations or users raising issues that are already resolved. Just an idea...

I am not being rude, you are being rude by not following how to interact with this project.

I am not here to prevent irritations or users raising issues: if an user wants to raise an issue or help they must follow the issue template, that's it.

> follow `IsPrivacySandboxAllowed()` at

If Bromite always blocks third-party cookies then I must conclude that FLoC is disabled because of the relative field trial.

**Comment by Peacock365** [comment]
@csagan5 

There already is an issue template, @Github-com-foss has created one, just saying... The rest of the issue is for discussion purposes because the issue template already exists.

Furthermore, I am going to point out the obvious: Relying entirely on third party cookies being off by default is a bad idea. There are use cases where the user might differ from the default by enabling third party cookies, e.g. to unbreak cross-site login forms. Why not introduce an explicit FLoC blocking patch like the Vanadium browser did? I think all that would be required is applying this patch 1:1...

**Comment by Peacock365** [comment]
I see that FLoC being disabled in Bromite was listed in the most recent release notes. Thumbs up for that, however, I am currently not seeing any new patch relating to FLoC? Am I missing something here (curious)? Anyway, I have question:

If a user allowed third party cookies in Bromite, e.g. to unbreak cross-site login forms, before FLoC rolled out, is there a possibility that they were enrolled in the trial since you were apparently relying solely on the cookie setting to disable FLoC (correct me if I'm wrong)?

**Comment by uazo** [comment]
in any case seems that a patch is needed: the changes of brave are more than the simple flag, and must be studied

**Comment by csagan5** [comment]
> Furthermore, I am going to point out the obvious: Relying entirely on third party cookies being off by default is a bad idea. There are use cases where the user might differ from the default by enabling third party cookies, e.g. to unbreak cross-site login forms.

Instead of posting all these comments, why do you not prove that FLoC was/is enabled in Bromite? That is the only thing you have not done so far (and nobody else).

> in any case seems that a patch is needed: the changes of brave are more than the simple flag, and must be studied

Both privacy sandbox and FLoC are disabled, nothing else is needed. Brave's patches seem to be focused on allowing FLoC in some scenarios, which is not something we need in Bromite. It will be disabled as in all other browsers that have not opted for having FLoC; if Chromium goes forward with making the privacy sandbox and FLoC enabled by default and without a feature flag, we will need a bigger patch.

**Comment by Peacock365** [comment]
@csagan5

Oh look, Ungoogled Chromium has a proper patch for FLoC now:

https://github.com/Eloston/ungoogled-chromium/commit/ba646b42b095ac3247123afa57dd8e039120955c

Relying entirely on arbitrarily set preconditions for FLoC being enabled (third party cookies being enabled) is a bad idea, those preconditions might be altered by Google randomly and without prior notice in the future. But yeah, no need for a proper patch. /s

I am out, just wanted to hint at the fact that other projects saw the need for a patch and did it correctly.
