### ISSUE TITLE
Option to import auto-fill passwords from file?

### ISSUE THREAD

**Issue by pojebunny** [bromite/bromite#112]
There is a setting to export them, but not import. Can this feature be added or is it considered not safe enough?

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)

As for this specific issue: the functionality has already been imported.
