### ISSUE TITLE
Code to create adblock_entries.h

### ISSUE THREAD

**Issue by pceiley** [bromite/bromite#113]
Would you be willing to share your code to generate the adblock_entries.h file such that I can adapt for my project?

Thanks for your ongoing work on this browser!

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)

As for the specific question: I am working on a release of such code for #2 but it is not ready yet.
