### ISSUE TITLE
Adding "Enable Antitracking" ticker

### ISSUE THREAD

**Issue by Sterilize** [bromite/bromite#118]
In other words, the "Enable AdBlock" ticker consists of Antitracking as well.

Would it be rude of me to ask to seperate them.?

*I'm using Adaway with stevenblack's hosts & I'd rather use this over the default adblocking.

Thus by disabling only the built-in adblock in bromite, the browser would require less resources to load a webpage each time.

********
BTW whether csagan5 would implement my feature request or not, I'm just willing to thank him for his hard work upon this great browser!

I always install Bromite browser on smartphones of my family members and recommend it to my friends, colleagues and even clients.

Thank You Very Much!!!

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
