### ISSUE TITLE
add feature : disable history in non-incognito mode

### ISSUE THREAD

**Issue by Ananas-Kuchen** [bromite/bromite#1181]
### Is your feature request related to privacy?

 yes

### Is there a patch available for this feature somewhere?

 no

### Describe the solution you would like

 please add an option to disable history in the regular tab. so I don't have to erase history multiple times in non-incognito mode

### Describe alternatives you have considered

 no idea

**Comment by uazo** [comment]
I'd like to add that option, along with the ability to change it in always incognito, by adding a flag like this for history:
![image](https://user-images.githubusercontent.com/29201891/120368961-f7d9b600-c312-11eb-8acb-539eb3fed56d.png)

**Comment by csagan5** [comment]
> I'd like to add that option, along with the ability to change it in always incognito, by adding a flag like this for history:

We have already discussed this in the past; the use-case vs always-incognito is no history but cookies, cache and local storage.

My conclusion last time is that we cannot support all these combinations, they are an endless source of bugs.

**Comment by uazo** [comment]
> My conclusion last time is that we cannot support all these combinations,
> the use-case vs always-incognito is no history but cookies, cache and local storage.

I do not understand, what do they have to do with it cookies, cache and local storage?

the change is pretty simple, to be done is only here https://github.com/bromite/bromite/blob/master/build/patches/Add-history-support-in-incognito-mode.patch#L105 , `kIncognitoTabHistoryEnabled` could have three states: 
- on (default) 
- on only in always incognito (like now)
- always off

> by adding a flag like this for history

maybe this is a bit more complex (if it's not complex I don't like it :)
I can try to check if it is possible to add a flag linked to the tab, rather than to the profile. perhaps this possibility already exists, although I have never seen it.

> they are an endless source of bugs.

you may be right, that's why (in my opinion) priority goes to activating test cases (and obviously bugs fixing)

**Comment by Ananas-Kuchen** [comment]
@csagan5 The reason why I'm making this request is related to some of the things that Incognito mode lacks.

Maybe for you a simple solution but there are some problems that I need to describe

- In incognito mode, I have to log in many times if I want to enter a website

- Saving web pages cannot be done in incognito mode. It's troublesome if there's a moment where I need to do it.

- If you can "disable history" or "delete all data automatically after exiting the application" then this makes it easier to use on non-incognito users (but you rejected a lot of people's submissions regarding it)

Not all solutions finish by suggesting incognito mode due to some restricted features.

Of course it's not safe if the login session is still stored in incognito mode

Incognito mode is effective if it is used to login on certain websites that are rarely visited. not frequently visited and users don't want to log in multiple times to a website. although there is a save password feature but I don't feel like using it.

I hope you can consider this. but of course i can understand if of course there is a limit on what you can do because the problem is complicated.

But if possible I hope this request is considered to be realized. at least another solution which is more effective from developer point of view but all users can find it useful. related to "automatically delete history" when exiting the browser.

Thank you

**Comment by csagan5** [comment]
> Not all solutions finish by suggesting incognito mode due to some restricted features.

Equally, not all features submitted increase privacy.

> Incognito mode is effective if it is used to login on certain websites that are rarely visited. not frequently visited and users don't want to log in multiple times to a website. although there is a save password feature but I don't feel like using it.

My statement is clear: if you want a bit better browsing privacy, use incognito mode. Disabling history while leaving everything else enabled will not give you a bit better browsing privacy.

> * If you can "disable history" or "delete all data automatically after exiting the application" then this makes it easier to use on non-incognito users (but you rejected a lot of people's submissions regarding it)

It does not matter how many times a feature is requested: any feature request that does not increase privacy will be rejected. This feature makes privacy worse because users will not use incognito thanks to it.

**Comment by uazo** [comment]
> If the user disables history he will be ignoring the fact that third-parties can still track you via cookies, cache and local storage
> This feature makes privacy worse because users will not use incognito thanks to it.
> Disabling history while leaving everything else enabled will not give you a bit better browsing privacy.

Ok, now I remember and always agree with you.

> This has already been discussed in past issues; as last time, I asked: why cannot always-incognito be used instead of disabling history? What are the features that work in one and not in another?

we have to open a task for that, otherwise I'll never remember to investigate

> priority goes to activating test cases

we continue to add features but how guarantee that they have no bugs? it was simply for that

> I setup the project with issue priorities

I know them, I'm working on it

> If you can "disable history" or "delete all data automatically after exiting the application" then this makes it easier to use on non-incognito users (but you rejected a lot of people's submissions regarding it)

@Ananas-Kuchen it is more complex than you think, the ways to track navigation are many but it seems that the chromium team has minimized them only in anonymous mode. but @csagan5 is right, we should make it explicit

**Comment by Ananas-Kuchen** [comment]
thank you all for your statements that let me know what is true

**Comment by csagan5** [comment]
> > If the user disables history he will be ignoring the fact that third-parties can still track you via cookies, cache and local storage
> > This feature makes privacy worse because users will not use incognito thanks to it.
> > Disabling history while leaving everything else enabled will not give you a bit better browsing privacy.
> 
> Ok, now I remember and always agree with you.

Disagreement is good, but we need arguments and evaluate pros/cons. There are a couple questions to pin on this topic:
* what happens if the user has history disabled but everything else in normal mode?
* what are the downsides of using incognito that make the users need normal mode with history disabled?

At the very least history makes the user more aware of which sites have something on you, there is no similar easy access for cache, cookies, local storage.

Last time we discussed this I was proposing to make incognito mode stronger, following the upstream design from Chromium.

> thank you all for your statements that let me know what is true

They are all opinions but any change is made for everyone using the browser and must be evaluated fairly.

**Comment by uazo** [comment]
> what happens if the user has history disabled but everything else in normal mode?

technically nothing change, history is a separate service in chromium: the confirmation is the patch that reactivates it in always incognito.
from the point of view of the sites even there nothing, theoretically no site has access to the history, unless (big) security bugs.

> what are the downsides of using incognito that make the users need normal mode with history disabled?
> Last time we discussed this I was proposing to make incognito mode stronger, following the upstream design from Chromium.

from the code, the disabled functions seem to be several, long ago I had marked all the times that the code referred to `IsOffTheRecord()` and similar, I found it in many points, but I never identified them one by one, it is something that we should do sooner or later.

for the ui, it seems to me that are missing
- homepage
- add to home screen
- recents tabs
- persist tabs over sessions (that I miss a lot)

maybe there is more, never user normal mode
