### ISSUE TITLE
Add Custom DoH Servers

### ISSUE THREAD

**Issue by laamalif** [bromite/bromite#124]
Option to add custom DoH server instead of Cloudflare and Google servers. Anyone can run there own DoH servers locally or in VPS to improve privacy.

Servers:
https://github.com/jedisct1/rust-doh
https://facebookexperimental.github.io/doh-proxy/

Client:
https://github.com/curl/doh

Public Server:
https://mozilla.cloudflare-dns.com/dns-query

Mozilla and Cloudflare Privacy Policy:
https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/firefox/

Server Setup:
Easiest implementation will be rust-doh server which forward all requests to quad9 servers by default. 
```
doh-proxy -u 1.1.1.1 # or your own dns server
```
nginx config block:

```
    location /dns-query {
	if (!-f $request_filename) {
		proxy_pass http://127.0.0.1:3000;
		break;
	}
```

You can mix match your server with dnscrypt and unbound with ads blocking for more paranoid setup.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
