### ISSUE TITLE
Allow homescreen shortcuts in Incognito mode

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [bromite/bromite#1257]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

Not that I know of.

### Describe the solution you would like

Currently we can only add home screen shortcuts and use similar features when not in an Incognito window. But there are - I believe - quite a lot of people who use Bromite with "Always in Incognito" enabled, so it can be annoying to switch out and back from this mode. Same thing with screenshots but I will create another issue for that: [#1258] I think we should have more options in Incognito.

### Describe alternatives you have considered

--

**Comment by csagan5** [comment]
The NTP tiles cannot be implemented without having them fetch the favicon every time you open the NTP page; that is not a desired feature when using always-incognito mode.

Since this feature request is about UI rather than privacy I will close it; if there is someone that wants to implement this and maintain it for an indefinite time, please submit a patch.

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 What about caching the favicon?
