### ISSUE TITLE
Very basic tab view

### ISSUE THREAD

**Issue by Muscarv2** [bromite/bromite#128]
The most recent update (69.3497.91) has chrome://flags/#enable-accessibility-tab-switcher as the tab view, even if that flag is disabled. I've tried re-installing but it's still that way.

**Comment by Madis0** [comment]
This happens on any Chromium 68+ if you have an accessibility feature enabled on its settings. Chromium 71 will have an option to disable that.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)

**Comment by Madis0** [comment]
This is fixed in upstream 70 (and therefore Bromite) though.
Settings > Accessibility > Simplified view for open tabs
