### ISSUE TITLE
[Feature Request] Delete History, Cookies, etc. at timely intervals.

### ISSUE THREAD

**Issue by TearJoy** [bromite/bromite#1319]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
No, not that I know of as of writing.

### Describe the solution you would like
As the title says, the feature allows you to clear history, cookies, and other data at timely intervals e.g. XX:00 or XX:30. Add options to exclude some things like site settings too because it can be a real pain to have to allow a JS exception again. This also helps against using always-incognito mode as always-incognito mode doesn't save history, doesn't open links in apps and possibly other things. (Using incognito can be FPable (?)). Optionally also add an option to whitelist sites from cookie sanitizing for people who like to login.

### Describe alternatives you have considered
Clear History and other site data on exit, something that exists in Firefox and Brave. This feature isn't really practical on mobile devices since pressing home or switching apps doesn't actually close the browser. Ofcourse you can just kill the app or clear it from recent apps, but what about the times when you forgot to do it?

**Comment by wchen342** [comment]
> This feature isn't really practical on mobile devices since pressing home or switching apps doesn't actually close the browser

This is not entirely true. It is true that apps can remain in background and not being killed, but:

 - When the app is no longer visible to the user, `onDestroy()` will be called on activity, which is often used to do tasks similiar to exiting on Desktop applications, and
 - There is nothing stopping the app (in this case, browser) just to call a function deleting everything it stores when the user clicked a button in menu, and then hide itself. It will be true that the browser is not truly "killed", but nonetheless the data will be cleared because of the function we called.
 - The "quit on exit" are implemented different on Desktop and on Android, so on Android they don't depend on the "app being completely dead" logic that used on desktop.

Having said that,

> what about the times when you forgot to do it?

I think this is a valid point, although there can be a situation when the user need something to stay and "forget to turn off the timer" this time. There is always a trade-off.

**Comment by TearJoy** [comment]
Thanks for your insight. These are just concerns when I used FF in the past where it didn't actually "close" the browser, I had to press quit or swipe it from the recents apps menu. What you said interests me tho, have a button to clear history, site data, etc or just a button to quit the browser, like what FF has. It would be a great feature to have in Bromite. Looking forward to the dev's responses!

**Comment by csagan5** [comment]
This is a variation of a feature request that keeps coming up regularly; feel free to search the issue tracker for those.

The response is unchanged: only always-incognito and regular mode are supported, see the replies in those other issues for the rationale.
