### ISSUE TITLE
Links open via custom tabs are added to History even if Bromite is set to open new links in incognito mode

### ISSUE THREAD

**Issue by celsoazevedo** [bromite/bromite#132]
**Bromite version**

Version: `69.0.3497.91`
Arch: `arm64`
Android version: `Android 8.1 (LineageOS 15.1)`

**Describe the bug**
Links opened from an app that supports custom tabs are added to our history even if the new "open links in incognito tabs always" option is enabled.

**To Reproduce**

1. Clean up all your browsing history
2. Go to Settings > Privacy
3. Enable "Open links in incognito tabs always" and "Allow custom tab intents"
4. Open a link from any app that support custom apps and then close it
5. Check your browsing history

**Expected behavior**
URLs shouldn't be added to our "history".

**Screenshots**
[ScreenRecord-2018-09-17-21-32-35-1.mp4](https://www.celsoazevedo.com/files/2018/ScreenRecord-2018-09-17-21-32-35-1.mp4)

**Comment by csagan5** [comment]
@rarcher looks like the patch needs an extension for custom tab intents

**Comment by csagan5** [comment]
> @csagan5 The issue is that enabling always-incognito mode doesn't convert existing regular tabs into incognito ones. The Brave people specifically wanted that behavior, and did not wish to merge the patch without it.

@rarcher thanks for telling about the history of the patch. What are your thoughts regarding this? I am considering this a bug, but is there some reason/rationale why custom tab intents should override an "always incognito" mode?

**Comment by rarcher** [comment]
@csagan5 No, that's most definitely a bug.

**Comment by csagan5** [comment]
I did some tests on this. My findings:
* custom tab intents which have the incognito flag (so, an app that explicitly says I would like this to be in incognito) would be ignored with a logged message `Not handling with Instant Apps (other)`
* even if I set this flag explicitly on the intent, it gets ignored later on - probably because custom tab intents never were supposed to go incognito.

This is also a reason why I added that flag to disable custom tab intents: there is no reason why they should be "special" browsing, although some people like the feeling of not leaving the app.

My take on this is that it is not trivial to implement.

```diff
Author: csagan5 <32685696+csagan5@users.noreply.github.com>
Date:   Tue Sep 18 23:01:01 2018 +0200

    Fixup honour always incognito mode for custom tab intents as well

diff --git a/chrome/android/java/src/org/chromium/chrome/browser/instantapps/InstantAppsHandler.java b/chrome/android/java/src/org/chromium/chrome/browser/instantapps/InstantAppsHandler.java
--- a/chrome/android/java/src/org/chromium/chrome/browser/instantapps/InstantAppsHandler.java
+++ b/chrome/android/java/src/org/chromium/chrome/browser/instantapps/InstantAppsHandler.java
@@ -95,6 +95,8 @@ public class InstantAppsHandler {
     // Only two possible call sources for fallback intents, set boundary at n+1.
     private static final int SOURCE_BOUNDARY = 3;
 
+    private static final String PREF_ALWAYS_INCOGNITO = "always_incognito";
+
     private static final EnumeratedHistogramSample sFallbackCallSource =
             new EnumeratedHistogramSample("Android.InstantApps.CallSource", SOURCE_BOUNDARY);
 
@@ -221,9 +223,7 @@ public class InstantAppsHandler {
             return false;
         }
 
-        if (IntentUtils.safeGetBooleanExtra(
-                intent, IntentHandler.EXTRA_OPEN_NEW_INCOGNITO_TAB, false)
-                || IntentUtils.safeHasExtra(intent, ShortcutHelper.EXTRA_SOURCE)
+        if (IntentUtils.safeHasExtra(intent, ShortcutHelper.EXTRA_SOURCE)
                 || isIntentFromChrome(context, intent)
                 || (IntentHandler.getUrlFromIntent(intent) == null)) {
             Log.i(TAG, "Not handling with Instant Apps (other)");
@@ -248,6 +248,10 @@ public class InstantAppsHandler {
         callbackIntent.putExtra(DO_NOT_LAUNCH_EXTRA, true);
         callbackIntent.putExtra(INSTANT_APP_START_TIME_EXTRA, startTime);
 
+        if (ContextUtils.getAppSharedPreferences().getBoolean(PREF_ALWAYS_INCOGNITO, false)) {
+            callbackIntent.putExtra(IntentHandler.EXTRA_OPEN_NEW_INCOGNITO_TAB, true);
+        }
+
         return tryLaunchingInstantApp(context, intent, isCustomTabsIntent, callbackIntent);
     }
 
```

**Comment by bocekm** [comment]
Isn't [the **shouldIgnoreIntent** function](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/chrome/android/java/src/org/chromium/chrome/browser/IntentHandler.java#881) causing the problem?

```java
public boolean shouldIgnoreIntent(Intent intent) {
  ...
  // "Open new incognito tab" is currently limited to Chrome.
  if (!isFromChrome
    ...
    return true;
```

**Comment by csagan5** [comment]
@bocekm I tried that also with that, no results.

**Comment by uazo** [comment]
>@uazo support for incognito CCTs is not in v81?

You are right. It's in v84, with this commit:
https://chromium.googlesource.com/chromium/src/+/0564543823de028bad66868ffb7ef907fdbfb000

I don't know bromite policies, in these cases do we wait upstream?

**Comment by csagan5** [comment]
@uazo it is in all versions since v80: https://github.com/chromium/chromium/commit/0564543823de028bad66868ffb7ef907fdbfb000

**Comment by uazo** [comment]
thanks, now I'm starting to understand versioning.
therefore it is possible to constrain anonymous mode in the custom tabs, although they say

https://bugs.chromium.org/p/chromium/issues/detail?id=1023759
Incognito CCT intent handling is added. This is currently done using
the only available off the record profile in Chrome. Therefore the
profile is shared between browser and CCTs, and will leak data from
one to other.
Incognito CCT is now behind disabled kIncognitoCCT flag and will be
enabled when implementation is completed create an isolated profile
for each CCT.

I don't think that the calling application has the possibility to access some profile data (after all it simply launches an intent that is managed by another process), however it could track the user using some cookies, and I think that's why it is not yet been activated.

you could think of deleting the profile when closing the custom tab, or deleting the history of the single tab, but I don't know if it is allowed, nor if it is possible (my knowledge of the chromium source is still limited).

**Comment by csagan5** [comment]
Is this issue still present in `81.0.4044.127` (current release)?
