### ISSUE TITLE
Youtube broken

### ISSUE THREAD

**Issue by tcz305** [bromite/bromite#136]
With me youtube is broken since version .91
I get sound ok but the video is just green static.
Huawei mate 10 pro, Android 8.0 stock.
The latest chrome canary works fine.

**Comment by hhjeremy** [comment]
Same issue for me.
Huawei p20 Pro. 
Don't have this issue in any other problem.

**Comment by Primokorn** [comment]
No issue here with YouTube Vanced.
arm64_ChromeModernPublic & Bromite's webview

**Comment by csagan5** [comment]
Guys, the issue is invalid. It was not tested with Chromium **with that specific device**, to mention one problem. We do not compare Bromite issues to Chrome but to Chromium.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
