### ISSUE TITLE
option to have "Desktop Site" stay enable between reboots

### ISSUE THREAD

**Issue by tcz305** [bromite/bromite#144]
Possible to have the "Desktop Site" box  in the menu dropdown remain checked between app restarts?
As it is I have to enable it every time I open the app.
Thanks

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
