### ISSUE TITLE
Top bar become blanc?

### ISSUE THREAD

**Issue by DecodeMehh** [bromite/bromite#145]
It happen to me 3-4 times it is realy rare but still annoying
https://i.imgur.com/f9JYLrr_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
