### ISSUE TITLE
support for external download manager like ADM

### ISSUE THREAD

**Issue by np1729** [bromite/bromite#147]
Ability to select other app to download file ..like firefox

**Comment by aFoxWhoIsNice** [comment]
Why was this closed? Would've been super handy :/

**Comment by ExtremeNerd** [comment]
Copy link when ADM is running -- that's it.

**Comment by Madis0** [comment]
> Why was this closed? Would've been super handy :/

Probably because it does not follow the issue format and is not related to privacy.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

(Issues not following the template are considered invalid)

I also believe that this issue is not about privacy.
