### ISSUE TITLE
Open Links In External Apps.

### ISSUE THREAD

**Issue by blogmangit** [bromite/bromite#1472]
### Is your feature request related to privacy?

Maybe Not Sure
### Is there a patch available for this feature somewhere?

No Patch
### Describe the solution you would like

Is it possible to open links in external apps like YouTube links in YouTube app or reddit links on reddit app?

Also "Get in at PlayStore" links not opening playstore is it normal?

### Describe alternatives you have considered

Nothing considered

**Comment by uazo** [comment]
@csagan5 do you know what exactly that patch does then?
do you know a way to verify that it is working? otherwise I'll check the code

**Comment by csagan5** [comment]
That patch comes from Brave and it is quite old; they have changed the implementation quite a lot since then, and anyways I am still not very proficient and finding patches in the Brave repository.

See:
* https://community.brave.com/t/how-do-i-get-youtube-links-to-open-in-the-youtube-app/156896/8
* https://community.brave.com/t/youtube-link-opens-in-brave-instead-of-native-youtube-app/203425/11
* https://github.com/brave/brave-core/pull/3487
* https://github.com/brave/brave-core/pull/3507

**Comment by uazo** [comment]
OK thank you very much. I mark it among the things (many!) to look at..
I added it to projects repo

**Comment by csagan5** [comment]
@uazo I think this has been addressed by now?

**Comment by uazo** [comment]
good, you are right to ping me ... I even forgot about it!

> I think this has been addressed by now?

I don't know... in my opinion the situation is still that.

**Comment by baldrianbandit** [comment]
I see another use case for that. The DB Navigator app launches a window of the default browser to acconts.bahn.de/auth for authentication. After credentials are given by the user, website forwards to a dbnavigator://<key> url, which returns an err_unknown_url_scheme in Bromite.

Following the same procedure with DuckDuckGo browser set as default, it then asks me if the dbnavigator:// url should be opened via an external app. If I click yes, the DB Navigator app opens and tells me that authentication was successful.
