### ISSUE TITLE
Google searches saving in search box

### ISSUE THREAD

**Issue by Blinkenn** [bromite/bromite#148]
Why are Google searches now saved in the search bar on Google.com? 
Is this a browser setting that has changed and if not is there something I can change in the browser to stop this? 
I didn't have this happen on v68.

**Comment by Blinkenn** [comment]
Why is this invalid?

**Comment by csagan5** [comment]
@Blinkenn the issue submission template cannot be ignored. That text you erased, that's the submission template.

**Comment by Madis0** [comment]
@Blinkenn You might be thinking of #143

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
