### ISSUE TITLE
Bottom url bar like Kiwi

### ISSUE THREAD

**Issue by fredgolightly** [bromite/bromite#150]
As titled, Chrome Home allows buttons at the bottom, but the url bar at bottom would be a great option for those of us on larger phones.
Long-press on tab switcher icon to open a new tab would be greaet too!

**Comment by dimqua** [comment]
There are patches for this feature: https://github.com/kiwibrowser/privacy_patches

**Comment by fredgolightly** [comment]
Thanks! I guess these are only available if you're compiling the apk yourself?

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

All issues not following the template are considered invalid; this issue would not be valid even with template because it is about UI and it is clearly stated in the README that it is out of topic for Bromite.

Regardless, those patches still require a lot of work to be used.
