### ISSUE TITLE
Adding search engines.

### ISSUE THREAD

**Issue by ExtremeNerd** [bromite/bromite#152]
Correct me if I am wrong. I didn't find how to add a search engine of a website, for example github or searx, like we can do with firefox.

**Comment by csagan5** [comment]
Duplicate of #91

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

All issues not following the template are considered invalid.
