### ISSUE TITLE
Incognito mode keyboard

### ISSUE THREAD

**Issue by Ennneerrrgggyyy** [bromite/bromite#155]
After the latest update the use of Bromite incognito mode doesn't prompt the incognito mode of Gboard anymore

**Comment by fr31b3u73r** [comment]
Reproducible for me, would love to have incognito keyboard on incognito tabs

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear when submitting issues via mobile; I was always assuming that the issue template was being ignored, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

All issues not following the template are considered invalid.

**Comment by Ennneerrrgggyyy** [comment]
This is indeed, what must have happened 🙂 

Thank you. The problem doesn't occur anymore
