### ISSUE TITLE
Cosmetic filtering/Remove add elements.

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#157]
Can cosmetic filtering be added. Since in the place of ads, there is a big grey box that takes screen space. 

P.S - Title mistake, Ads instead of add. 😛

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear when submitting issues via mobile; I was always assuming that the issue template was being ignored, sorry for that.

I am working on a solution for the issue template problem; feel free to re-submit your issue after enabling desktop mode so that you will see and use the issue template.

All issues not following the issue template are considered invalid.

**Comment by killoid** [comment]
is this thing still being considered? on apkmirror, placeholders left by the blocked ads takes up so much screen space. looks very bad imo.
