### ISSUE TITLE
Privacy friendlier Cloudflare DoH resolver

### ISSUE THREAD

**Issue by randomshell** [bromite/bromite#164]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
Yes, it's an edit request

**Describe the solution you'd like**
Mozilla partenered with Cloudflare for their DoH resolver and they have a resolver (https://mozilla.cloudflare-dns.com/dns-query) which limits logged data and data retention, opposed to the 1.1.1.1
Can it be used instead the current 1.1.1.1 if DoH flag value is set to Cloudflare?

[Source article](https://www.ghacks.net/2018/04/02/configure-dns-over-https-in-firefox/)

**Describe alternatives you've considered**
any

**Comment by csagan5** [comment]
This is the special agreement: https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/firefox/

The privacy policy for 1.1.1.1 is instead: https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/privacy-policy/

In both cases you can see:
> All information collected by Cloudflare, no matter whether such information is part of Cloudflare’s temporary or permanent logs, will be cleansed of any personally identifiable data (including your IP addresses). Additionally information that is stored as part of Cloudflare’s permanent logs will be further anonymized.

An important question: is the main difference between the two that Cloudflare is sharing this DNS data with Mozilla? It is not stated explicitly that it is not the case.

The only difference I can see is that the data used for Cloudflare permanent logs contains less fields, but I would like to know if there is an agreement between Cloudflare and Mozilla about sharing such data first.

**Comment by randomshell** [comment]
Yes, they mix up Mozilla and Firefox (the browser).
You're right, form those lines seems both have access to it, even if the data collected in the permanent logs is less, as you said too.
Feel free to close the issue. Thank you for your time.

**Comment by csagan5** [comment]
@randomshell time is not the problem, but I am wary of situations like this where something _seems_ more privacy-safe while in reality it has some hidden caveat.

If I interpret these privacy rules incorrectly and there is just Cloudflare/APNIC with access to data then we can add it; if unfortunately there is less data collected but it is shared between Cloudflare and Mozilla, then I vote against adding this. Probably users of Bromite would not select the option since it is equivalent to regular Cloudflare with the added "benefit" that another company can use the (anonymised) data for whatever purpose.

Thanks for your interest, we all have to stay vigilant; I still hope there will be some day an EFF-sponsored DoH server but they do not seem much interested in operating services.

**Comment by Madis0** [comment]
Isn't this a matter of Cloudflare + APNIC vs Cloudflare + Mozilla? 
The Mozilla version does not contain any references of APNIC, so it is just about Firefox's telemetry, if any.

**Comment by csagan5** [comment]
@Madis0 the Mozilla version means Mozilla + Cloudflare + APNIC
