### ISSUE TITLE
Add an option to delete cookies and site data when closing the browser

### ISSUE THREAD

**Issue by KatoriYuu** [bromite/bromite#1647]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
I don't know.

### Describe the solution you would like
Everytime the browser is closed, all cookies and site data should be cleared, except those which are defined as exceptions.

### Describe alternatives you have considered
I don't have any.

**Comment by KatoriYuu** [comment]
Currently cookies can be blocked, but that causes some sites to be broken.

**Comment by csagan5** [comment]
@uazo the [patch for cookies was this one](https://github.com/bromite/bromite/blob/85.0.4183.86/build/patches/Session-only-cookies-support.patch), but as far as I remember it was not effective? Since on desktop it works differently.

Do you think it could be worth re-introducing it?

**Comment by friendlytherapist** [comment]
This request gets asked extremely often. Even I posted this request a long time ago. The devs refuse to implement and give no explanation. Enjoy getting your issue closed.

**Comment by uazo** [comment]
> Do you think it could be worth re-introducing it?

I don't know, cookies are only part of the information kept that can be used to track the user.
it should be modified so that it deletes all information other than cookies, keeping only the domains specified by the user, I think it is feasible.

**Comment by csagan5** [comment]
> it should be modified so that it deletes all information other than cookies

No, I would keep it only in scope for cookies as it was originally. With the expanded scope of deleting everything on exit it is equal to all the other duplicate requests about this feature; the advice is the same: use always incognito mode.

But regardless, the old patch was removed because uneffective on Android due to how apps are never actually closed.

**Comment by uazo** [comment]
> the old patch was removed because uneffective on Android due to how apps are never actually closed

no, you're wrong. the patch works, the cookies are deleted at the next restart.

**Comment by csagan5** [comment]
> > the old patch was removed because uneffective on Android due to how apps are never actually closed
> 
> no, you're wrong. the patch works, the cookies are deleted at the next restart.

The patch was improved after [this discussion](https://github.com/bromite/bromite/issues/142#issuecomment-670152861); I do not remember exactly why it was dropped, perhaps it was removed to re-focus on always incognito mode since it added another burden for maintenance (and for the reason you mentioned, that cookies alone are not sufficient to offer real privacy).

**Comment by uazo** [comment]
> Perhaps it was removed to re-focus on always incognito mode since it added another burden for maintenance (and for the reason you mentioned, that cookies alone are not sufficient to offer real privacy).

yes, I remember that too.

however, I think that giving the possibility to cancel at startup all data could also be useful for always incognito, as a mechanism to compensate for any bugs.
moreover I always have the doubt that h3 (quic) keeps data (the temporary user certificates sent by the server, the channel id) and considering that (for now) I cannot disable it in bromite it would be useful.
