### ISSUE TITLE
Add a 'Preview page incognito' option

### ISSUE THREAD

**Issue by oiao** [bromite/bromite#1697]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
No

### Describe the solution you would like
Add a 'Preview page incognito' option. 

The 'Preview page' feature for hyperlinks is quite useful for quick scans through a website. In some cases, the user might not want the previewed page to have access to the main session's cookies. For such cases an option to preview a page in an incognito environment would be great. 

### Describe alternatives you have considered
Of course the same can be achieved with the 'Open in Incognito tab' option, but incognito previews from a regular session would be a nice addition.

**Comment by uazo** [comment]
in my opinion, such a feature makes little sense simply because the anonymous profile is currently one and shared with the incognito session.
so an ephemeral incognito view could bring information via url between the normal session and the incognito one. this could also happen normally but the user is more aware of it if he can see the list of incognito tabs through the ui and decide to close all the incognito tabs leading to a reset of that session.

**Comment by csagan5** [comment]
Yes, Chromium-based browsers do not have the Firefox feature of sandboxing each website (although some progress has been made in that direction).

I do not think this would be a great improvement from privacy perspective.
