### ISSUE TITLE
Separate option for always-incognito mode.

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#1713]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?
I don't know.

### Describe the solution you would like
Right now, the option for always opening links in an incognito tab is the only way to have always-incognito mode. However, users should still have the option of opening links in apps when possible.

I believe that a separate toggle would be the simplest solution.

### Describe alternatives you have considered
Another option would be doing it like Firefox: if you exit the app in incognito, the app will open in incognito.

**Comment by hollowghost00** [comment]
Well now I feel stupid. Even if "Open links in incognito tabs always" is off, if you're incognito, links don't open in apps.

Now I'm not sure of what to do. I *assume* that even if a flag was added to allow that, if the aforementioned option was turned on for always-incognito, opening links in apps would still not work. I would still like always-incognito to be separate because of that. Should I close this issue and open another?
