### ISSUE TITLE
Clear history on close, like Firefox.

### ISSUE THREAD

**Issue by Nan123721** [bromite/bromite#1735]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not to my knowledge 

### Describe the solution you would like

Allow history to be cleared when the browser is closed, like is allowed on Firefox. A potential workaround is to always use incognito, but that also clears cookies, which some users, myself included may find annoying.

### Describe alternatives you have considered

Allow customization of what is cleared upon closing an incognito tab, so cookies and site data may be kept.

**Comment by Pranab009** [comment]
Please add this features.

**Comment by uazo** [comment]
there is already a pref `kSavingBrowserHistoryDisabled` that inhibits the saving of the history, we could make it accessible from the ui.
also I think it is possible to insert allow to modify the constant `kExpireDaysThreshold` from the ui, so that the user can also decide how many days to keep before they are automatically deleted.

**Comment by bat999** [comment]
Duplicate of #426
