### ISSUE TITLE
Remove the “Touch to Search” Function

### ISSUE THREAD

**Issue by JustAnUserLol** [bromite/bromite#1750]
Have you searched the issue tracker?
Yes
Have you read the F.A.Q.s? 
Yes
Have you read the README? 
Yes
Have you read the Wiki? 
Yes

### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
I am not Sure.

### Describe the solution you would like

Remove The “Touch To Search” Function because It's not good for Privacy

### Describe alternatives you have considered
It is possible to Disable It in settings, but Removing the function is better I think.

![photo](https://telegra.ph/file/77d2761e7a1b0298ecdd2.jpg)

**Comment by csagan5** [comment]
This is already disabled by default however I do not think it works when enabled.

**Comment by NSTAdventure** [comment]
bruh 🗿🗿🗿🗿🗿
i literally disagree
that feature is usefull as clean hat on the store 
🗿🗿🗿🗿

**Comment by csagan5** [comment]
@uazo I have been trying to figure out why this does not work, and whether it is possible to make it work, without any success.

The `ContextualSearchManager` is active and gets all the tab-related events, but `mSearchPanel.isActive()` (see [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/src/org/chromium/chrome/browser/contextualsearch/ContextualSearchManager.java;l=423;drc=e93f480dcacd119a7709495797228e6744761c73;bpv=1;bpt=1?q=issearchpanelactive&ss=chromium%2Fchromium%2Fsrc)) is always false.

If you have time please check if you can figure this out; then we can either allow it or disable it altogether if it cannot be made to work with other search engines.

**Comment by uazo** [comment]
> whether it is possible to make it work, without any success

did I get it right? would you like to be able to reactivate the "touch to search"? no, don't do it, better if it doesn't work!
this function sends the selected words to google servers for a search - every time I select a word -, and among the flags there is also the possibility to send the page url ... why reactivate it?

**Comment by csagan5** [comment]
> this function sends the selected words to google servers for a search - every time I select a word -, and among the flags there is also the possibility to send the page url ... why reactivate it?

Have you read my comment fully or only partially? Let me paste it here again:
> we can either allow it or disable it altogether if it cannot be made to work with other search engines.

Notice the "other" before "search engines".

**Comment by uazo** [comment]
> Have you read my comment fully or only partially?

of course I read it! (then if I understand it it's another thing :)
and mine? "this function sends the selected words to google servers for a search **every time I select a word**"

**Comment by csagan5** [comment]
@uazo you are stating that I want to add functionality that sends information to Google servers, which is ridiculous considering that I started this whole project to avoid that. I wonder why are you doing that?

The functionality "Touch to Search" is present in a half-baked state and that is why I started investigating how it is currently (not) working, since most of the code is active and running all the time.

Once it is figured out how it works a decision should be made on whether to keep it around or not. The only way this functionality can be kept is if it is made to work with **any** search engine, not only Google. Which is precisely what [I stated originally in my comment](https://github.com/bromite/bromite/issues/1750#issuecomment-1061095271).

Let me make a table:
| Question  | When using search engine Bing  |  When using search engine DuckDuckGo | When using search engine Google  | When using search engine Ecosia  |
|---|---|---|---|---|
| Does it send selected words to Google?  |  No | No  | **Yes**  | No  |

It was originally not tied to Sync services, hence I suspect it could work with any search engine, but I do not know for sure and definitely should behave the same for any search engine without any vendor-specific extra information provided.

**Comment by uazo** [comment]
> you are stating that I want to add functionality that sends information to Google servers

ok, i was inaccurate, to the search provider.

> The only way this functionality can be kept is if it is made to work with any search engine, not only Google.

my question is simply this: why do I have to send every word I select to the search provider? or even, who would ever want it? because I don't think bromite users would activate it. and above all, why waste time on this?

what am I missing?

**Comment by csagan5** [comment]
> > The only way this functionality can be kept is if it is made to work with any search engine, not only Google.
> 
> my question is simply this: why do I have to send every word I select to the search provider? or even, who would ever want it?

Why do you want to decide this for all users? I am neutral about user choice, except when it is privacy-invasive. In this case the functionality is already present and there is a toggle, disabled by default. So the answer to your question is: because the user decides so and you or me have no relevance on deciding what the user wants to do in this case since it is no different than making a web search.

> and above all, why waste time on this?

> The functionality "Touch to Search" is present in a half-baked state and that is why I started investigating how it is currently (not) working, since most of the code is active and running all the time.

> what am I missing?

That "touch to search" is the same as search.

**Comment by csagan5** [comment]
> > since it is no different than making a web search.
> 
> but the difference is: one thing is to want to search, one thing is to select to, for example, simple copy.

It is not: you first have to enable "Tap to search".

> > I am neutral about user choice, except when it is privacy-invasive.
> 
> at this point I'd like to understand why you don't consider this privacy-invasive. why then remove safe search?

Safe search is not the same as regular search. It only works using a single third-party; you cannot choose the safe search provider.

"Search when a word is selected" is the same as selecting the word and then tapping "Search", if the user has chosen to do so. But I have better things to do than keep discussing this; let's close it here, ok? I do not need to convince you or anyone else.

**Comment by uazo** [comment]
> It is not: you first have to enable "Tap to search".

Same as safe-search...

> you cannot choose the safe search provider.

unless you develop it

> let's close it here, ok?

I agree!

> I do not need to convince you or anyone else.

of course the opposite is also true

**Comment by csagan5** [comment]
Fixed in `99.0.4844.58`.
