### ISSUE TITLE
Allow changing the number of days to keep navigation history

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1870]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

[yes](https://github.com/uazo/bromite/blob/next/v99/build/patches/Allow-change-keep-navigation-history.patch)

### Describe the solution you would like

have the possibility to choose how many days to keep of the history

### Describe alternatives you have considered

That patch allows the user to choose how many days of history navigation to keep or possibly not to record at all in normal sessions.

**Comment by csagan5** [comment]
It looks like a good feature, however the patch description could use a bit more explanation for the feature added, for example how it works for "0".

Shouldn't there be also an option for "never"?

I noticed the change about padding to 0px, do you know why is that needed?

**Comment by uazo** [comment]
I've changed the ui and added some explanation ([see](https://github.com/uazo/bromite/blob/next/v99/build/patches/Allow-change-keep-navigation-history.patch)).
do you want me to do a pr or do you prefer to do it yourself?

**Comment by csagan5** [comment]
It's better if you do it so that attribution is visible also via GitHub.

**Comment by csagan5** [comment]
Fixed in `99.0.4844.58`.

**Comment by SebiderSushi** [comment]
Hello, i came to report that in version `99.0.4844.58` this new feature does not function as a user might expect.

### Expexted behavior
I expect my browser to never clear my browsing history without my consent and i expect that i can keep my browsing history for as long as i want.

### Observed bahavior
The feature comes with the default setting to keep only 90 days of browsing history which means that every user that does not know about this feature will loose data without expecting it.

I have set the new setting to "Never", expecting Bromite to "Never expire history", that is to keep the browsing history forever. I found this to be a reasonable interpretation of the setting because i did not find any other way to choose the desired behavior.
However, just like uazo hinted in their comment "Never == 0", this causes Bromite to keep 0 days of history.

### Possible solution
The current settings option "Never" could be changed to "0" or "No history".
There should be a new setting that actually allows to keep the browsing history forever. This option should be the new default to prevent any surprises for users that are unaware of this new feature. This option could still be labeled "Never" or "Unlimited" / "Forever", all of which should be intuitive in combination with the settings title "Expire history days threshold" or the settings description "Number of days to keep navigation history." respectively.

**Comment by uazo** [comment]
> The feature comes with the default setting to keep only 90 days of browsing history which means that every user that does not know about this feature will loose data without expecting it.

90 days is chromium's immutable default

> I have set the new setting to "Never", expecting Bromite to "Never expire history"

yes, the indication can be misleading. maybe it's better "Keep no history"

> There should be a new setting that actually allows to keep the browsing history forever

I don't know if it's worth it

**Comment by SebiderSushi** [comment]
Ah, thanks. I never noticed that. If the 90 days limit comes from Chromium itself then i do not expect you to fix it. I do wonder why the chromium devs decided not to communicate this anywhere, huh.

Changing the "Never" option label would still be appreciated since it really only makes any grammatical sense when combining it with "expire history" yeah...

**Comment by tiklii** [comment]
> > There should be a new setting that actually allows to keep the browsing history forever
> 
> I don't know if it's worth it

It is. The option to keep your browsing history in a browser is certainly a crucial 'feature'.

Also, just to add, I also got burnt by the never==0 option.

**Comment by csagan5** [comment]
> > I have set the new setting to "Never", expecting Bromite to "Never expire history"
> 
> yes, the indication can be misleading. maybe it's better "Keep no history"

I noticed this and plan to change it for next release.

> > There should be a new setting that actually allows to keep the browsing history forever
> 
> I don't know if it's worth it

I also thought we should have had this for the `Never` option. Server-side certainly can remember our histories forever, so why should we not have that capability?

**Comment by uazo** [comment]
> so why should we not have that capability?

I would not like to introduce performance problems, but they are choices nonetheless.
I think if you add an option with a very large value you get to that goal.

**Comment by csagan5** [comment]
> > so why should we not have that capability?
> 
> I would not like to introduce performance problems, but they are choices nonetheless.

History is not loaded into memory all the time.

> I think if you add an option with a very large value you get to that goal.

That is a hack.

**Comment by uazo** [comment]
> History is not loaded into memory all the time.

I wasn't thinking about memory, but about the performance of sql db (which I don't know)

**Comment by csagan5** [comment]
SQLite on an average device will be fine with anything that a human can generate.

**Comment by preall** [comment]
@csagan5 Could you please consider reopening this issue?
There is no warning that the history will be deleted and I want to keep my history as long as I want.
Thanks

**Comment by SebiderSushi** [comment]
Issue https://github.com/Eloston/ungoogled-chromium/issues/1676 seems to indicate that they have this feature (if that is of any use, and applicable to android).

**Comment by csagan5** [comment]
@preall the text has already been changed; for an extended history a new issue should be created.

The patch @SebiderSushi is referring to is this one: https://github.com/Eloston/ungoogled-chromium/blob/61d47f6bcdec8c71151144f07c7f8a0197eeca7a/patches/extra/ungoogled-chromium/add-flag-to-disable-local-history-expiration.patch

**Comment by SebiderSushi** [comment]
Thank you very much for the new option in version `100.0.4896.57` to keep the history forever.  
This completely resolves any issues i've described.

**Comment by 0rt** [comment]
I knew it closed but please allow my applause for this fix. I stick to Firefox for years because it allow I set the history entries number and purge time limit long than 6 months, even I knew Chrome/Chromium is a better browser. I keep google the problem "how to store chrome history more than 90 days" every a few months and this time new answer pop up... thanks
