### ISSUE TITLE
Anti fingerprinting 

### ISSUE THREAD

**Issue by nahcos** [bromite/bromite#1873]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Improved anti-fingerprinting engine. Based on Bromite fingerprinting test, the browser scores 5/9 however, it leaks lots of vital info such as: GPU, plug-in, user agent, etc. 
Given the private nature behind the development of Bromite browser, I would expect it to excel at privacy, rather than be in the middle of the pack. 

### Describe alternatives you have considered

Both, Brave and Mull do a much better job for privacy & fingerprinting while still preserving a positive browsing experience.

**Comment by uazo** [comment]
> it leaks lots of vital info such as: GPU, plug-in, user agent, etc.

um, it seems like a bogus issue to me.
sure both are likely to have room for improvement, but I checked the code of brave and the quality of the antifingerprinting is more or less similar to that present in bromite.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/Fingerprinting

> I would expect it to excel at privacy, rather than be in the middle of the pack.

Go read the papers about fingerprinting and how things work instead of checking any arbitrary score by any website.

**Comment by nahcos** [comment]
> See https://github.com/bromite/bromite/wiki/Fingerprinting
> 
> > I would expect it to excel at privacy, rather than be in the middle of the pack.
> 
> Go read the papers about fingerprinting and how things work instead of checking any arbitrary score by any website.

It seems to me you are the one not reading. 
I did mention that I've used the Bromite Fingerprinting Test (not some arbitrary score on any website) on several installed browsers. Plus, I did read the documentation you are referring to and yet, the empirical results yielded by direct comparison clearly shows that Brave (at strict setting) and Mull by default do hide the info mentioned above, which Bromite does NOT. Do you want me to post comparative screenshots to believe that this is NOT a bogus issue? 

Furthermore, rushing to close the ticket only shows me that there is no interest in further investigating this. I wonder why?

**Comment by csagan5** [comment]
> I did mention that I've used the Bromite Fingerprinting Test (not some arbitrary score on any website)

That is not a score.

> I did read the documentation you are referring to

Let's try again, together:
> Bromite aims at reducing leaked information and in some cases it randomises high-entropy measured values to prevent precise fingerprinting.

"Precise fingerprinting" means that you cannot get the same fingerprints **after** refreshing the page. That is the only test you can do.
I will change the text to be clearer, in the hope that it helps.

Additionally, there are tens of different ways to get fingerprints and Bromite (and other browsers) only cover the most common ones. You cannot find any reliable score because there is not a comprehensive collection of all the ways one can collect a fingerprint, despite some libraries or websites have good selections of them.

**Comment by csagan5** [comment]
> Now we're talking. While I understand your points clearly, the ranking above, though admittedly subjective, is based on what the browsers were showing, or not.
> 
> Mull does, unquestionably, the best job at anti-fingerprinting by hiding/removing most parameters. Do test it, please! All the other browsers seem to employ a different strategy for anti-fingerprinting, which replaces original values for some randomized ones.

"Unquestionably": it is always questionable. Your bias here is that removing or hiding is better than randomizing them; that is discussed _ad nauseam_ in the papers I linked and I have no interest to discuss it further here.

Bromite uses a mix of removing and randomizing as you can see from the test page.

> All I'm asking if to further investigate and see if my comments and tests have any merit. Don't just dismiss it, just because... 

They have no merit because you did not go deep enough in understanding the problem and/or the tests/measurements about fingerprinting, thus it is not helping. You posted this issue thinking that the number of fingerprints is a score and now you are saying something else, that showing no fingerprints is better. That is...according to you.

> After all, that's why we're here, to make improvements, no?

The correct approach (in my opinion) to make a positive contribution is: go find widely used fingerprinting techniques (there are quite a few new ones since when mitigations were introduced in Bromite), for example by looking at what commonly used commercial or open source libraries do (yes, this takes some effort).
Afterwards measure how effective they are in Bromite (try to track yourself across incognito sessions or after deleting all data from Bromite); at that point one could even start thinking of introducing a new mitigation, but not any earlier than that.

Note that you did not start a discussion, you reported an issue (in disguise of a feature request), so you were certain this was a problem and needed to be reported as such, even before understanding how fingerprinting or the mitigations work.

**Comment by nahcos** [comment]
Points taken, I agree with your comments.

Thanks!

**Comment by csagan5** [comment]
Some examples on why removing information does not always work:
1. might break Javascript of some websites, which would then be reported as a bug
2. you cannot remove all sources of fingerprinting because there is not a full list anywhere (although upstream Chromium/Firefox have been shifting focus on this, see https://github.com/bslassey/privacy-budget/blob/master/faq.md)
3. if you remove source A, you automatically enter the set of users with A-removed; that set is small enough that, combined with any of the sources from (2), it helps to identify you better, thus leading to more efficient fingerpriting

I am not here to discourage anyone from doing further research (please do! we have a terrible lack of research in this field) and patches are always welcome, but situation is more nuanced than what it superficially looks like.

**Comment by nahcos** [comment]
Thanks for the details, Carl! I've done a lot of reading on the topic (the suggested links provided excellent material) and I see the intricacies of the concept - it's definitely not black and white.

I appreciate your guidance.

Best!
