### ISSUE TITLE
Respect #omnibox-ui-hide-steady-state-url-scheme

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#193]
**Is your feature request related to privacy?**
Somewhat - anti-phishing and less false sense of security

**Is there a patch available for this feature somewhere?**
Upstream

**Describe the solution you'd like**
Previously, Chromium had a flag called `#omnibox-ui-hide-steady-state-url-scheme-and-subdomains`.

You seemed somewhat supportive of the flag in #97, but you didn't like that it did two things at once:
>[...] the problem is also that the option disables everything at once, otherwise I would leave it in the preferred state by default.
>The alternative would be to develop flags to toggle these individual hiding options, but [...] I have no commitment to develop the flags.

Now, as of Chromium 71, the flags have been split to two:

* `#omnibox-ui-hide-steady-state-url-scheme`
* `#omnibox-ui-hide-steady-state-url-trivial-subdomains`

...so I made a new issue that may make you reconsider it now. Here are my pros and cons:

Pros of enabling the flag:

* No more distracting green highlights of the `https://` and lock
* Anti-phishing - see more of the URL itself on a small screen
* Lack of `https://` would make the user focus more on URL, rather than getting false sense of security from the https protocol (anecdotal; may conflict with your POV at #171)

Cons of enabling the flag:

* Less accuracy in terms of actual protocol display 
* If you keep the current Bromite behaviour of `http://` (visible)with this flag enabled, it may be harmfully misleading due to what people are used to see (`https://` visible, `http://` hidden; anecdotal as this flag would still be disabled by default anyway)

To be extra clear - I only want `#omnibox-ui-hide-steady-state-url-scheme` to be respected; `#omnibox-ui-hide-steady-state-url-trivial-subdomains` should always be disabled as it is the _actually_ misleading one (hiding `www.` and `m.`).

<details><summary>Comparison screenshot</summary>
Chromium on top, Bromite on the bottom. <br/>
Notice how Chromium can display the full date in the URL and therefore give a better idea of what the user is looking at.

![screenshot_bromite_20181202-122847](https://user-images.githubusercontent.com/8611110/49338744-b7f4c380-f62e-11e8-967d-c140ed467aae.png)

</details>
<br/>

**Describe alternatives you've considered**
You could at least make `https://` and the lock gray by default as in desktop Chromium.

**Comment by csagan5** [comment]
It is becoming a somewhat complicated situation, but thanks for your analysis and exposition.

My POV can and should change, my opinion is not perfect or immutable. I am trying to stick to the goals of Bromite (which can be interpreted in many ways, of course) and keep the experience somewhat consistent.

What I observe in current Bromite:
* for HTTPS sometimes a green padlock is displayed, then after half a second the padlock completely disappears (perhaps because the certificate is not EV or similar)
* if the page theme color is green, padlock becomes gray; clicking on the padlock displays a green `https://`
* HTTP pages have the `http://` protocol displayed, and an `i` with circle; if there are forms, I believe a warning sign is instead displayed

(other combinations have probably not been observed by me in this simple test)

What I believe would be best is:
* gray padlock and gray `https://` prefix for HTTPS pages, never hidden and never changing color
* no `http://` omitted for HTTP pages and perhaps we leave the behaviour of the `i` or warning symbol

Now, how to achieve this situation, is beyond my current comprehension. @Madis0 which flags should we look to achieve this result and, if not possible, to edit their code in such direction?

Note that I disagree with the omission of any protocol prefix from the URL; if visualising the URL was of any real concern, I believe a different address bar widget could have been engineered upstream by now (changes to the address bar are a big portion of all the changes ever happened to Chromium during its development history).

**Comment by Madis0** [comment]
>for HTTPS sometimes a green padlock is displayed, then after half a second the padlock completely disappears (perhaps because the certificate is not EV or similar)

That is only the case for [mixed content](https://mixed.badssl.com), in Chromium as well.

> if the page theme color is green, padlock becomes gray; clicking on the padlock displays a green `https://`

I guess you mean [this](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) in pages like GitHub and ArsTechnica (white on black there, other colors in other sites).

>HTTP pages have the http:// protocol displayed, and an i with circle; if there are forms, I believe a warning sign is instead displayed.

[That is correct.](http://http-textarea.badssl.com/)

Another observation by me is that due to some Bromite patch, sites without a path have [black `https://` with a green lock](https://www.bromite.org/) and ones with a path have [green `https://` with a green lock](https://www.bromite.org/news/2018-10-18-bromite-v70-released-new-logo).

---
> which flags should we look to achieve this result and, if not possible, to edit their code in such direction?

>gray padlock and gray `https://` prefix for HTTPS pages, never hidden

The same `#omnibox-ui-hide-steady-state-url-scheme` makes the padlock gray but doesn't change the `https://` color, presumably because the goal is to hide it anyway.

>and never changing color

I don't think it is very easy to make it never change color, due to the _theme-color_ attribute and Bromite bug described above, though what I think you could do is just find the code that turns it green and make it gray instead.

>no `http://` omitted for HTTP pages and perhaps we leave the behaviour of the i or warning symbol

`#enable-mark-http-as` controls the symbol and makes the `http://` red and crossed out in the page info popup. Omission isn't controlled by the flag since it has been hidden for years already (and you have a patch to unhide it).

>I believe a different address bar widget could have been engineered upstream by now 

In Chromium 69, they initially did push out the original flag (that hid `https://`, `www.`, `m.`) for everyone. They then rolled it back a short while after and now are considering other approaches (such as this flag split) because [people got very vocal about it](https://bugs.chromium.org/p/chromium/issues/detail?id=883038). And yes, [they have a bigger goal in mind for all of this](https://www.wired.com/story/google-wants-to-kill-the-url/) (which I am cautious, but interested about).

**Comment by csagan5** [comment]
@Madis0 thanks for the information, most of it was unknown to me and I am glad you are following this.

> Another observation by me is that due to some Bromite patch, sites without a path have black https:// with a green lock and ones with a path have green https:// with a green lock.

I have no idea what could be causing this, could be some ungoogled-chromium patch.

> In Chromium 69, they initially did push out the original flag (that hid `https://`, `www.`, `m.`) for everyone. They then rolled it back after a short while after and now are considering other approaches (such as this flag split) because [people got very vocal about it](https://bugs.chromium.org/p/chromium/issues/detail?id=883038). 

Was not aware that there were so many complaints, but glad so.

>And yes, [they have a bigger goal in mind for all of this](https://www.wired.com/story/google-wants-to-kill-the-url/) (which I am cautious about, but interested in seeing).

I have been reading about that "bigger plan" and I believe it is related to "signed exchanges" feature (https://developers.google.com/web/updates/2018/11/signed-exchanges), correct me if I am wrong. I do not like the strategy of pushing such big choices via Chromium, then having the other players adapt to them; I favour a public discussion in the interest of users instead.

To go back to this issue here: so the only change here would be that when `#omnibox-ui-hide-steady-state-url-scheme` is set, it should work as intended (like in Chromium). Correct?

I believe it could be done and we could set the default in Bromite to be as it is now, but when an user changes it then it would behave as per upstream.

**Comment by Madis0** [comment]
>I have been reading about that "bigger plan" and I believe it is related to "signed exchanges" feature (https://developers.google.com/web/updates/2018/11/signed-exchanges), correct me if I am wrong. I do not like the strategy of pushing such big choices via Chromium, then having the other players adapt to them; I favour a public discussion in the interest of users instead.

Oh god, so that's exactly what people thought it would be - Google's goal to serve AMP pages from _their_ servers, yet make them appear as they would've been sent by the page that is being served.
Although it could be useful for decentralizing some controversial content on the surface web (similar to Zeronet), so there's that...

>To go back to this issue here: so the only change here would be that when #omnibox-ui-hide-steady-state-url-scheme is set, it should work as intended (like in Chromium). Correct?
>I believe it could be done and we could set the default in Bromite to be as it is now, but when an user changes it then it would behave as per upstream.

Yes, this is what I would prefer.

**Comment by csagan5** [comment]
I checked this, in Bromite all flags to omit parts of the URLs are disabled because these flags are used around in the code and not configurable by the user (except the one you mentioned for the Omnibox).

So, restoring this option would make the hardcoded flags all around the codebase come into effect again, unless a bigger patch that removes each of them is coded.

Hiding parts of the URL - and furthermore no options to disable such hiding - is not something we want to go back to in order to allow hiding of the HTTPS prefix in the Omnibox with the recent `#omnibox-ui-hide-steady-state-url-scheme` flag.

**Comment by Madis0** [comment]
Alright. What about fixing the color to be consistently gray in HTTPS? Waiting for upstream to do that?

**Comment by csagan5** [comment]
@Madis0 I checked that part; there is also a red or green color assigned to the summary depending on the security status; I will not touch the color to avoid it being inconsistent with that other part, which I have no intention to change.

**Comment by Poopooracoocoo** [comment]
I just updated to Bromite 77 and even when "https" is green, the padlock stays black. I'd prefer if "https" were black too.
