### ISSUE TITLE
Ask to enable JIT when WebAssembly is used

### ISSUE THREAD

**Issue by easrng** [bromite/bromite#1932]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Right now, sites that require WebAssembly silently break until JIT is enabled. For an example of this, check the Cloudflare Workers dashboard if you have a Cloudflare account. There should be a prompt to enable JIT when window.WebAssembly is accessed.

### Describe alternatives you have considered

Ideally without JIT Bromite would use a WASM interpreter, but I'm not sure if V8 currently has one so that might be significant work. Injecting a JS polyfill might work, but would be slow probably and I don't know if one exists.

I could also just add a userscript that does something like this:
```js
if(typeof WebAssembly === "undefined") {
  Object.defineProperty(window, "WebAssembly", {
    get: () => new Proxy(null, {
      get: () =>alert("This site uses WebAssembly, which requires JIT. Please enable JIT from the site permissions menu.")
    })
  })
}
```

**Comment by csagan5** [comment]
I see that `typeof WebAssembly` results in `undefined`; I guess websites assume it is a regular Chromium and they do not check any capability? Something like https://stackoverflow.com/a/47880734 would work.

Enabling JIT is dangerous, an incomplete list of recent 0-days:
* https://github.com/r4j0x00/exploits/commit/7ba55e5ab034d05877498e83f144e187d3ddb160
* https://bugs.chromium.org/p/chromium/issues/detail?id=835887
* https://github.com/bromite/bromite/discussions/1927

If we had such prompt it would also be shown when a website is trying some exploits on the user (via WebAssembly), so the message would need to mention this.

I can leave this issue open for a while in case someone wants to submit a patch, but might be tricky because you want to show only 1 prompt regardless of how many objects are created on the page (and on sub-frames), the answer to the prompt needs to be remembered etc so I am generally not in favour of adding all this complexity.

**Comment by Zoraver** [comment]
Something to note is that the Microsoft Edge team is [working on a WASM interpreter](https://microsoftedge.github.io/edgevr/posts/Introducing-Enhanced-Security-for-Microsoft-Edge/#introducing-drum-brake-a-webassembly-interpreter) that they plan on upstreaming to Chromium. With luck, the UX problem that prompted this issue will be resolved soon without Bromite needing to do anything to handle this case.
