### ISSUE TITLE
Page info should display more of the URL by default

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#195]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
Not sure

**Describe the solution you'd like**
Chromium displays the URL of the page in page info popup in two rows. 
If it doesn't fit to two, the user can tap and show more rows (up to some amount, I think four rows).

<details><summary>Comparison screenshot</summary>
Before

![screenshot_bromite_20181202-154246](https://user-images.githubusercontent.com/8611110/49340545-d6b48380-f649-11e8-98ca-ced882d9c2fa.png)

After
![screenshot_bromite_20181202-154253](https://user-images.githubusercontent.com/8611110/49340550-e764f980-f649-11e8-9701-de312f831a5a.png)

</details>
<br/>

[Expandable long URL](https://example.org/Lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed-do-eiusmod-tempor-incididunt-ut-labore-et-dolore-magna-aliqua-Ut-enim-ad-minim-veniam-quis-nostrud-exercitation)

[Unexpandable - too long URL](https://example.org/#Lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed-do-eiusmod-tempor-incididunt-ut-labore-et-dolore-magna-aliqua-Ut-enim-ad-minim-veniam-quis-nostrud-exercitation-ullamco-laboris-nisi-ut-aliquip-ex-ea-commodo-consequat-Duis-aute-irure-dolor-in-reprehenderit-in-voluptate-velit-esse-cillum-dolore-eu-fugiat-nulla-pariatur-Excepteur-sint-occaecat-cupidatat-non-proident-sunt-in-culpa-qui-officia-deserunt-mollit-anim-id-est-laborum)

I think Bromite should expand that initial limit to at least 20 rows, in order to display most URLs in full while still keeping the info area usable (security state, permissions, site settings).

**Describe alternatives you've considered**
Could at least remove the upper limit of expandability.

**Comment by csagan5** [comment]
You can tap the shortened URL to see the full URL up to the fragment `#`; the too long URL example you provided is such only because most of the text is after the fragment, if it were before the fragment it would work: [Long URL](https://example.org/?Lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed-do-eiusmod-tempor-incididunt-ut-labore-et-dolore-magna-aliqua-Ut-enim-ad-minim-veniam-quis-nostrud-exercitation-ullamco-laboris-nisi-ut-aliquip-ex-ea-commodo-consequat-Duis-aute-irure-dolor-in-reprehenderit-in-voluptate-velit-esse-cillum-dolore-eu-fugiat-nulla-pariatur-Excepteur-sint-occaecat-cupidatat-non-proident-sunt-in-culpa-qui-officia-deserunt-mollit-anim-id-est-laborum)

I do not deem necessary to change the default upstream behaviour (tap to see the full URL except fragment).
