### ISSUE TITLE
DoH won't work if /etc/hosts can't be read

### ISSUE THREAD

**Issue by SnwMds** [bromite/bromite#1960]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.57

### Device architecture

armeabi-v7a

### Android version

8.1

### Device model

AllCall_S1_X

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

DoH won't work if the `/system/etc/hosts` can't be read by Bromite.

### Steps to reproduce the bug

1. Set the permissions of your `/system/etc/hosts` file to something less permissive (e.g. `chmod 600 /system/etc/hosts`)
2. Enable "Secure DNS" in Bromite and choose some provider from the list (e.g. Google)
3. Go to `dnsleaktest.com` and click at "Standard test"
4. You will see the IP addresses of your ISP, not the provider you have choose

### Expected behavior

I expect DoH to work even if the `/system/etc/hosts` file can't be read by Bromite.

**Comment by csagan5** [comment]
If that file cannot be read it is ignored: https://source.chromium.org/chromium/chromium/src/+/main:net/dns/dns_config_service.cc;l=125;drc=401f9911c6a32a0900f3968258393a9e729da625;bpv=1;bpt=1

What happens if you specify the custom DoH provider as `https://dns.google/dns-query` instead? Can you please provide a screenshot of the Secure DNS settings while problem reproduces?

**Comment by SnwMds** [comment]
> Can you please provide a screenshot of the Secure DNS settings while problem reproduces?

Sure, see below:

![Screenshot-2022-04-10](https://user-images.githubusercontent.com/46784020/162627173-55f17213-a9c6-40ac-b112-ec03da3523ed.jpeg)

Changing the permissions back to `644` and restarting Bromite fixes this issue. It also work if I just delete the entire hosts file.

**Comment by csagan5** [comment]
> Sure, see below:
> 
> ![Screenshot-2022-04-10](https://user-images.githubusercontent.com/46784020/162627173-55f17213-a9c6-40ac-b112-ec03da3523ed.jpeg)

With DoH configured to `https://dns.google/dns-query` you can resolve new addresses?

> It also work if I just delete the entire hosts file.

Anything related in `adb logcat` when the hosts file has the non-working permissions?

**Comment by SnwMds** [comment]
> With DoH configured to `https://dns.google/dns-query` you can resolve new addresses?

Yeah, I can still browse on any site without issues. 

> Anything related in `adb logcat` when the hosts file has the non-working permissions?

This line catches my attention:

```
W chromium: [WARNING:dns_config_service.cc(148)] Failed to read DnsHosts.
```

Here is the complete output of `logcat | grep -E (bromite|chromium)` on my device:

[logcat.txt](https://github.com/bromite/bromite/files/8459445/logcat.txt)

**Comment by csagan5** [comment]
> > With DoH configured to `https://dns.google/dns-query` you can resolve new addresses?
> 
> Yeah, I can still browse on any site without issues.

And the DNS reported by `dnsleaktest.com` is your ISP?

> This line catches my attention:
> 
> ```
> W chromium: [WARNING:dns_config_service.cc(148)] Failed to read DnsHosts.
> ```
> 
> Here is the complete output of `logcat | grep -E (bromite|chromium)` on my device:
> 
> [logcat.txt](https://github.com/bromite/bromite/files/8459445/logcat.txt)

Thanks; it is a warning because even without hosts no functionality related to DNS should be impacted.

**Comment by SnwMds** [comment]
> And the DNS reported by `dnsleaktest.com` is your ISP?

Yeah, it is.

> it is a warning because even without hosts no functionality related to DNS should be impacted.

I see.

**Comment by csagan5** [comment]
The cause seems to be this:
```
04-10 19:09:13.820  2773  2850 E chromium: [ERROR:ssl_client_socket_impl.cc(997)] handshake failed; returned -1, SSL error code 1, net_error -200
```
That `-200` should be `ERR_CERT_COMMON_NAME_INVALID`; so there appear to be actually 2 separate issues at work here:
1. DoH fails for the SSL failure above
2. when this DoH failure happens, somehow the underlying Android DNS provider is used

(2) is not expected at all, nothing should resolve if user has enabled DoH explicitly (not auto mode); I will investigate both.

If others want to reproduce the issue with the emulator, see this [SO answer](https://stackoverflow.com/a/65076881).

**Comment by csagan5** [comment]
> Can the bug be reproduced with corresponding Chromium version?
> No

It can be reproduced with Chromium; it is an upstream issue, please report it there.

**Comment by csagan5** [comment]
If you will file a bug upstream feel free to add some information I gathered [here](https://github.com/bromite/bromite/wiki/DNS-over-HTTPS#dns-internals) in your Chromium bug report, it could help them to reproduce/understand the issue.

Even if issue is in upstream Chromium next release will add a workaround for this odd system state so that DoH configuration is enforced more consistently; please report back if you will find any other issues with `100.0.4896.83`.

**Comment by SnwMds** [comment]
> If you will file a bug upstream feel free to add some information I gathered [here](https://github.com/bromite/bromite/wiki/DNS-over-HTTPS#dns-internals) in your Chromium bug report, it could help them to reproduce/understand the issue.

Thanks for the tips. I filled a bug report to the Chromium issue tracker:

https://bugs.chromium.org/p/chromium/issues/detail?id=1315278

> Even if issue is in upstream Chromium next release will add a workaround for this odd system state so that DoH configuration is enforced more consistently; please report back if you will find any other issues with `100.0.4896.83`.

I tried with the latest version and can confirm this is working as expected.

Thank you very much for fixing this on Bromite's side!

**Comment by csagan5** [comment]
Well done, it has already been merged into [another issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1251715) with this [comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1315278#c3); I have documented on [Bromite's wiki](https://github.com/bromite/bromite/wiki/DNS-over-HTTPS) the difference in behaviour.
