### ISSUE TITLE
Support user-specified adblock filters

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#2]
This issue composes of multiple parts:
* ~~a new tab/UI to manage the adblocking feature~~ will not implement this
* logic to download the adblock filters and store them
* logic to parse the adblock filters (or an intermediate format)
* users can of course customize where the adblock filters come from (URLs)

The projects we could look at are adBlock and uBlock origin and other browsers that implement such functionality.

**Comment by hexauniverse** [comment]
For me using ublock origin filter syntax seems most preferable. Moreover, uBO supports adguard filters, that, in my opinion, are the best in coverage ads. It would be nice to realize their potential here.

**Comment by csagan5** [comment]
I am familiar with uBlock origin; uBO does not enable adguard filters by default but uses EasyList+EasyPrivacy+some others, I am going to try to cover the same lists.

**Comment by dimqua** [comment]
@hexauniverse AFAIK, adguard uses adblock plus syntax.

**Comment by csagan5** [comment]
Right now the biggest problem I see is that the original NoChromo patch is a very simplified request blocker, it has no support for the options for example, or for the selectors.

Comparing to SWE (I recently could give a look to their commits), they use [WebRefiner](https://webtech-devx.qualcomm.com/swe/docs/articles/en/web-refiner.html) there, which is quite advanced.

To complicate further the picture, Google is developing their own in-house adblocking, which makes it somewhat not a good choice to try to add WebRefiner to latest Chromium codebase: it might be better to just mod Google's own safebrowsing-with-adblocking.

So for now I will just maintain the current simple approach to ad blocking, and wait for Google's own adblocker to mature. They'll likely add some external API to check what to block and/or whitelists, which we do not want.

**Comment by csagan5** [comment]
I have added a wiki page to document adblocking engines used in Chromium browsers: https://github.com/bromite/bromite/wiki/AdBlocking

**Comment by csagan5** [comment]
The embedded adblock filters are updated every time Bromite is built for a new Chromium release; since these releases are often enough, I will close this enhancement issue for now.

**Comment by csagan5** [comment]
Reopening this issue because I plan to implement download of adblock filters. This would afterwards allow something like #33.

For now I am discarding having a configuration tab, too complex, but we will still have a user preference URL where to fetch the filters from, and baked-in filters as a fallback.

**Comment by DragoCubed** [comment]
I have a kinda unrelated question for you csagan5. Where did you learn programming?

**Comment by sevospl** [comment]
Bump. When will this be available? I'd love to have the ability to choose own filter lists!

**Comment by projectextremum** [comment]
Is it possible to implement it as a single text file that can be edited from within bromite. Eg: from a custom URI.

**Comment by leedoyle** [comment]
Would be cool to also have the ability to disable third party java scripts and media (like in uBlocks "advanced" mode).

**Comment by kitkatloyalist** [comment]
uBO seems to also hybridize UserScript.  Refer to their Experimental filter set.  Instead of blocking google analytics it replaces it with neutered version for example.

More power is more better.

**Comment by Laicure** [comment]
As it seems now, it works well though as a maintainer of a [hosts file](https://github.com/Laicure/HostsY_hosts) for adblocking, I suggest that it must somehow include a "load hosts file" or something to update the adblocking list.

My scenario hours ago:
- Use Bromite (latest version as of writing this)
- Turn off DNS66
- Navigate to usual site (kissanime.ru)
- Works well (things being blocked)
- Tried tapping a link, pop-up shown
- Tried to check the domain responsible for the pop-up (used Chrome Beta 70 for the net-internals)
- Found and [updated](https://github.com/Laicure/HostsY_hosts/commit/d9ad9454965be0713aae59951d0c2f68e60ad1bc) the hosts file
- Update DNS66 sources
- Enabled DNS66
- Tried Bromite again as above
- Domain blocked, no more pop-ups

**Comment by foss-rocks** [comment]
Hi @csagan5,
I'd like to report a minor logic flaw related to Bromite and in particular this issue but the users.noreply.github.com email keeps bouncing. Could you please contact me or just have a look at the repository I shared?

**Comment by foss-rocks** [comment]
Hi!

Because Bromite ships with hard coded adblock filters, every version is identified by the rules it has. In other words, the [User-Agent-anonymize.patch](https://github.com/bromite/bromite/blob/master/build/patches/User-Agent-anonymize.patch) doesn't really work without supporting user-specified filters (this issue), thus differing from the release apk.

I released a public test page that shows your current build, working for the latest v76 versions and some older ones. You can find it at https://randshell.github.io/bromite-version-check/, repository [here](https://github.com/randshell/bromite-version-check).

This issue has been previously [discussed](https://github.com/bromite/bromite/commit/3a9775c5c03fea81315a9f0ccd8b7afa8e2258f2) with @csagan5.

**Comment by csagan5** [comment]
Yes, I confirm the above.

@foss-rocks the identification of version will only be mitigated if the feature described in this issue exists and it is configured to auto-update by default

**Comment by csagan5** [comment]
With `77.0.3865.81` an URL for the ad filters is being used internally, which we can in future expose in the UI without too much hassle; so this issue should be soon addressed.

**Comment by ouzowtf** [comment]
Does Bromite use the API for filtering that Google wants to get rid off in one of the next Chrome (and certainly Chromium) versions?

**Comment by csagan5** [comment]
> Does Bromite use the API for filtering that Google wants to get rid off in one of the next Chrome (and certainly Chromium) versions?

It was never used in Bromite, it's an API for extensions.

**Comment by ouzowtf** [comment]
Sorry, I just have to ask again for me to not misunderstand you: the new v77 way of filtering is a different filtering method than the filtering used by extensions like uBlock and that Google wants to eliminate?

**Comment by csagan5** [comment]
@ouzowtf the new way and the old way are C++ patches which modify directly the browser code. So they are both different than how extensions work. Extensions use code written in Javascript, to name the biggest difference, and they do not run inside the browser itself.

**Comment by csagan5** [comment]
@ouzowtf on this topic: see my comment here: https://github.com/GrapheneOS/Vanadium/issues/10#issuecomment-515671578

The retiring of the extensions API used by adblocker is related to the Network Service, but they are both part of a bigger strategy of tracking requests IMO.

**Comment by ouzowtf** [comment]
Thanks for this insight! :)

**Comment by githubsucks-usegitlab** [comment]
When will there be an easy way to set our own filters? A lack of solid adblock is the only reason why I am not using this Web browser over e.g. Dolphin. It's bad enough the lack of Chrome extension support but given what I understand this browser's goals are that's okay.

What's really kind of not okay is that from a privacy point, proper adblock and any tracking isn't implemented or at least a method of being able to do this myself isn't implemented.

We don't need a fully tab for customising adblock rules. Just let us set our own filters in an easy to use manner either by allowing us to add/edit our own hosts list or otherwise.

This browser already has more than enough features and it's incredibly stable. Having only the bare minimum super obvious ads "kind of" being removed, and none of the tracking that goes with it being blocked, just doesn't cut it though.

Thanks for understanding.

**Comment by csagan5** [comment]
> When will there be an easy way to set our own filters?

This is an open source project, you are not entitled to ask "when", sorry.

**Comment by sevospl** [comment]
@githubsucks-usegitlab if you want, use Adguard for a while -- it allows you to use custom filter lists.

**Comment by FirstDefolD** [comment]
Will the option "Element selection mode" be added to highlight the unnecessary on the page and block as in the PC version. That is, you choose what to block yourself, because not all ads are deleted and sometimes you need to remove the interfering buttons and callouts on the page.
I give an example below:
![68071464-11f88e80-fd94-11e9-8f14-8a45b6c40c04](https://user-images.githubusercontent.com/57290638/68071539-cdb9be00-fd94-11e9-8046-040c581d508f.png)
![68071472-23da3180-fd94-11e9-8338-1c1b1c05b1ea](https://user-images.githubusercontent.com/57290638/68071542-d14d4500-fd94-11e9-88e6-e62581e0d8da.png)
![68071480-381e2e80-fd94-11e9-95bb-7f667d28bc17](https://user-images.githubusercontent.com/57290638/68071543-d5796280-fd94-11e9-80b4-f5c1e42fbcf5.png)

**Comment by Laicure** [comment]
> Will the option "Element selection mode" be added to highlight the unnecessary on the page and block as in the PC version. That is, you choose what to block yourself, because not all ads are deleted and sometimes you need to remove the interfering buttons and callouts on the page.
> I give an example below:
> ![68071464-11f88e80-fd94-11e9-8f14-8a45b6c40c04](https://user-images.githubusercontent.com/57290638/68071539-cdb9be00-fd94-11e9-8046-040c581d508f.png)
> ![68071472-23da3180-fd94-11e9-8338-1c1b1c05b1ea](https://user-images.githubusercontent.com/57290638/68071542-d14d4500-fd94-11e9-88e6-e62581e0d8da.png)
> ![68071480-381e2e80-fd94-11e9-95bb-7f667d28bc17](https://user-images.githubusercontent.com/57290638/68071543-d5796280-fd94-11e9-80b4-f5c1e42fbcf5.png)

That's **a lot** to ask, I think.
Domain/hosts blocking is sufficient.

**Comment by FirstDefolD** [comment]
> That's **a lot** to ask, I think.
> Domain/hosts blocking is sufficient.

And what's so, I used a browser with the ability to install extensions. You click on the extension and Adblock includes the "Element Selection Mode" and click on the unnecessary and it hides from the page.
![image](https://user-images.githubusercontent.com/57290638/68074097-f64fb100-fdb0-11e9-98fe-71e66056d57d.png)
![image](https://user-images.githubusercontent.com/57290638/68074102-fc459200-fdb0-11e9-92ab-9abdbeb5aa22.png)

**Comment by Laicure** [comment]
Is that _Kiwi_?
If that so, I've seen a lot of reported issues regarding extensions on that browser.
That would keep Bromite flooded with bug reports for extensions instead of the important ones.

Anyway, Bromite's main thing is privacy not extensions or customization.
It keeps things simplified and patched.

I would love to see those things in Bromite but nope, seeing it keeping simple means a lot.

**Comment by FirstDefolD** [comment]
> Is that _Kiwi_?
No, this is a Yandex browser. It has extension support. But he is too sophisticated and not very comfortable.

**Comment by Laicure** [comment]
> Is that _Kiwi_?
> No, this is a Yandex browser. It has extension support. But he is too sophisticated and not very comfortable.

Oh, I use Samsung Browser with the [Adguard Content Blocker](https://github.com/AdguardTeam/ContentBlocker) long ago.
That thing you pointed was discussed here: #198
It discusses about the ability of Samsung/Yandex to use app extensions such as [Adguard Content Blocker](https://github.com/AdguardTeam/ContentBlocker).

**Comment by FirstDefolD** [comment]
> В нем обсуждается возможность использования Samsung / Yandex расширений приложений, таких как [Adguard Content Blocker ](https://github.com/AdguardTeam/ContentBlocker).
But I want to be on the chrome shell, but with the ability to install extensions.

**Comment by dimqua** [comment]
> Bromite's main thing is privacy not extensions

There are a lot of extensions, that improve privacy. But proprietary browsers, like Kiwi and Yandex, are horrible for privacy.

**Comment by githubsucks-usegitlab** [comment]
> > When will there be an easy way to set our own filters?
> 
> This is an open source project, you are not entitled to ask "when", sorry.

Spare me the holier than thou nonsense mate. If people ask me on my own projects when/if I will ever implement something I'm at least polite enough to give them an answer. What's the point of working on his project if you aren't going to implement features that people actually need and that will give people an incentive to actually make use of your effort instead of a competing app?

Your argument is a fallacy through and through. Seriously, look at your reply again and in particular to the words:  "open source" and "entitled". Not only does your comment contain absolutely no logic what-so-ever, it's not only a waste of your own writing time but my and everyone else's reading time.

I don't care if you're not being paid to work on this project, all of us realise this isn't a charity but your reply is utter bs. How about the next commit you make is a change to your attitude. J@ck@ss.

**Comment by csagan5** [comment]
This feature is being tested and should be available on next release; I will also think of a way to help users generate the subresource filters file format that Chromium/Bromite need.

**Comment by csagan5** [comment]
Fixed in `78.0.3904.130`.

See also: https://www.bromite.org/custom-filters

**Comment by dimqua** [comment]
Well, its not an easy way. Not at all. :(

**Comment by sevospl** [comment]
I need the sources of `ruleset_converter`, so that I can compile it under FreeBSD. Possible by any chance?

**Comment by csagan5** [comment]
@sevospl in the [help page](https://www.bromite.org/custom-filters) linked in [previous comment](https://github.com/bromite/bromite/issues/2#issuecomment-563192451) there is a link to [Chromium documentation](https://github.com/chromium/chromium/blob/master/components/subresource_filter/FILTER_LIST_GENERATION.md). It explains how to compile the tools; the source is in the Chromium repository since that help page explains how to build and use them.

**Comment by sevospl** [comment]
> @sevospl in the [help page](https://www.bromite.org/custom-filters) linked in [previous comment](https://github.com/bromite/bromite/issues/2#issuecomment-563192451) there is a link to [Chromium documentation](https://github.com/chromium/chromium/blob/master/components/subresource_filter/FILTER_LIST_GENERATION.md). It explains how to compile the tools; the source is in the Chromium repository since that help page explains how to build and use them.

Hey! I've cloned the whole repo, however I'm not familiar with Ninja/GN at all -- altough I have no idea how to compile this specific tool. Could you help me more excatly, please?

**Comment by Ajaja** [comment]
**macchrome** has built ruleset_converter.exe for Windows:
https://github.com/macchrome/winchrome/issues
