### ISSUE TITLE
Google search sub categories ("All, Images, Video, News, etc") disappear

### ISSUE THREAD

**Issue by BJOkarma** [bromite/bromite#20]
Google search sub categories ("All, Images, Video, News, etc") disappear after a search is executed. Duration it momentarily shows: variable - until the webpage is fully loaded (e.g. slower connection shows it longer); sub categories then become cropped, link text no longer shows, some categories can be utilized by clicking in the tiny space above the link text.

Downloaded ARM64 version on 07DEC17
Bromite Settings show: Application Version - Bromite 65.0.3284.0
Operating System Android 8.0.0; Pixel 2 Build/OPD3.170816.023

**Comment by csagan5** [comment]
The application version you see from inside Bromite is incorrect, it shows the Canary version for reasons unknown to me. You can see the correct version from Sttings -> Apps. I opened a separate issue (#21) for that problem, but it's low prio.

Regarding the issue reported here: as explained on XDA forums it is due to the anti-AMP cleanup of hyperlinks. It should be possible to be more selective with the cleanup and fix this issue.

**Comment by csagan5** [comment]
Next release `63.0.3239.118` should have this fixed by my tests with it; please confirm after it has been released (~24 hours).

If you can test using the arm64 version, it is already available here: https://github.com/bromite/bromite/releases/tag/63.0.3239.118

**Comment by csagan5** [comment]
It is fixed in the upcoming `63.0.3239.122`
