### ISSUE TITLE
change default search engine to no search 

### ISSUE THREAD

**Issue by inorinet** [bromite/bromite#2100]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

upstream ungoogled chromium 

### Describe the solution you would like

change the default search engine to no search

### Describe alternatives you have considered

none

**Comment by csagan5** [comment]
> upstream ungoogled chromium

Upstream is Chromium; if this were implemented it would cause an endless stream of bug reports and complaints because the right way to do this would be to ask user to choose a search engine on start. Chromium even has such promo dialogs implemented for China but permanently disabled.

Implementing the dialog would be some major work and without any maintainer for that UI I cannot commit to this feature.
