### ISSUE TITLE
Timezone override random doesn't work

### ISSUE THREAD

**Issue by tankaras** [bromite/bromite#2133]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64

### Android version

12.1

### Device model

Xiaomi Mi 9 se

### Changed flags

N/a

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1

### Describe the bug

System timezone persists

### Steps to reproduce the bug

1. Go to https://browserleaks.com/javascript
2. Check section 'Internationalization API'

### Expected behavior

Randomized timezone info

**Comment by uazo** [comment]
actually now it behaves differently, rather than "per page" now it works "per site", which from a certain point of view is even better this way, apart from understanding what has changed in the chromium code.

@csagan5 what do you think? Isn't it better if the override is per site, so that the same site doesn't have the ability to track the user simply because it changes the timezone every requests? because in the end we are always at the same question: is it better to differentiate or disguise oneself in the crowd?
from what I have understood so far it is better not to be too different from the crowd, I seem to understand that algorithms look for what is easier to find. however, it always depends on which algorithms: that is, with those that create a hash based on values it is better to differentiate, with those who are looking for a logic between different navigations it is better to hide ...

**Comment by csagan5** [comment]
Where is the bug here? If nobody changes the timezone then the system one is used. The steps written by @tankaras do not mention that timezone was changed.

> from what I have understood so far it is better not to be too different from the crowd, I seem to understand that algorithms look for what is easier to find. however, it always depends on which algorithms: that is, with those that create a hash based on values it is better to differentiate, with those who are looking for a logic between different navigations it is better to hide ...

Yes it should work per site; it was working per page before in Bromite?

> in the end we are always at the same question: is it better to differentiate or disguise oneself in the crowd?

This is already decided in Bromite, see https://github.com/bromite/bromite/wiki/Fingerprinting

**Comment by uazo** [comment]
> Where is the bug here?

when I wrote the patch, the change of the random timezone is on each page/request, as also specified in the settings.
now instead the calculation of the random time zone is per site, ie every time the first party changes it is recalculated, no longer at each request.
I think it's because some optimization has taken place in chromium which makes site settings available once per first party.

> it was working per page before in Bromite?

yes.

> This is already decided in Bromite

i didn't know that page.

**Comment by tankaras** [comment]
Upon troubleshooting further. This bug is reproducible when you add a site exception to the timezone settings. I.e introducing a whitelist site corrupts the timezone randomization feature.

Let me know @csagan5 if you would like me to open a new issue.

**Comment by xxjoe2** [comment]
another suggestion about spoofing fingerprints

could you add an option to set the default accept-language header to en-us pls? coz in android we cant add extension to do this. also javascript can detect the system language correctly

thanks a lot

**Comment by csagan5** [comment]
> > Where is the bug here?
> 
> when I wrote the patch, the change of the random timezone is on each page/request, as also specified in the settings. now instead the calculation of the random time zone is per site, ie every time the first party changes it is recalculated, no longer at each request. I think it's because some optimization has taken place in chromium which makes site settings available once per first party.

@uazo I think it's better now, I will update the wiki page to explain how it works. Do we need to update the patch as well to mention this?

> Upon troubleshooting further. This bug is reproducible when you add a site exception to the timezone settings. I.e introducing a whitelist site corrupts the timezone randomization feature.

It is working per site instead of per page, this is actually an improvement. @tankaras you mean that without the site exception it changes for each page instead?

**Comment by tankaras** [comment]
@csagan5 Yes. This is the behavior I am getting.

**Comment by uazo** [comment]
> Where is the bug here?

there is also another bug.
basically the chain of exceptions entered by the user does not work: the bug is common for all content settings passed to the render (webgl, webrtc, timezone and autoplay).

you can try
- deactivate webgl (or another above) globally
- activate it for a site
- it is active on all sites

I have already fixed it, I am waiting for the next release to do the pull requests.

**Comment by csagan5** [comment]
> I have already fixed it, I am waiting for the next release to do the pull requests.

@uazo does this still need a patch?

**Comment by csagan5** [comment]
Fixed in `103.0.5060.126`.

**Comment by csagan5** [comment]
This was actually fixed in `103.0.5060.140` via #2207.
