### ISSUE TITLE
Bromite doesn't render any webpage

### ISSUE THREAD

**Issue by mrquyetdx** [bromite/bromite#214]
Bromite says it "Can't open this page"
Bromite version: 71...120
Android version: 7.1.2
System webview: by Google ver 71.0.3578.99 or by Bromite ver 71...120

**Comment by lowtrucks** [comment]
i can confirm that.

Bromite version: 71.0.3578.120.apk
Android version: 9.0
Phone: Samsung Galaxy S3 (i9300)

![screen_20190107_1350](https://user-images.githubusercontent.com/12945674/50758785-ffe9b480-1284-11e9-9e8e-9090225ea714.png)

**Comment by fitittome** [comment]
Ditto. LineageOS 16.0. arm.

**Comment by ouzowtf** [comment]
Have you tried if it works in Chromium?

**Comment by mrquyetdx** [comment]
Chromium, same version, also doesn't work.

**Comment by jrjordao** [comment]
Probably the same issue, although what I get is "Bromite has crashed". When trying to go to any page, including (Bromite's own) bookmarks and downloads.

Bromite version: 71...120
Android version: 6.0.1

**Comment by csagan5** [comment]
@mrquyetdx please re-submit it with the issue template. The issue template is visible when visiting the Desktop version of Github. You don't need to add screenshots but this is most probably a crash so the logcat of the crash is needed.

**Comment by lowtrucks** [comment]
**Bromite version**

Version: `71.0.3578.120
Arch: `arm`
Android version: 9.0 (LineageOS 16.0)

**Is the bug reproducible with latest version?**
yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
don't know.

**Describe the bug**
Bromite doesn't open **any** Web page. even local _about:blank_, which doesn't require internet connection.

**To Reproduce**
Steps to reproduce the behavior:
run Bromite with Web page.

**Expected behavior**
a browser opening any Web page.

**Screenshots**
![50758785-ffe9b480-1284-11e9-9e8e-9090225ea714](https://user-images.githubusercontent.com/12945674/50772853-f2e2ba80-12b0-11e9-8e78-ce56404a2f2d.png)

**Comment by lowtrucks** [comment]
should i re-open this issue as new. or is it enough?

**Comment by csagan5** [comment]
@lowtrucks the new one in #216  will do, less confusion by it being the first post
