### ISSUE TITLE
Installing Bromite SystemWebView as an user app (no root required in a specific environment)

### ISSUE THREAD

**Issue by moriel5** [bromite/bromite#220]
Device: Nexus 4
ROM: CRDroid
OS Version: 7.1.2

If Google's WebView (or, I'm guessing, any WebView provider other than the standard Android WebView) is default, and the standard Android WebView is not installed, it is possible to install Bromite WebView as a user app, and select it from the developer settings.

So far, no issues here (though I am running the .115 release, not .120).

**Comment by csagan5** [comment]
@moriel5 we should document this in the wiki. Is this made possible by the CRDroid ROM? Is it possible on AOSP or a stock ROM? I think not; there are limitations that CRDroid ROM might have lifted to make this possible.

As for the package name: see https://github.com/bromite/bromite/wiki/Installing-SystemWebView#about-the-package-name

**Comment by csagan5** [comment]
@moriel5 what is the documentation change that you suggest for [that wiki page](https://github.com/bromite/bromite/wiki/Installing-SystemWebView)? You can also do it yourself.

**Comment by moriel5** [comment]
I had never edited a GitHub Wiki, so I'd be honored.
I'll think of a way to properly phrase what I had already said, plus recheck what patch it is that allows installing additional WebView providers on Android 7 and up (most custom ROMs have it built in), as I had forgotten it's name.

**Comment by moriel5** [comment]
How about this?
Installation with root or TWRP
...

Alternatively, you can skip step 3, and just install Bromite WebView as a user app after rebooting, by setting the default WebView provider in Developer Settings to Bromite WebView (note, with this method you will not be able to use anything that requires WebView until you set Bromite WebView as the default WebView provider).

Installation without root
...

On ROMs where the AOSP WebView (`com.android.webview`) is not preinstalled, you can just install Bromite WebView as a user app, and set it as the default WebView provider from Developer Settings.

**Comment by csagan5** [comment]
> The reason this had worked, is because Android does not require a specific signature from the `com.android.webview`,

...unless a package is already installed, in that case it requires a package with same signature (and version code >= current version code) before allowing installation, or the removal of the package and then installation anew (but this is not possible for system packages without root).

> so if you have something else set as default (`com.google.android.webview`, `com.android.chrome`, etc.), and the stock AOSP WebView isn't installed, Android will function without any issues with Bromite WebView being installed as a user app, and once it is installed, the system will happily allow it to be set as default.

This is because Bromite SystemWebView uses AOSP SystemWebView package name (which is the default package name when building the SystemWebView in Chromium, `com.android.webview`); the reason this name was kept is to have maximum compatibility across ROMs (custom & stock, rooted/non-rooted); the advantage of having its own package name would be that with a custom ROM you can also have the AOSP SystemWebView available without the signature conflict.

> This should be correct for any ROM, even stock OEM ROMs.
> 
> Nevertheless, there should be no security issue from this (unless you count having WebView installed in /data but not in /system), since `com.android.webview` must not be already present for this to work, so the only ROMs that a user will not have to modify to get Bromite WebView installed, are ROMs where `com.android.webview` in not preinstalled.

@moriel5 so are you saying that:
* all stock OEM ROMs come without a hard-coded signature for `com.android.webview`?
* custom ROMs also do not set a hard-coded signature for `com.android.webview`?

If this is true then indeed the ROM locks on the first `com.android.webview` installed (permanently if it is preinstalled or installed as a system app, with possible removal if it is an user app instead). This information should additionally be used to clarify why the non-root Debloater approach works in the Bromite wiki page (the Debloater removes the pre-installed system app, thus allowing installation of any other chosen by the user).

Can you specify official sources for this (so everybody can verify as well)?

> This gets me thinking, there may be a flaw (not security, usability) in this system, since it limits the allowed webview providers to a select list (if it not already possible, you should be able to get Bromite (the browser) listed as a WebView provider by patching the ROM with this [patch](https://github.com/AOSPA/android_frameworks_base/commit/d36582165d4694da101cc65755af0841d443c80e) (there is an extra space there, which was removed with an incremental patch), provided courtesy of OpenGAPPS, after adding Bromite and it's signature to the patch.), rather than only just using the API, similar to how you can select the default phone, messaging, home launcher, browser, and assistant apps.

This mode of working (locked if installed, free otherwise) might be in place for easier integration by OEMs; the OEM might receive from the Android team a ROM without the webview and the install their own, and then finally release it to their users.

Bromite uses the default `com.android.webview` package name specifically to not have to ask all custom ROMs for inclusion of the package name and signature, and I would exclude that is a good idea going forward.

> Note: I still need to test this without Google's WebView installed in /system, something that I should hopefully test within the next 2 weeks (I still need to format my phone, and upgrade the OS version from 7.1.2 to 8.1).

You could try using Debloater to remove that from the ROM, but I think it will work (if `com.android.webview` is not pinned to a specific signature, as inquired before): the mechanism that prevents installing another APK with a different signature is simply the core signature verification present in Android (it has nothing to do specifically with the SystemWebView and it is enforced with all apps already installed).

**Comment by moriel5** [comment]
> ...unless a package is already installed...

That is true, I was merely speaking about the WebView whitelist, not about the Android Package Manager.

> @moriel5 so are you saying that:
* all stock OEM ROMs come without a hard-coded signature for `com.android.webview`?
* custom ROMs also do not set a hard-coded signature for `com.android.webview`?

If this is true then indeed the ROM locks on the first `com.android.webview` installed (permanently if it is preinstalled or installed as a system app, with possible removal if it is an user app instead). This information should additionally be used to clarify why the non-root Debloater approach works in the Bromite wiki page (the Debloater removes the pre-installed system app, thus allowing installation of any other chosen by the user).

From what I can tell and have seen, that is the situation (this does require testing on stock ROMs, though).

If you wish, I'll think of how to add this information to the Debloter section of the documentaion on Sunday (I won't be available from now until then.

>Can you specify official sources for this (so everybody can verify as well)?

The only source I have is OpenGAPPs patch, I had merely looked at it's changes from AOSP, and saw that `com.android.webview`, unlike the other WebView providers, did not have a line for the signature.

> This mode of working (locked if installed, free otherwise) might be in place for easier integration by OEMs; the OEM might receive from the Android team a ROM without the webview and the install their own, and then finally release it to their users.

That certainly makes sense

> Bromite uses the default `com.android.webview` package name specifically to not have to ask all custom ROMs for inclusion of the package name and signature, and I would exclude that is a good idea going forward.

I agree, I just thought that it would be a good idea to mention this.

> You could try using Debloater to remove that from the ROM...

No need, I am rooted (I do not use the Play Services, only a few of Google's app), and in any case I do not use Windows (my Linux distro of choice is Solus).

**Comment by bdashore3** [comment]
I cannot install Bromite WebView as a user/system app on Android 9 (latest security patch). It installs via package manager, but it doesn't show up in Developer Options

**Comment by csagan5** [comment]
> From what I can tell and have seen, that is the situation (this does require testing on stock ROMs, though).
> 
> If you wish, I'll think of how to add this information to the Debloater section of the documentaion on Sunday (I won't be available from now until then).

I am more concerned that we have not verified the information, so I would not add it there until that. I will modify the wiki to mention what we know already without extending it to stock ROMs (which can vary wildly by themselves); see if my changes have improved the page?

**Comment by moriel5** [comment]
Sorry for being late, I am looking at the possibility of repairing a "smart" TV that had stopped turning on (no clues so far, and I am disappointed that it does not have a separate power supply board, something that explains the soldered power cable), and had forgotten to open GitHub.

@bdashore3 you need to first remove or disable Google's WebView for this to work.
I had found, on android 5.1, 6.0, and 7.0, on the Nextbook Ares 10A, the Blackview BV6000s, and a few other chinese devices, all running stock ROMs that barely deviate from AOSP (I forget what device ran what version of Android, aside from the Blackview BV6000s, which was on Android 7.0), that disabling the AOSP WebView automatically enabled Google's WebView, and vice versa.

@csagan5 I agree with that reasoning, as I had only looked at stock ROMs that have next to no changes from AOSP.
The changes so far look great.

**Comment by csagan5** [comment]
@moriel5 I have added a new section that explains how to verify the viability of a (system) webview installation: https://github.com/bromite/bromite/wiki/Installing-SystemWebView#verifying-allowed-webview-packages

I think with this there is now more information for non-root users, root users and who wants to edit a ROM.
