### ISSUE TITLE
VirusTotal (Relations) Contacted IP Addresses

### ISSUE THREAD

**Issue by Slavatar2001** [bromite/bromite#2209]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

103

### Device architecture

arm64-v8a

### Android version

9

### Device model

Redmi 4 pro

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Since version 103 Bromite, VirusTotal sees in paragraph RELATIONS third party Contacted IP Addresses.
 Chromium version 103 there is no such problem.
 Bromite Version 102 does not have this problem either.

### Steps to reproduce the bug

VirusTotal

Bromite apk version 103
https://www.virustotal.com/gui/file/1364edd5c3acf1d1afa691b6fc361d023f2075766b8417a5e11d16f1f689c9a6/relations

Bromite apk version 102
https://www.virustotal.com/gui/file/54dd81e28b0eb74871affcba4c411e017d3f3c3d077f9ab093be0c5d0b5dd4ef/relations

### Expected behavior

Expected behavior how in Chromium 103, or Bromite 102.

### Screenshots

![Screenshot_20220721-002145_1](https://user-images.githubusercontent.com/101465569/180084886-c0b6142d-318f-47f0-aec0-adbbde8f805f.jpg)

**Comment by uazo** [comment]
from what I understand that section contains the addresses where that file is downloadable, it has nothing to do with what bromite does.
if you have more precise information, please write it down.

**Comment by Slavatar2001** [comment]
> from what I understand that section contains the addresses where that file is downloadable, it has nothing to do with what bromite does. if you have more precise information, please write it down.

![Screenshot_20220721-140828_Chrome_1](https://user-images.githubusercontent.com/101465569/180200033-8651bff4-9960-454f-849f-949e8d2da725.png)

VirusTotal shows that these IP associated with checks-gps and telephony. 
And what you wrote IP related to download Bromite, it looks like it's not.

**Comment by uazo** [comment]
> VirusTotal shows that these IP associated with checks-gps and telephony and obfuscated.

bromite does not communicate to any site other than github for updates and filters, in addition of course to dns.
those could be the home page favicons.
you can check for yourself via network tools, there are also simple ones, like PCAPdroid.
in any case thanks for the report, I will check with other tools.

**Comment by uazo** [comment]
@csagan5 actually, during the fre, with wireshark I found a packet to `mtalk.google.com`, I think generated by gcm.
I still haven't figured out where it starts from

**Comment by Slavatar2001** [comment]
> bromite does not communicate to any site other than github for updates and filters, in addition of course to dns. those could be the home page favicons. you can check for yourself via network tools, there are also simple ones, like PCAPdroid. in any case thanks for the report, I will check with other tools.

Ok, thanks for the reply.
I will only repeat that this problem is only Bromite any version 103(apk). Bromite versions 102 , there are no such problems(apk). Chromium versions 103 also no such problem(apk).

**Comment by Slavatar2001** [comment]
Perhaps in version 104 this problem will disappear on its own.

**Comment by uazo** [comment]
I did some additional checks.
- reprocessing v102 gives the [same results](https://www.virustotal.com/gui/file/54dd81e28b0eb74871affcba4c411e017d3f3c3d077f9ab093be0c5d0b5dd4ef/behavior/Zenbox%20android)
- testing with `netstat -atnp` the origin is not bromite
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program Name
tcp6       0      0 :::5037                 :::*                    LISTEN      12262/adbd
tcp6       0      0 ::ffff:10.215.173:43754 ::ffff:108.177.119:5228 ESTABLISHED 6869/com.google.android.gms.persistent
tcp6       0      0 ::ffff:10.0.2.16:33694  ::ffff:216.58.209.35:80 TIME_WAIT   -
```
- I tried removing `android.permission.INTERNET` from permissions:
https://www.virustotal.com/gui/file/c066aa268fb6da5d056f73e790f5a4f24254bc6c95bac234d42eb9c914b60abb/behavior
- I tried to put an infinite loop at the startup to verify and this is the result:
https://www.virustotal.com/gui/file/9b2d935fec873a04f2d11dd7a5e20af33c735a495aa2982be54720c28732af38/behavior
(the result is strange, because it show the tags but not connections)
- I tried removing the last leftover code related to the gcm driver in chromium:
https://www.virustotal.com/gui/file/dec39d2a50b7e171f1b0680068dc068ac30ecc82f5cdfd21c49c4d534c8818b9/behavior
- I have asked at VT support if the packets log are global to the system, this is the answer:
```
We include both system and application network traces
```
my conclusion is that they are logging also google play services activity on their sandbox machine.

**Comment by Slavatar2001** [comment]
> I did some additional checks.
> 
> * reprocessing v102 gives the [same results](https://www.virustotal.com/gui/file/54dd81e28b0eb74871affcba4c411e017d3f3c3d077f9ab093be0c5d0b5dd4ef/behavior/Zenbox%20android)
I looked at it, something was strange, at the first check Ip and was not at all in version 102, but in 103 they were immediately.
Well, there is still something strange in version 102 Bromite, chromium 103, only 9 ip maximum, while in version 103 Bromite ip already 39 pieces. Why did they increase so dramatically in version 103, from 9 to 39 ip?

Bromite 102 from your first link.
![Screenshot_20220723-123409_Chrome](https://user-images.githubusercontent.com/101465569/180599729-75b00088-b825-46fc-ab19-b604cbd5b00f.png)

Bromite 103 from my first link.
![Screenshot_20220723-123435_Chrome](https://user-images.githubusercontent.com/101465569/180599735-5d6325f3-2dfc-41df-85e6-a12c4c0f58e9.png)

> my conclusion is that they are logging also google play services activity on their sandbox machine.
Yes it is possible.

**Comment by uazo** [comment]
> Why did they increase so dramatically in version 103, from 9 to 39 ip?

I don't know, but I didn't worry considering that the vt doesn't seem to me the optimal tool for a point check.
currently this is what bromite requires at startup without always incognito:

```
07-23 13:19:49.558 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 103133150 https://cdn2.iconfinder.com/data/icons/minimalism/512/Chromium.png
07-23 13:19:49.560 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 103133150 https://www.chromium.org/_/rsrc/1484148948583/apple-touch-icon.png
07-23 13:19:49.564 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://cdn2.iconfinder.com/data/icons/minimalism/512/Chromium.png
07-23 13:19:49.565 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 103133150 https://developers.google.com/_static/9bce7b6017/images/touch-icon.png
07-23 13:19:49.565 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 103133150 https://freenode.net/static/img/logos/coloured-alphabg-sq-120.png
07-23 13:19:49.565 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 103133150 https://assets-cdn.github.com/pinned-octocat.svg
07-23 13:19:49.567 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://www.chromium.org/_/rsrc/1484148948583/apple-touch-icon.png
07-23 13:19:49.568 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://developers.google.com/_static/9bce7b6017/images/touch-icon.png
07-23 13:19:49.568 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://freenode.net/static/img/logos/coloured-alphabg-sq-120.png
07-23 13:19:49.569 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://assets-cdn.github.com/pinned-octocat.svg
07-23 13:19:50.182 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 45578882 https://github.com/bromite/bromite/releases/latest/download/x64_ChromePublic.apk
07-23 13:19:50.185 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 45578882 https://github.com/bromite/bromite/releases/latest/download/x64_ChromePublic.apk
07-23 13:19:50.188 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 45578882 https://github.com/bromite/bromite/releases/latest/download/x64_ChromePublic.apk
07-23 13:19:50.194 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 45578882 https://github.com/bromite/bromite/releases/latest/download/x64_ChromePublic.apk
07-23 13:19:51.495 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://www.gstatic.com/devrel-devsite/prod/vdb149cdc08c87ab249cdebfec6395e8f073056d752ca9c2d285d3b8426fcfa32/9bce7b6017/images/touch-icon.png
07-23 13:19:51.877 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 103133150 https://freenode.net/view/Main_Page
07-23 13:19:55.279 21949 21949 I chromium: [INFO:simple_url_loader.cc(1845)] ---SimpleURLLoader::Create 54845618 https://www.bromite.org/filters/filters.dat
07-23 13:19:55.282 21949 22024 I chromium: [INFO:url_request_http_job.cc(228)] ---URLRequestHttpJob::Create 54845618 https://www.bromite.org/filters/filters.dat
```
in addition of course to the dns calls. in always incognito mode no favicon is loaded at every restart

**Comment by Slavatar2001** [comment]
I see, thanks for the detailed explanation and for taking the time. Thank you.😉

**Comment by csagan5** [comment]
> @csagan5 actually, during the fre, with wireshark I found a packet to `mtalk.google.com`, I think generated by gcm.
> I still haven't figured out where it starts from

Did you figure this out? They originate from the Play Store?

> currently this is what bromite requires at startup without always incognito:

These are for the favicons.

In v103 I did some major cleanup of what is compiled (or not) in terms of C++ and Java classes/inclusions; did we find here anything new (or a regression) that needs to be blocked? It looks like not.

**Comment by uazo** [comment]
> Did you figure this out? They originate from the Play Store?

yes, in fact it is not bromite but `com.google.android.gms.persistent` as https://github.com/bromite/bromite/issues/2209#issuecomment-1192634882

the doubt I have is that it is requested through an IPC call with intents and `PackageManager`, I'm trying to figure out if I can intercept all the calls and block them in the bud.

in fact by doing a search for `getPackageManager` in the chromium code, you will see that it is used to check the packages installed on the device, including java side [gcm driver](https://source.chromium.org/chromium/chromium/src/+/main:components/gcm_driver/android/java/src/org/chromium/components/gcm_driver/GoogleCloudMessagingV2.java)
at first I thought that removing `android.permission.QUERY_ALL_PACKAGES` from the manifest would fix it, but system packages don't need that permission, so I should block it from code.
so the idea is to return a `PackageManager` shadow class by overriding `getPackageManager` in `SplitCompatApplication` (which is the `Context` of all chromium views) and, since it is tedious to rewrite all abstract methods, I think I will reuse code from  [BridgePackageManager](https://cs.android.com/android/platform/superproject/+/master:frameworks/layoutlib/bridge/src/com/android/layoutlib/bridge/android/BridgePackageManager.java).

> did we find here anything new (or a regression) that needs to be blocked? It looks like not.

I don't know if new or old, but theoretically there is also [this](https://source.chromium.org/chromium/chromium/src/+/main:components/gcm_driver/android/BUILD.gn) to remove (via [Remove-gcm-driver-java.patch](https://gist.github.com/uazo/cfda32614db2a3206b2e0b2e1c659234#file-remove-gcm-driver-java-patch)), but if I can do something more general (as I explained above) it is certainly better and less intrusive.
