### ISSUE TITLE
How to change SystemWebView without UI?

### ISSUE THREAD

**Issue by tristan-k** [bromite/bromite#236]
Is there a way change the SystemWebView without using the user interface. I'm running a rooted kindle hd 10 and there is no entry to set the SystemWebView in the developer options.

**Comment by csagan5** [comment]
@tristan-k there is an issue template to use which unfortunately - due to a Github limitation - does not show up if you use Github mobile.

Your question seems generic and not specific to Bromite so I suggest using a search engine or similar to get to the answer as here we deal only with Bromite issues or feature requests.
