### ISSUE TITLE
Bookmarks export not working

### ISSUE THREAD

**Issue by jackdroido** [bromite/bromite#248]
**Bromite version**

Version: 72.0.3626.99
Arch: arm64
Android version: Android 8.1.0 Oreo

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Describe the bug**
Bookmark export functionality does not work

**To Reproduce**
1. Go to 'Bookmarks'
2. Click on 'Export'
4. Bromite tries to open file:///storage/emulated/0/Download/bookmarks.html but fails (ERR_FILE_NOT_FOUND)

**Expected behavior**
Bromite should create/update the bookmarks export file correctly. Tried on a clean install with only https://duckduckgo.com as a bookmark
Same as issue #225 (closed because not following issue template)

**Comment by csagan5** [comment]
@jackdroido with a clean install, go to https://www.bromite.org and attempt downloading Bromite's APK (any other download would work). After authorizing Bromite, click cancel. This will make bookmarks export work.

Somebody would need to add similar code to the export functionality so that it asks for permissions also there, but there is currently a workaround (as described above).

**Comment by jackdroido** [comment]
@csagan5 It works ! Feel free to close the issue, but IMHO adding a line about the workaround in the wiki could be helpful. Thanks !

**Comment by ZeroPucks** [comment]
As far as I know, exporting bookmark for the first time will always cause that "ERR_FILE_NOT_FOUND" message to appear, but a bookmarks.html file will still be created in the Downloads folder. Exporting again when there is already a bookmarks.html file in the Downloads folder will then show a list of bookmarks in the tab, but it may show the old list instead of the current one. It's as if it is looking for a pre-existing file called "bookmarks.html", but it doesn't exist yet when exporting for the first time. It would explain why exporting a second time will show the old list and not the newest one.

Regardless, exporting and then importing the bookmarks.html file, or opening it in Bromite using a file manager app, will show the most recent list of bookmarks.

**Comment by csagan5** [comment]
> but it may show the old list instead of the current one.

this might be simply because the export gets created **after** the page is opened.

Closing for now as there is no patch or intent to patch.
