### ISSUE TITLE
Scroll freeze with Disqus

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#284]
**Bromite version**

Version: `74.0.3729.80`
Arch: `arm64`
Android version: 9

**Is the bug reproducible with latest version?**
Yes, did not occur in previous 

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Is the bug a crash?**
No

**Describe the bug**
Pages with Disqus freeze the scrolling when scrolling through the comments

**To Reproduce**
1. Open a site with Disqus comment section (e.g, an androidpolice.com article)
2. Scroll to comments
3. Scroll through comments
4. Eventually scrolling will freeze until a page reload

**Expected behavior**
Scrolling should not freeze.

**Screenshots**
N\A

**Comment by ouzowtf** [comment]
Can confirm with 74.0.3729.86
Works in Chromium with the same version number.

**Comment by csagan5** [comment]
Isn't this simply due to the adblocker?

**Comment by Madis0** [comment]
Disabling Bromite's adblock does not appear to fix it.

**Comment by csagan5** [comment]
I have investigated a bit, they use jRespond and plenty of other Javascript libraries so it's not an easy task to figure out how it hangs. What it does is that if you scroll up twice very fast it "forgets" to listen to any taps afterwards. That is probably because there are half a hundred libraries trying to analyse your user input and send it to their servers for analytics. If you scroll again from the remote debugger it seems to get unstuck.

Most surely this is a side effect of the anti-fingerprinting functionality plus bugs in the website/widget.

Closing because there are no plans to do anything in Bromite for this problem.
