### ISSUE TITLE
Using webview with magisk

### ISSUE THREAD

**Issue by alexa-v2** [bromite/bromite#291]
**Bromite version**

Version: 74.x
Arch: arm64
Android version: pie

**Is the bug reproducible with latest version?**
Latest from f-droid and website

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No
If yes then report it upstream on [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first; all Chromium issues reported here will be closed as `invalid`.

**To Reproduce**
1. Installed from f-droid normally
3. Use magisk debloat to remove normal webview and reboot
2. Use magisk app systemizer to put in /system_root/system/app
3. Reboot
4. Installed/updated app from official site apk
5. Bromite doesn't show up as option
Note: Putting it in /system/app manually doesn't persist after a reboot with magisk, probably due to it's systemless nature
**Expected behavior**
Bromite should be a webview option but only chrome is

**Screenshots**

**Comment by csagan5** [comment]
@alexa-v2 if the instructions on the wiki do not help, there is not much else I can do to help. Most (advanced) users manage to install it if their ROM allows it, otherwise it means you cannot (or you are not able to).

You can look for troubleshooting/support on XDA or Reddit, there is no difference between Bromite's Webview or Chromium's webview regarding installation.

**Comment by alexa-v2** [comment]
I'm using magisk. Surely someone has managed to do it
