### ISSUE TITLE
What to install?

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#32]
Not sure whether to install ChromeModernPublic ChromePublic MonochromePublic on my Androd 7 phone. Just a user so this is not obvious to me.

**Comment by sanjayen** [comment]
Would be great if the differences between the following 64 bit versions are explained on the GitHub releases page.

arm64_ChromeModernPublic.apk
arm64_ChromePublic.apk
arm64_MonochromePublic.apk
arm64_SystemWebView.apk

Keep up the good work. Thank you.

**Comment by sanjayen** [comment]
Found a closed bug #12 which provides links which mention the differences.

**Comment by csagan5** [comment]
Yes, please refer to https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets to know the differences.

From what I understood, ChromeModernPublic or MonochromePublic will do on any recent Android. Not sure what are the advantages of MonochromePublic (if any), maybe something because of the embedded SystemWebview. But I suspect they are technically the same, except that MonochromePublic can only be installed on latest versions of Android compared to ChromeModernPublic.

So I'd suggest going with ChromeModernPublic all the times (which is the default selected on the home page).
