### ISSUE TITLE
DNS-over-HTTPS (DoH) not working while on WiFi

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#336]
**Bromite version**

Version: `75.0.3770.139`
Arch: `x86`
Android version: `9.0 pie`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Is the bug a crash?**
No

**Describe the bug**
DoH seems to be working only while using mobile data connection. Switching to WiFi uses the default Android system DNSes.

This could be due to Android propagating the DNS settings to Chrome as a system network change.

**Comment by csagan5** [comment]
@thestinger if/when you get around to checking this functionality, help would be appreciated. Perhaps you can figure out why it is happening. My only hypothesis - as per description - is that the Android system network change overrides the DoH settings.

**Comment by thestinger** [comment]
Unfortunately, I don't know much about the Chromium DNS-over-HTTPS implementation or the other browser-level DNS functionality.

I won't be looking into it since DNS-over-TLS is available in GrapheneOS via AOSP, so I don't have the same use case of covering older versions without DNS encryption. It may make sense to support DNS-over-HTTPS as an alternative to DNS-over-TLS since it's a bit more resistant to filtering due to using port 443. Nothing prevents using DNS-over-TLS over port 443, but it wouldn't be compatible with DNS server deployments so that would be impractical and confusing. If DNS-over-HTTPS ends up being wanted for GrapheneOS, it would be as an OS level feature covering all applications rather than just the included browser though. I think it's unfortunate that there ended up being 2 deployed standards for encrypted DNS, in addition to the earlier DNSCrypt too.

**Comment by bakancs** [comment]
@thestinger You are right, in Chromium the system can override the user settings, only in Firefox it can't

**Comment by BUAWF** [comment]
Try Disabling "Async DNS Resolver" in about:flags. Personally I've disabled it & DoH I've opted for Cloudflare, it's working fine for Me on switching back & forth WiFi/Mobile Data. I'm on armv7, Android 7.1.2. Hope this may help for x86 too.

**Comment by csagan5** [comment]
Considering also issue #377 I understand that the solution here would be to always store the incoming Android-level proxy changes into a "default config" variable, and only use it if the proxy UI selector is on "default".

This would solve both problems at once.

**Comment by icejr** [comment]
DOH on WiFi is working on latest build `78.0.3904.119`

**Comment by csagan5** [comment]
> mind if I know what was the issue?
Previously DoH would be configured within Bromite when the app starts, now it is configured when the user sets it via settings.

@icejr I do not think the DoH issues are gone but merely need to be verified differently:
1. close Bromite while you are on 4G
2. start Bromite while you are on 4G (this guarantees a clean slate), make sure it is configured to use DoH and verify that it is using it with something like https://www.dnsleaktest.com/
3. now switch to WiFi and perform the test again

Can you please report what are your findings?

**Comment by icejr** [comment]
DOH is working on both 4G and WiFi... Checked using https://1.1.1.1/help

**Comment by csagan5** [comment]
@icejr thanks for checking!
