### ISSUE TITLE
Failed to connect to fdroid.bromite.org Repository via F-Droid Client

### ISSUE THREAD

**Issue by Qemics** [bromite/bromite#400]
**Bromite version**

Version: `78.0.3904.72`
Arch: `arm64` 
Android version: 10.0
Device model: Pixel 3a

I'm not able to download Bromite via F-Droid Client. While refreshing repository F-Droid outputs an error message: "Error getting F-Droid index file --> Failed to connect to fdroid.bromite.org/45.49.126.196:443. All other repos didn't create errors (F-Droid Core Rep works without any issues)" 

The apk file from bromite.org is not working as well. "There was a problem while parsing the package."

**Comment by sevospl** [comment]
I have the same issue. Fingerprint doesn't matter here. Looks like this server (45.49.126.196) is dead (no ping answer).

**Comment by lothrond** [comment]
Same here. I had to download/verify things manually, which still works.

**Comment by csagan5** [comment]
I had contacted the service provider to avoid a suspension due to too high traffic usage; I contacted them **before** the traffic threshold was reached, but nonetheless they let it go above it because of some mistake on their side. Long story short, the service is now restored but IPv6 was thrown out of the window, I hope we can restore that but no high expectations.

**Comment by Techguyprivate** [comment]
same.

**Comment by Techguyprivate** [comment]
> > same.
> 
> @Techguyprivate what do you mean with "same"? The issue has already been resolved.

Yes. Thank you. 

I had the same issue . I was just lazy and I had no time to  post and write the details so wrote same. 

Yes. It was resolve and not showing error now on refresh.
