### ISSUE TITLE
64.0.3282.204

### ISSUE THREAD

**Issue by lowtrucks** [bromite/bromite#43]
arm_ChromeModernPublic.apk can't be installed - it reports error, that app can't be installed.

also, apk version didn't change in 64.0.3282.204. it's still **64.0.3282.193**, and the build number is even lower - **1519522724**.

**Comment by csagan5** [comment]
Thanks for reporting; it is happening because previous build was from Beta channel instead of Stable, so it was higher. I will fix this by increasing the version code and re-releasing it.

As I mentioned on the forums, I do not understand how the apk version would still be the old one. Where did you see that?

**Comment by csagan5** [comment]
@lowtrucks I was asking whether you checked it on Android or in the APK metadata. I checked the metadata, I indeed verify it is incorrect there.

The error I believe is simply due to the fact that the version code is low.

**Comment by lowtrucks** [comment]
![screen_20180310_1429](https://user-images.githubusercontent.com/12945674/37240611-bbb6f060-246f-11e8-9cd9-5e0b1acdc4db.png)
![screen_20180310_1429_2](https://user-images.githubusercontent.com/12945674/37240613-bf33f8e6-246f-11e8-8f71-230f686431bb.png)

**Comment by csagan5** [comment]
The arm and arm64 builds have been fixed.

**Comment by lowtrucks** [comment]
@csagan5, thanks!
