### ISSUE TITLE
Do not remove Startpage

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#435]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

This repo

### Describe the solution you would like

While I cannot reproduce it being removed in the latest build, please don't remove Startpage as a search engine. There have been controversies over the new ownership, but they have answered some questions over it, so it is worth to reconsider: https://github.com/privacytoolsIO/privacytools.io/issues/1562

### Describe alternatives you have considered

Add the search engine from startpage.com manually

**Comment by csagan5** [comment]
> it is worth to reconsider: [privacytoolsIO/privacytools.io#1562](https://github.com/privacytoolsIO/privacytools.io/issues/1562)

I disagree; the bar is high for privacy and we have unfortunately lost another option.

It should disappear on next release and/or when data is erased.

**Comment by Bara-dev** [comment]
Could I ask to reconsider this decision?
Even if you still believe startpage has privacy issues, it still serves better results than ddg and is located in Europe. Also removing it for that reason, wouldnt it mean you should also remove Google?

(PS. Startpage has answered multiple questions on many reddit posts like https://www.reddit.com/r/privacytoolsIO/comments/dxx4y1/startpage_answers_more_questions_reveals_majority/ and they are always happy to answer any questions on twitter etc)

**Comment by gergesh** [comment]
I'd also appreciate if you reconsidered it. Considering Google, Bing and Yahoo are there I don't think there's an argument for leaving startpage out. This change is made even worse by the fact that it seems they do not support Open Search and are not added to the search providers list, which means to get startpage support one would have to rebuild the browser with the patch applied.

**Comment by csagan5** [comment]
@Bara-dev default search engines have been added to Bromite in the past only if they are better than the existing default selection in terms of privacy. No existing **default** search engine has been removed, and not even the default search engine is changed.

> they do not support Open Search

@gergesh any idea why this is the case? I suggests requesting that they add this feature, unless they have already denied it.

**Comment by Madis0** [comment]
PSA: [According to Startpage](https://www.reddit.com/r/StartpageSearch/comments/fcre75/different_base_engines/), they use Google results on desktop and Bing results on mobile, so "better results than DDG" are moot at this point 😞

**Comment by sorryusernameisalreadytaken** [comment]
I wrote startpage.com and ask them if they can support OpenSearch description format.
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

I will report you, when they reply. If :D

**Comment by sorryusernameisalreadytaken** [comment]
Good news 🚀 
Startpage.com does support OpenSearch spec!

Here is the reply from Alex from Startpage.com Support:
'''
Startpage already has support for the OpenSearch spec, you can find it here: https://www.startpage.com/sp/cdn/opensearch/en/opensearch.xml

You can add Startpage to Bromite by following these steps:

1) Navigate to https://www.startpage.com/do/settings
2) Change the HTTP request method from POST to GET
3) Save your settings
4) Enter any search query on our homepage

Startpage should now be displayed as a recently visited search engine in Bromite's search engine settings. Due to frequent inconsistencies with OpenSearch, you might have to try this multiple times before Startpage will be recognized as a search engine, but the steps are confirmed to work.

Please let us know if you have any questions.

Best regards,
Alex
Startpage.com
'''

I think this is agood solution for us all.
