### ISSUE TITLE
Restore the Images category to Site Settings

### ISSUE THREAD

**Issue by danhansen** [bromite/bromite#452]
### Is your feature request related to privacy?

While not overtly privacy-related, this feature request is to restore the ability to configure Image loading/blocking through the "Site Settings" menu. According to this commit:

https://chromium.googlesource.com/chromium/src.git/+/ff717a9063ca1acb955fef71b9366c9b9fe00e9c

The Images category was removed from the Site Settings, because it overlapped with the Data Saver feature. However, the Data Saver feature was removed from Bromite to satisfy issue #67, so this overlap no longer exists. I see no reason this feature cannot be restored, giving users more control over their browsing experience.

### Is there a patch available for this feature somewhere?

Not as such, but I imagine that a patch can be pretty easily worked out by undoing https://chromium.googlesource.com/chromium/src.git/+/ff717a9063ca1acb955fef71b9366c9b9fe00e9c

### Describe the solution you would like

Effectively, just a reversion of https://chromium.googlesource.com/chromium/src.git/+/ff717a9063ca1acb955fef71b9366c9b9fe00e9c

### Describe alternatives you have considered

In my mind this is more or less a question of reverting the change that removed Images from the Site Settings, or not. I don't really see any alternatives in the vein of this request.

**Comment by csagan5** [comment]
> a patch can be pretty easily worked out by undoing

@danhansen a revert does not currently apply, and even if it did then maintaining a patch like this across new versions can easily cost ~1h more for each release.

To offset the initial burden I ask for patches submission (it would take me easily a couple hours to make this revert apply), but the project also needs patch maintainers otherwise the functionality can go stale/broken (see #450 for example).
