### ISSUE TITLE
Twitter detects notifications as not supported

### ISSUE THREAD

**Issue by SinTan1729** [bromite/bromite#474]
### Bromite version

Version: `79.0.3945.139`
Arch: `arm64`
Android version: `10.0`
Device model: `Redmi K20`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?

No

### Describe the bug

Notifications are not working.

### Steps to reproduce the bug

1. Go to any website that supports notifications (e.g. `twitter.com`)
2. Try to turn on notifications
3. It shows browser is not supported

### Expected behavior

Notifications to be turned on.

**Comment by csagan5** [comment]
The notifications require Play services integrations which are not embedded in Bromite, there are in fact patches to remove all of them for privacy reasons.

Someone could investigate whether it's possible to have notification support without them, for example using microG or similar, but it goes unfortunately beyond the scope of this project.

If I am wrong about the integrations and the issue is due to some other reason then we need to reopen this and fix it.

A way to verify this would be building Bromite without the integration-removal patches.

**Comment by csagan5** [comment]
When testing with https://acme.com/webapis/notification.html I get notifications working.

Bigthink.com is another site where they do not appear to work.

How is twitter (mis)detecting the lack of support for this functionality which appears to be working in some cases? Perhaps there is a specific type of notifications which are not? 

I will reopen the issue so that hopefully someone can perform a better investigation and help figure it out.

**Comment by SinTan1729** [comment]
@csagan5 `facebook.com` doesn't work as well.

**Comment by Adrymate9** [comment]
I brought this problem some time ago.  It would be extremely important to be able to add push notifications.  From my place I can ensure that Twitter and Facebook do not work, neither does instagram.

**Comment by csagan5** [comment]
@SinTan1729 @Adrymate9 please test with the two websites reported in [this comment](https://github.com/bromite/bromite/issues/474#issuecomment-578629937) and report back your findings.

**Comment by SinTan1729** [comment]
@csagan5 For those two sites, my experience is the same as you i.e. acme.com works while bigthink.com does not.
As for Facebook, it does not enable notifications, neither does it report anything. The page simply reloads.

**Comment by Adrymate9** [comment]
test: for this website, the push notification actually arrives.   https://acme.com/webapis/notification.html

For Twitter when turning on the button to allow push notifications, return this poster: "Browser not supported
 It seems that your browser does not support push notifications".

For Facebook, just by logging in with the user account, give it a pop up warning if you want to receive the notifications, I give it a "allow" and then it just freezes.  I only have the option of going with the back button to continue browsing Facebook but they are notifications.

**Comment by randomshell** [comment]
@csagan5 the issue is not about Google integration and gcm because you're right, there are different types of notifications. My findings are the following.

Facebook notifications doesn't work because it uses gcm. Earlier I said it's not a problem because it is deprecated and will stop working in March. Source: https://bugs.chromium.org/p/chromium/issues/detail?id=979235

Twitter and bigthink use the `PushEvent` API and it is the one that doesn't work. Source: https://developer.mozilla.org/en-US/docs/Web/API/PushEvent . The specific error is at line 8 in the mozilla example and says `Uncaught SyntaxError: Unexpected token EVENT in JSON at position 0`.
I think to implement a similar app to get more specific informations if necessary. A guide can be https://developers.google.com/web/fundamentals/codelabs/push-notifications for anyone interested.

Acme uses `ServiceWorkerRegistration.showNotification` and is the only type of notification that works. Source: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by csagan5** [comment]
@randomshell thanks for looking into it.

The `PushEvent` API is implemented in Blink using GCM: https://github.com/chromium/chromium/blob/79.0.3945.139/chrome/browser/push_messaging/push_messaging_service_impl.cc

So this explains why it does not work for both Facebook and Twitter.

I am going to document in the README that the `PushEvent` API does not work.

**Comment by csagan5** [comment]
An alternative to allow this functionality would be to use https://github.com/microg/android_external_GmsLib

But it is not complete and maintained, so unlikely to ever happen.
