### ISSUE TITLE
Search results from Google that are YouTube videos won't open

### ISSUE THREAD

**Issue by Godecki** [bromite/bromite#478]
Edit: I now included the template. Sorry, I am new to GitHub.

### Bromite version

Version: '79.0.3945.139'
Arch: 'arm64'
Android version: '10'
Device model: 'OnePlus 7 Pro (GM1913)'

### Is this bug about the SystemWebView?

I don't know

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

When clicking the links or miniatures nothing happens. Even if I try to open it in a new tab or copy the link, the link seems to be just the Google search results, not the YT video link itself.

### Steps to reproduce the bug

1. Go to www.google.com
2. Type title of any video from YouTube
3. Click the miniature/link to the video
4. Nothing happens

### Expected behavior

Bromite should ask me wheather I would like to open the video in a specific app or in Bromite itself.

**Comment by HigH-HawK** [comment]
@Godecki is this a fresh installation of Bromite or just an update? Maybe try to clear the app`s data in the phone app settings. I had a similar issue and clearing the app cache fixed it for me.

**Comment by Godecki** [comment]
@HigH-HawK  It's not a fresh install, however I haven't noticed in which version it occured first. I tried clearing cache with no success. I'll try setting up Bromite again, as on my tablet running the same version there is no problem.

**Comment by HigH-HawK** [comment]
Yeah I did clear the app data and uninstalled the app afterwards and re inatalled it as well. It was working afterwards again. Not sure what is causing this though

**Comment by Godecki** [comment]
@HigH-HawK  I just reinstalled it, configured the same way as before and the problem surprisingly is gone. I should've perform reinstall in the first place on my own, but thanks anyway.

**Comment by Godecki** [comment]
@HigH-HawK  Shall I now close the issue, or leave it open for the dev or something? I am still new to GitHub community.

**Comment by HigH-HawK** [comment]
I guess you can close it, since your problem is resolved 👍🏼

**Comment by Godecki** [comment]
Fine, thank you very much!

**Comment by csagan5** [comment]
> Edit: I now included the template. Sorry, I am new to GitHub.

No problem, GitHub does not show the template on mobile and they do not commit to fix that issue, so it's not your fault if you tried to submit the issue from mobile.

@HigH-HawK I find it surprising that reinstalling works. However in this case I think it can happen if you have associated another app to open the videos. Reinstalling Bromite will clear the association too.

**Comment by HigH-HawK** [comment]
@csagan5 I kind of agree with the fact that it is surprising, that reinstalling Bromite works! I had the issue in #401 and could only fix it as described above. Before Bromite I was using Chrome which is the standard browser on HTC smartphones, so I was kind of surprised as it was working with Chrome but not with Bromite. I never associate any apps to open something, I usually use the option "Only once..." to leave the choice open for the next situation.

Nevertheless, clearing the app data / reinstalling Bromite fixed the problem for me at the time I had the issue and I never had it again :)

**Comment by csagan5** [comment]
@HigH-HawK in #401 you thought that something was left behind after uninstalling the app, but that is not possible, see [this comment](https://github.com/bromite/bromite/issues/401#issuecomment-549015976).

If the cause of the issue is not an external app association for videos then it might be something else that still needs to be figure out; the removal of association with other apps seems to be a sensible possibility.

In general when a video is played an intent is launched by Bromite and processed by Android; the only part to debug/troubleshoot here is about the intent launch, which can be done via logcat logs.

**Comment by HigH-HawK** [comment]
I indeed thought that something was left behind, since un- and reinstalling didn't fix it for me. Only after I cleared the app data before uninstalling the app, did fix it. I do believe you and I did read the link you posted in that comment. To be fair I was a little confused as to why my way fixed it in the end but wasn't giving any further thought, since it was fixed afterwards.

Unfortunately I can't reproduce it anymore, so the logcat logs wouldn't help right now. But I keep this in mind, if either this issue or another comes up again 👍 

Love Bromite by the way, finally a secure browser with AdBlock to block these presky adverts :) Great work
