### ISSUE TITLE
Clarification: x-client-data to google.com ?

### ISSUE THREAD

**Issue by casoncobi** [bromite/bromite#480]
Does Bromite send a unique client ID (x-client-data) to google properties (google.com etc) ?
This is considered a "backdoor" for Google (and google only!) to track users even without cookies.

If Bromite sends this header - can it be removed?
If Bromite doesn't send this header - maybe worth mentioning in the README in the feature list?

Description of this http header:
https://github.com/w3ctag/design-reviews/issues/467#issuecomment-581944600

**Comment by Kwinnieprince** [comment]
Hi @casoncobi I don't use bromite and the x-client-data is sent to google domains in the chrome browser. This has to do with google and not with bromite.
There is more information in this whitepaper from google: https://www.google.com/chrome/privacy/whitepaper.html#variations

**Comment by casoncobi** [comment]
The logic to append this "X-Client-Data" header in Chromium source:

```
const char kClientDataHeader[] = "X-Client-Data";
<snip>

 bool AppendHeaderIfNeeded(const GURL& url, InIncognito incognito) {
    // Note the criteria for attaching client experiment headers:
    // 1. We only transmit to Google owned domains which can evaluate
    // experiments.
    //    1a. These include hosts which have a standard postfix such as:
    //         *.doubleclick.net or *.googlesyndication.com or
    //         exactly www.googleadservices.com or
    //         international TLD domains *.google.<TLD> or *.youtube.<TLD>.
<snip>

    resource_request_->cors_exempt_headers.SetHeaderIfMissing(
        kClientDataHeader, variations_header_);

```

Here:
https://github.com/chromium/chromium/blob/ccd149af47315e4c6f2fc45d55be1b271f39062c/components/variations/net/variations_http_headers.cc

Maybe in other places too, "X-Client-Data" appears several files in the source code.

**Comment by huwdp** [comment]
Google has a pretty good idea of who their users are with x-client-data and other identifiable information such as IP addresses. Very scary

**Comment by csagan5** [comment]
Bromite has been using [this ungoogled-chromium patch](https://github.com/bromite/bromite/blob/79.0.3945.139/build/patches/ungoogled-chromium-Disable-Google-host-detection.patch) since `v64.0.3282.168` (introduced on [Feb 15, 2018](https://github.com/bromite/bromite/commit/71b5dc1b0bd8943d71e0777905a6f4ee9090f525)); this patch avoids detecting any specific domain as Google's own ones and thus sending any special header.

This was added back as a good measure (code looks fishy) and to prevent account ID headers in case user is logged in to some service, but I was not aware that non-logged-in users also have a tracking ID (although I am not surprised, and at some point I figured out that something like this was happening in another scenario, for GCM).

**Comment by casoncobi** [comment]
@csagan5 thank you so much for fighting for our privacy, you're a hero!

I tested x-client-data on a regular Windows Chrome install - it's about 200 bit random value, and sent every time you open a new tab. Nice GUID you have here Google. Nice. /s

I'd sleep better at night if this line didn't exist at all:
  `headers.SetHeaderIfMissing(kClientDataHeader, ...)`
Who knowns when/if Google will change the rules in `AppendHeaderIfNeeded()`...

**Comment by csagan5** [comment]
> you're a hero!

Not so much; I started this project because I needed a "decluttered" mobile browser for myself, but you're welcome to use it as anybody else.

> I'd sleep better at night if this line didn't exist at all:
> `headers.SetHeaderIfMissing(kClientDataHeader, ...)`
> Who knowns when/if Google will change the rules in `AppendHeaderIfNeeded()`...

A patch can be arranged, but you should not be surprised about this specific instance; there are unfortunately many more similar cases. If you look at Bromite's patches, about half of them has a similar story behind.

There is also some users which sometimes "patrol" the requests/responses, see for example #471 for something similar.
