### ISSUE TITLE
Bromite does not upgrade via F-Droid

### ISSUE THREAD

**Issue by angelog0** [bromite/bromite#499]
I see that last version of Bromite   is ` 80.0.3987.118` but F-Droid still says **All applications are updated** and insists to show `80.0.3987.95` as _Suggested_ 

What am I missing? Thanks

**Comment by angelog0** [comment]
Each time one flags an issue, real or potential, you close the discussion. 

What kind of `issue-template` should I add? Open F-Droid app, tap on Updates, **All apps are updated** is the answer, In F-Droid tap on `Settings - Handle your apps - Bromite 80.0.3987.95 (Suggested)`. Tap on `repo - bromite`, the url and fringerprint is what you report in your site. What else should I have added?

Your behavior is very very unfriendly. I am afraid.

**Comment by csagan5** [comment]
@angelog0 verified issues which are planned to be fixed are open; verified issues which cannot or are not planned to be fixed are documented, the rest are closed because incomplete or not verified.

You need to submit issues from GitHub in desktop mode and to fill in the template; the issue you are experiencing is not with Bromite, you should look into F-Droid Client usage documentation.
