### ISSUE TITLE
Automatic download

### ISSUE THREAD

**Issue by periw** [bromite/bromite#519]
### Bromite version

Version: `81.0.4044.83`
Arch: `arm64`
Android version: (`9.0`)
Device model: (`SM-G960F`)

### Is this bug about the SystemWebView?
I dont think so

### Is the bug reproducible with latest version? 
Yes

### Can the bug be reproduced with corresponding Chromium version?
Idk

### Is the bug a crash? 
No

### Describe the bug
Bromite dosent ask permission for automatic downloads in websites(spam downloads) and it starts the download.
I even set the setting to block, but it dosent work at all.
I have tried with chrome too and it asked and blocked downloads.

### Steps to reproduce the bug

You can see this with websites spreading spam apk downloads

### Expected behavior

It should ask my permission for automatic downloading.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Idk

As explained in the issue template:
> Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

**Comment by csagan5** [comment]
Fixed in `81.0.4044.97`.
