### ISSUE TITLE
Why is no one building Bromite or an equivalent for linux?

### ISSUE THREAD

**Issue by famewolf** [bromite/bromite#537]
I love bromite on my android device but then when I'm on my laptop I'm back to having to use brave.  Why is no one building the same for linux and other os's?   We get privacy on our phones but not on our laptops and desktops?

**Comment by Madis0** [comment]
https://github.com/Eloston/ungoogled-chromium#downloads

However, I see that project as quite unsustainable unfortunately (the binaries are infrequently released), so I would say Brave is the best bet.

**Comment by randomshell** [comment]
> I'm back to having to use brave

> Why is no one building the same for linux and other os's?

What is wrong with brave? It has secure defaults related to privacy settings.

After some research you can have this and more with Firefox with extensions and ghacks-user.js. But these aren't defaults and require you to understand what each settings does.

As @Madis0 suggested there is Iridium too that has secure defaults but also doesn't have proprietary code, so DRM will not work, an example is Netflix. I am not sure if they handle security patches in time in comparison with Brave or Firefox.

**Comment by famewolf** [comment]
My understanding is brave still has it's OWN analytics compiled in that report back to brave.  Additionally anytime I can have an open source solution over a closed source one I'll prefer the open source one.

**Comment by varbhat** [comment]
@csagan5 Is it sustainable for you to release version of Bromite for Desktop?

**Comment by bokov** [comment]
> What is wrong with brave? It has secure defaults related to privacy settings.

Brave (and every other browser I could find for Android except Bromite) has no direct bookmark export. Since Brave's sync is also broken (yes, even in the latest version) that amounts to Brave keeping your bookmarks hostage on your phone. I'd rather import/export manually with Bromite than not even be able to do that with Brave.

Desktop import/export is pretty simple. The big problems are caused by Android's restrictive security model and clumsily organized file-system.
