### ISSUE TITLE
Enable/Disable screenshots in incognito

### ISSUE THREAD

**Issue by ShontelleBlackwood** [bromite/bromite#551]
### Is your feature request related to privacy?

Yes as without screenshot functionality using the privacy-related permanent incognito mode is limited.

### Is there a patch available for this feature somewhere?

Not sure sorry.

### Describe the solution you would like

I would like to be able to take screenshots while in incognito mode. Chrome by default prevents this however I believe it would make permanent incognito mode more desirable for more users. Perhaps there could be a toggle to enable/disable screenshots in incognito mode.

### Describe alternatives you have considered

I have to switch to different browser to take screenshots is the only alternative I have at the moment (Firefox Preview has screenshot in incognito toggle).

**Comment by csagan5** [comment]
Screenshots in incognito are disabled since v65 due to https://chromium-review.googlesource.com/c/chromium/src/+/809508

That is because if screenshots are allowed then the tab preview can be seen in the Android tab manager.

I will see if it's possible to add a flag and enable this for next version.

**Comment by Poopooracoocoo** [comment]
i think kiwi has a patch for this?

**Comment by csagan5** [comment]
No idea, I have already created a patch for it.

**Comment by csagan5** [comment]
Fixed in `83.0.4103.46`.
