### ISSUE TITLE
WebRTC policy in custom tabs

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [bromite/bromite#553]
### Bromite version

Version: `81.0.4044.127`
Arch: `arm64`
Android version: (example: `10.0`)

### Describe the bug

I disabled all WebRTC plugins of bromite. WebRTC leak is prevented when I test it using website like -----> https://browserleaks.com/webrtc

But if I use other apps that can open the same link like using telegram to open https://browserleaks.com/webrtc using bromite then I see WebRTC Leak is detected !

[Note] : Bromite is currently my defaut browser

![image](https://user-images.githubusercontent.com/32685696/81479315-b7e4f400-9222-11ea-8a92-32423b266a32.png)

**Comment by csagan5** [comment]
Please provide screenshots of the leak.

**Comment by BL4CKH47H4CK3R** [comment]
Through its my privacy issue I am providing you :)

![New Bitmap Image](https://user-images.githubusercontent.com/54761717/81467370-06ca6380-91fa-11ea-8b70-e9e0e5a368b4.jpg)

**Comment by BL4CKH47H4CK3R** [comment]
I tried disabling WebRTC features using `about://config` nothing works

**Comment by csagan5** [comment]
@BL4CKH47H4CK3R you can always amend the sensitive details in the image before posting it.

> I tried disabling WebRTC features using `chrome://flags` nothing works

They are already disabled by default in Bromite, see https://github.com/bromite/bromite/blob/81.0.4044.127/build/patches/Disable-WebRTC-by-default.patch

> Thats why I never liked chromium based browsers it always has WebRTC leak issues

Nothing is proven so far. The page from the app is opened as a custom tab intent which looks like has different permissions, it needs investigation. You would need to show the local IP address leak without using [custom tab intents](https://developers.google.com/web/android/custom-tabs/implementation-guide).

**Comment by csagan5** [comment]
`disable_non_proxied_udp` has been used since version `69.0.3497.73` (v68 was the last version with the possibility of disabling the build of webRTC) however I can observe:
* it does not leak local/public IP addresses in the webRTC offer when opening a web page in a regular tab
* it shows local and public IP when connecting from a custom tab. If you are on a VPN it will however show only the VPN public IP, thus no leak is happening.

When navigating Bromite regular tabs we have in logs:
```
WebRTC routing preferences: policy: 3, multiple_routes: 0, nonproxied_udp: 0, min_udp_port: 0, max_udp_port: 0, allow_mdns_obfuscation: 1
```

When using the custom tab intent instead: 
```
WebRTC routing preferences: policy: 0, multiple_routes: 1, nonproxied_udp: 1, min_udp_port: 0, max_udp_port: 0, allow_mdns_obfuscation: 1
```

This is because the custom tabs appear to use a different set of preferences; @uazo are you aware of how custom tabs work in terms of preferences?

I will check other preferences we set for other potential issues related to CCTs.

I will patch Bromite for next release to change the default policy enforced flags. @Eloston you might find this interesting as well, the patch is available here: #555

**Comment by csagan5** [comment]
@BL4CKH47H4CK3R to reply to your original concern: there is no leak, you can verify yourself that when using a VPN only the public VPN IP address is visible.

However the setting was supposed to be enforced on an even stricter level (no IP addresses at all) as investigated&explained in previous comment.

**Comment by BL4CKH47H4CK3R** [comment]
The IP I provided was my VPN IP, The private and public IP was VPN IP don't worry. But as I discovered this issue I informed you ! Because if the VPN sells your data then it will be dangerous. Most of the VPN do this without informing through they claimed to be the best
Greetings, BL4CKH47H4CK3R

**Comment by csagan5** [comment]
> The IP I provided was my VPN IP, The private and public IP was VPN IP

Yes, but that does not constitute a leak.



> the VPN sells your data then it will be dangerous.

The attacker is not the VPN, you already trust it. Attackers are possible websites that want to track you; they could only see your local IP address, there is no other information leak.

**Comment by BL4CKH47H4CK3R** [comment]
I got another issue `chrome://version` is not matching with https://chromium.woolyss.com/ its decting as a older version like 67.x

**Comment by csagan5** [comment]
> I got another issue

Then please submit a separate issue and give context on how to reproduce it on that issue.

> not matching with https://chromium.woolyss.com/

That is not the Bromite official website.

**Comment by csagan5** [comment]
Discussion contiues in #589
