### ISSUE TITLE
Add option to keep local data until browser exit

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#56]
The option reads on the desktop version "Keep local data only until you quit your browser" and it is currently not possible to change it on Android.

This would allow Bromite and its SystemWebview to change the behaviour introduced by [this patch](https://github.com/bromite/bromite/blob/49ae827/patches/BRM006_prefs-only-keep-cookies-until-exit.patch).

The introduced behaviour is problematic because at first install the setting is being set through that patch, and then it is no more possible to change it.

**Comment by csagan5** [comment]
Other thoughts:

1. why does an app loose the logged-in status in SystemWebview? (see [this post](https://forum.xda-developers.com/showpost.php?p=76429429&postcount=717))
2. how would one configure this option for the Webview?

**Comment by abhinav96** [comment]
(I'm the same guy from [this post](https://forum.xda-developers.com/showpost.php?p=76429429&postcount=717))
Some more details:
With Bromite's WebView Quora was asking me to login again after killing it. So I restored my system's WebView, tested Quora (works as intended), and then I installed Bromite's WebView again. Now Quora does not ask me login again even though I'm using Bromite's WebView ¯\\\_(ツ)_/¯

**Comment by abhinav96** [comment]
I did some more tests.
There was one more app which uses WebView and required login (and wasn't remembering them).
I restored my system's WebView and logged into the app, installed Bromite's WebView and the app is working fine.
Updated Bromite's WebView, rebooted the device, uninstalled and installed the apps. The logins still persist.

I am not sure what the issue was which made multiple apps forget logins, however restoring the original WebView and installing Bromite's WebView again seems to have fixed it.
(maybe it was not related to WebView at all?)

If nobody else can reproduce the issue, we can close this for now.

**Comment by csagan5** [comment]
@abhinav96 what you found out is in line with the problem that one cannot change the settings for the Bromite WebView, so when you install the system Webview and then put over Bromite's, you get Bromite WebView + the settings of the system WebView. Those settings have the "Keep local data only until you quit your browser" set to false, in opposition to Bromite's default of true.

So even if we implement this option in the UI, it will still not be possible to access it from the Webview since it has no UI to change the settings...

**Comment by csagan5** [comment]
Fixed in 68.0.3440.126
