### ISSUE TITLE
request for restore the old button

### ISSUE THREAD

**Issue by atuolol** [bromite/bromite#562]
Hi,

since v79.0.3945.107 you have decided to "remove global ads and javascript menu options"

is it possible to restore that function again?

thanks

**Comment by LukeOwlclaw** [comment]
@csagan5 I can understand that you want to keep the issue list short. That is a good thing. But where is the place for a discussion about this feature (or better said "the removal thereof")?

You yourself added that feature with in 2018 due to this issue https://github.com/bromite/bromite/issues/37
It was an awesome feature. To me it THE feature to use bromite. 
Now it was silently removed. Why?

**Comment by LukeOwlclaw** [comment]
Just found this:

I am not going to change Bromite back to have a global toggle for ads/javascript; related: #133

_Originally posted by @csagan5 in https://github.com/bromite/bromite/issues/466#issuecomment-574038933_

Sorry to hear. Still do not understand the reasoning.

**Comment by csagan5** [comment]
> But where is the place for a discussion about this feature (or better said "the removal thereof")?

There is no official discussion place, on purpose, because I would not have the time for it. You can try Reddit or XDA where other users might reply and help.

> Now it was silently removed.

It was not "silently" removed. All changes are documented in the [CHANGELOG](https://github.com/bromite/bromite/blob/master/CHANGELOG.md).

> Sorry to hear. Still do not understand the reasoning.

The issue you linked mentions both the old and the new way to toggle Javascript.
