### ISSUE TITLE
Block private networks scanning (gateway attacks)

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#590]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

There is some work going on upstream, see https://bugs.chromium.org/p/chromium/issues/detail?id=378566

### Describe the solution you would like

Gateway attacks should be blocked also for WebSocket requests. They are currently blocked only for background requests, see https://github.com/chromium/chromium/blob/83.0.4103.53/third_party/blink/renderer/modules/background_fetch/background_fetch_manager.cc#L251

See also: https://news.ycombinator.com/item?id=23253184

**Comment by csagan5** [comment]
@thestinger also relevant for Vanadium, see the related HN comment and discussion; although I believe the public outcry will speed up an upstream fix soon.

**Comment by csagan5** [comment]
Fixed in `84.0.4147.106`.

**Comment by orazioedoardo** [comment]
Since this update, I can't connect to my [Home Assistant](https://www.home-assistant.io/) instance anymore. Using the remote debugging I got the following error:
```
Uncaught (in promise) DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.
```

I think it's related to this change since I connect to the web interface using an internal domain which resolves to a private address. Is there a way around?

**Comment by kcdipesh** [comment]
I am also getting this issue 
DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.

**Comment by csagan5** [comment]
@orazioedoardo @kcdipesh it is working as intended; allowing access to those addresses is not allowed in Bromite because some websites scan your private network when it is allowed.

**Comment by kcdipesh** [comment]
In my case,I am using mqtt js which is using trying to connect to a server using websocket and I'm using this under a web worker

**Comment by danielehrhardt** [comment]
> In my case,I am using mqtt js which is using trying to connect

How did you solved it. I am getting the same Message:
`DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.`

**Comment by JobNoorman** [comment]
This seems to have broken [lichobile](https://github.com/veloce/lichobile). However, the WebSocket request that is disallowed is one to `socket.lichess.org`, which doesn't resolve to a local or private IP address. See [this issue](https://github.com/veloce/lichobile/issues/1599) for more details.

The request is made by a web worker that is loaded from a script on localhost. However, as far as I can tell, the origin of the request shouldn't matter since the destination is a public IP.

Could this be a Bromite bug? If not, any advice about how to further debug this problem would be appreciated.

**Comment by csagan5** [comment]
> However, as far as I can tell, the origin of the request shouldn't matter since the destination is a public IP.

The [patch in Bromite](https://github.com/bromite/bromite/blob/90.0.4430.101/build/patches/Block-gateway-attacks-via-websockets.patch) has three checks:
1. forbid a request to reserved IP addresses
2. forbid a request to local IP addresses
3. forbid `requestor_space > target_space`

The last one is calculated based on the enum values defined here: https://github.com/chromium/chromium/blob/90.0.4430.101/services/network/public/mojom/ip_address_space.mojom

The enum values correspond to 0,1,2,3.
If the requestor is local it will allow private and public.

By looking at this logic I wonder if the issue is not instead about a `local` -> `local` connection.

@JobNoorman for further troubleshooting I suggest you inspect network traffic on Chromium and try to figure out exactly what goes thru on Chromium and not in Bromite; then open an issue with that detailed information.

**Comment by JobNoorman** [comment]
Thanks @csagan5 

I opened #1129 for this but it got closed for not following the template even though I triple-checked and it seems correct :sweat_smile:

**Comment by danielehrhardt** [comment]
Could some please open the Issue #1129.

**Comment by csagan5** [comment]
@danielehrhardt no, it will not be re-opened, because it must be reproducible with the browser - not with the system webview.

I already provided steps to find out whether there is a bug or not:
> @JobNoorman for further troubleshooting I suggest you inspect network traffic on Chromium and try to figure out exactly what goes thru on Chromium and not in Bromite; then open an issue with that detailed information.
