### ISSUE TITLE
Option to block all 3rd-party connections

### ISSUE THREAD

**Issue by oksjd** [bromite/bromite#625]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Not any that I'm aware of.

### Describe the solution you would like
Add an option for indiscriminately block all 3rd-party requests and connections. Currently I can set JavaScript, cookies and a few others to "blocked" and add local exceptions when necessary.

With this option, one can browse most text-orientated websites without trouble and preserve privacy.

![Screenshot_Bromite_20200622-210530](https://user-images.githubusercontent.com/54463160/85291003-72eee700-b489-11ea-9c95-889b53aceca6.png)
Adding a local exception to allow JavaScript on Wikipedia.

![Screenshot_IceCatMobile_20200622-210246](https://user-images.githubusercontent.com/54463160/85291093-9023b580-b489-11ea-8be9-44b0c28265f0.png)
Blocking 3rd-party requests using uMatrix on IcecatMobile (available on F-Droid)
### Describe alternatives you have considered
Use IcecatMobile with uMatrix. (not very viable since Firefox on Android doesn't integrate well with Android native features, such as context menu, selecting text by dragging, etc.)

**Comment by csagan5** [comment]
It could be an interesting feature to have, but there are not many users that will want to use the web like this. Your use-case is: "access only resources under the domain in the URL".

Chromium does not have a pre-existing functionality like this which we could leverage; the subresources filter could be hacked to do this.

Since this will benefit few users and I am not going to work on the development of this feature, there is little benefit to keep this issue open; @oksjd can you contribute a patch for this feature?

**Comment by oksjd** [comment]
Unfortunately I don't know how to implement this feature either.

I think I'll stick with IceCatMobile+uMatrix for the time being, some websites just load too many garbage when viewing them.
