### ISSUE TITLE
[Question not a bug] Webview android 10 name

### ISSUE THREAD

**Issue by aelisya** [bromite/bromite#627]
hello, 
i have a question, i'm on no-root, so i have uninstalled webview with ADB, and killed it (even reboot the phone).
but the bromite webview don't appear in the dev zone, i think it's because it's name changed from com.android.webview to com.google.android.webview.

IT's only my phone who have this problem or it's a regular bug on android 10 ?
i ask because webview is the last soft who force me to rest to play store (one of the fdroid app use webview i can't just disable it).

nb: i don't want to root, because root = twrp = loosing encryption and unlock oem = security risk (since no security update anymore)

Thanks if someone have an idea to let it work.

**Comment by 00101010ASCII** [comment]
@csagan5 
@aelisya @nikolowry @lucianlau @Madis0 
@SebiderSushi

I have Motorola One Power phone,
NOROOT-Locked Bootloader.
No chrome installed.
Only com.google.android.webview preinstalled which i have uninstalled using
adb shell pm uninstall --user 0 com.google.android.webview 
>Success

**Problem- Bromite installed but not shown up in dev.settings**

> framework-res.apk res/xml/config_webview_packages.xml

 **Gives this output i.e. only one webview that too without signature**
> E: webviewproviders (line=17)
>   E: webviewprovider (line=19)
>     A: availableByDefault=(type 0x12)0xffffffff
>     A: description="Android WebView" (Raw: "Android WebView")
>     A: packageName="com.android.webview" (Raw: "com.android.webview")


adb shell dumpsys webviewupdate
**Gives this Output** **Bromite is already installed but not shown up in dev.settings**
> Current WebView Update Service state
>   Fallback logic enabled: false
>   Multiprocess enabled: true
>   Current WebView package (name, version): (com.google.android.webview, 77.0.3865.92)
>   Minimum targetSdkVersion: 29
>   Minimum WebView version code: 386509238
>   Number of relros started: 2
>   Number of relros finished: 2
>   WebView package dirty: false
>   Any WebView package installed: true
>   Preferred WebView package (name, version): (com.google.android.webview, 77.0.3865.92)
>   WebView packages:
>     Valid package com.google.android.webview (versionName: 77.0.3865.92, versionCode: 386509238, targetSdkVersion: 29) is  installed/enabled for all users
>     com.google.android.webview.beta is NOT installed.
>     com.google.android.webview.dev is NOT installed.
>     com.google.android.webview.canary is NOT installed.
>     com.google.android.webview.debug is NOT installed.
>     Invalid package com.android.webview (versionName: 83.0.4103.119, versionCode: 1592784620, targetSdkVersion: 29), reason: Incorrect signature


it is showing incorrect signature for bromite and not for other webview like com.google.android.webview even though it is not defined in framework-res.apk

**Comment by SebiderSushi** [comment]
@aelisya 
@00101010ASCII 

Any veritable android OEM will almost definitely ship `user` builds in production. `user` is an android build type and it makes sure that all available security features are enforced. This is the build type that is intended for end users.

As a result, any webview provider which is not pinned down to a certain signature must be installed as a system app. That way it is guaranteed that a webview only gets enabled if it was built by a trusted party which owns the whitelisted signing key or by someone who can install system apps (because someone in that position can effectively break all security measures anyway).

In effect, you will either need to change the whitelist so that it whitelists the Bromite WebView along with its signature or make the Bromite WebView a system app. In both cases you'll need to change the contents of your system partition in any way.

If system updates are your only concern but unlocking the bootloader itself is okay to you, you might take a look at [Magisk](https://github.com/topjohnwu/Magisk). Magisk allows you to change the contents of the system without tampering with the actual physical system partition on your device. You will still need to unlock your device bootloader so be aware of all that this implies in general and also for your specific device, including the probable loss of [SafetyNet](https://www.xda-developers.com/safetynet-hardware-attestation-hide-root-magisk/) (which i gues you won't notice as you are likely not using Google Play Services anyway).

**Comment by aelisya** [comment]
@SebiderSushi My problem in unlocking the bootloader is first, the loose of the "security on boot", and second de monthly 
 security update of my build (and i have seen many android build without update or nightly extremely unstable one and don't have security update is a very VERY big concern of mine).

During the time where security update are done by the constructor i don't realy have any intention of broking the security on boot, "just" for having root + bromite webview.

Is why i search to have an alternative who doesn't broke the system (i hoped adb will help but it seem's not).
I hope one day we will have a smartphone who do security update and all security and let us have root, but i think it's a dream.
