### ISSUE TITLE
GMS libs still inside(GCM and the like)

### ISSUE THREAD

**Issue by thermatk** [bromite/bromite#65]
Hi!
While leaving everything else might be OK, after all you know that you're using Google's Chromium and that the prebuilts can be theoretically compiled from source, there are still Play Services libs in blob form with a proprietary license inside Bromite. While you apply proven desktop patches, this one has to be completely new, because no one tried to compile a truly open source Chromium before.

**Comment by csagan5** [comment]
The binary contains non-free components, I agree. However I am not planning to work on this for now as compiling Chromium/Bromite completely from scratch would be a goal in #4; I do not know if it is possible to rip all the licensed blobs and not use any binary for the compilation.

**Comment by thermatk** [comment]
this is only partially connected, I don't understand why you closed it
by this issue I mean the binary blobs inside the apk, distributed with a separate license(the one you accept during runhooks) and providing proprietary features. The prebuilts, which are used to build chromium, are a shady topic, but supposedly every single one of them can actually be reproduced from sources.
A very rough patch is here https://gist.github.com/thermatk/b127cf46a62fb929ab7766f0ac6dbcb2

**Comment by thermatk** [comment]
Thing is, if you disable VR by `enable_vr=false` in gn args it will already be halfway done

**Comment by csagan5** [comment]
@thermatk `enable_vr=false` has already been there for a few releases now. I closed it because I do not see what work could be done to remove the binary blobs inside the apk? :confused: 
Yes, I see the difference with the prebuilts; my previous comment was confusing, what I mean is: I do not see how we could easily build Chromium without those licensed blobs, as I expect the build to fail here and there in many places without those integrations.

Also: do you know what functionality would disappear without these licensed blobs (Play Store etc)? I suspect nothing too important for Bromite.

I am re-opening, I am not against the idea, just evaluating if it is feasible (if you have experience on this, then better!) at all and/or not too much of a drain in terms of development/maintenance.

(If we are talking about the ethical aspect, and not practical, then I agree 100% and there is no doubt that all binary blobs should go out of the window, the Debian way)

**Comment by csagan5** [comment]
I think removing the blobs would make location functionality not work anymore; I do not care much personally as I think it's yet another way to undermine privacy, but I am sure users of Bromite might want that.

Another general problem:
* as it stands currently the code is already bypassing most GCM integrations; shouldn't also proprietary codecs be removed if one wants to get rid of all non-free blocks in the binary?

That's why I had closed the issue originally: there is little benefit (only disadvantages) and does not allow to make the binary a 100% FOSS product.

Your patch is interesting though, one could double-check that all those points in the code are currently not active (except where desired) for the embedded blobs.

**Comment by thermatk** [comment]
Codecs: they are not really proprietary in terms of code mostly, only patents. Europe doesn't recognize a lot of them, so it's ok.
Location: yes, this may be the only thing truly missing. It's potentially possible to integrate the system framework back.

While I'm slowly moving through to compile the native part, here is a patch to pass gn gen for canary:
https://github.com/Chromium-FOSS/hq/blob/master/patches/Exclude-GMS-and-pass-gen.patch . Most of it can be reduced to "remove all $google_play_services_package occurrences".

My previous patch was for the Android Studio version with precompiled libchrome, so I also had to shim native calls with empty classes. This certainly won't be needed

**Comment by csagan5** [comment]
> It's potentially possible to integrate the system framework back.
That would be interesting. Maybe visiting some old Chromium codebase predating GMS introduction.

Is Chromium-FOSS some sort of project? I am interested because I am pretty sure that once Bromite (or Chromium) would be buildable on F-Droid build system (#4), then the next step would be addressing what you are doing now.

Have you checked how other distros build Chromium? I inspected Debian/Ubuntu patches some time ago, you might find some work already done there.

I am all in favor of this (after all, what kind of open source project is Chromium if it cannot be built without proprietary blobs?), in fact I had to give this idea up quickly when I realised the blockers/complications (or broken features, as mentioned before) of building Chromium in a truly FOSS way.

Regarding Bromite: I am looking forward to see the patches you come up with. You might also want to give a look to the Bromite patches as most of them are about disabling these integrations with cloud services and similar.

**Comment by thermatk** [comment]
It's a shell for my attempt to get Chromium truly FOSS. My view on the plan is reverse. As you proved, it's theoretically possible to build on F-Droid, but it's not even possible to ask for any exceptions in terms of prebuilts, because there are blobs inside. 

If I manage to get blobs out, next step is to find an architecture to make the source libs approach work better. For now I'm just checking out sources and package them into a tar.xz with this script: https://github.com/Chromium-FOSS/hq/blob/master/scripts/packagesources.sh . Have to do it like that, because at home it's not even possible to finish fetch without fail :cry:
Your previous idea with converting all deps into sourcelibs won't work anymore, I think, because of the strange non-git CIPD dependencies. My proposal would be to split the fully checked out snapshot into not-so-enormous parts(like third_party as a separate folder and so on) and upload to separate repos on github, which then would be checked out as srclibs by fdroid.

**Comment by csagan5** [comment]
> As you proved, it's theoretically possible to build on F-Droid

I did not come up to the end of it to see a completed build but I could see the ninja build starting; it would probably have worked if not for the other issues.

> ask for any exceptions in terms of prebuilts, because there are proprietary blobs inside.

Yes I suspect the F-Droid guys would request this right after. Rightly so, except that I am a bit surprised about other submissions present there:
* https://f-droid.org/en/packages/com.dosse.chromiumautoupdater/
* https://f-droid.org/en/packages/com.anddevw.getchromium/
* https://f-droid.org/en/packages/chromiumupdater.bamless.com.chromiumsweupdater/

(I never thought of adding an installer like that to F-Droid because it feels really like cheating to me: an open source installer that fetches a binary blob built somewhere...)

> Your previous idea with converting all deps into sourcelibs won't work anymore, I think, because of the strange non-git CIPD dependencies. 

I just noticed [your comment there](https://gitlab.com/fdroid/fdroiddata/merge_requests/2854#note_77859382), sorry for missing that out. Were not the CIPD dependencies already there back then? I had to come up with a way to convert the `gclient` deps to the F-Droid build deps. Useless to say, it would be some work to make this maintainable..

I see you want to do some experiments, please let me know how that goes. May I suggest that you make a submission to build Chromium-FOSS via the F-Droid build system? As you can clearly see that would bump into the same issues I had, and probably with a different approach you might have success.

For now I am closing this as there is no plan or course of action to remove the GMS libs in Bromite (as a general rule I keep only actionable issues open); feel free to comment (I receive them via email) for more discussion. I also discuss at [XDA forums](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258) although the level there varies greatly (from newbie to technical sometimes).

**Comment by csagan5** [comment]
The patches developed for this effort are available here: https://gitlab.com/thermatk/Unobtainium/
