### ISSUE TITLE
GoogleEN search not using google.co.uk

### ISSUE THREAD

**Issue by AndhikaWB** [bromite/bromite#66]
Everytime I tried using "GoogleEN", Bromite will always use google.com instead of google.co.uk. Yes, it was in English, but it makes no different compared to original "Google" search. And please, rename it to "Google UK" instead of "GoogleEN"

**Comment by csagan5** [comment]
When I added that search engine I was under the impression that using `google.co.uk` would serve results in (UK) English by default. That however has been changed in recent years, and now it does not matter which domain you reach - the specific language must be asked via `hl=en` querystring parameter (this is what the GoogleEN has been doing).

My conclusion is that there is no benefit to use a specific domain (rather a disadvantage based on your distance to UK servers), so I will change the keyword to not be `google.co.uk` since it is misleading and it has never used that base domain anyway, but rather the default `{google:baseURL}` which is `google.com` as you observed or the geo-located one.

**Comment by AndhikaWB** [comment]
EDIT: I have looked at the patch file and realize that 'google.co.uk' is just a cosmetic because it will use 'Google:BaseURL'.

My only problem is that Google will always use 'google.com' instead of the localized domain, even when not using 'GoogleEN' (using Google). Is this privacy feature or bug?

Tested on Chrome latest version and Google search will use google.co.id (my country domain). Even when location is turned off.

**Comment by AndhikaWB** [comment]
Yes, I have looked at the patch file and realized that google.co.uk is just a cosmetic. However, using Google (not GoogleEN) will also show Google in English. Is it a privacy feature or a bug?

Tested latest Chrome version and Google search will use my country language (and domain), even when location is turned off.

**Comment by csagan5** [comment]
If you are in UK or US or another English-speaking country, then you will likely see it always in English. It depends from your phone settings and/or country IP address (my guess).

The GoogleEN search engine is for those cases where you want to always see results in English, regardless of your Android OS language (you can try changing that to test this) and/or country IP address.

**Comment by AndhikaWB** [comment]
Thanks for the explanation. I'm not aware that Android language will also affect Google.

My only little complain is:
Please consider renaming 'GoogleEN' to 'Google English' or something else. I'm a perfectionist and this makes me feel a little uncomfortable when seeing it.

**Comment by csagan5** [comment]
Yes, I will rename it to `Google in English` in next release; this search engine additionally removes Google-specific querystring parameters from searches

**Comment by csagan5** [comment]
Fixed in 67.0.3396.88
