### ISSUE TITLE
Canvas randomization gives the same value after < 10 page refreshes

### ISSUE THREAD

**Issue by Slaviro** [bromite/bromite#69]
I was testing the canvas fingerprinting randomization using browserleaks.com on Google Pixel and found that I get the same Signature value with your patch in about 5-6 page refreshes. I should add that I was building only SystemWebView myself. On Oneplus 5T with latest Bromite (ChromePublic.apk) I got the same Signature 3 times in a row. Is it OK?

**Comment by csagan5** [comment]
I've noticed this, however I do not know what to make out of it. My current theory is that the number is always random, however sometimes the change is too small, thus nothing gets changed. Need to investigate further.

**Comment by Slaviro** [comment]
I tried to play around with your algorithm, for example, I couldn't find out why you count the number of pixels to change like (w +h) / 128. I tried to make something like "change 2% of all pixels", use rand() instead of chromium's random generator and multiply shuffleR(G, B) by random value from 0.01 to 0.2. The situation became a little better - number of refreshes slightly increased, sometimes I saw visible noise on the picture, thus far I'm still getting equal values sometimes. At least, not in a row. It looks for me like there's some caching or something else that bypasses the randomization. I came to this conclusion because a clean Chromium gives the same value for me. 
I don't believe randomization gives nothing for 132 pixels (2% of 220x30 pixels).

**Comment by csagan5** [comment]
> I couldn't find out why you count the number of pixels to change like (w +h) / 128.

This is to reduce the amount of pixels "touched" by the process. Changing only a few pixels is enough to spoil fingerprinting, so 2% would amount to more than what I select there.

> a clean Chromium gives the same value for me.

In this case it could be that `rand() * 0.03` gives 0 for all 3 RGB values, it's frequently possible because we are multiplying by a `0-255` RGB component and sometimes the component overflows (imagine it's already white). Having a change of 0 for all components has still to be accepted...what I would change there is the 3% to something higher.

> I think it could be a good idea to modify every pixel's RGB value by the same random value from -1 to 1

If you mean every pixel of the image, then I think it's a bad idea. It would be slow. If you mean every selected pixel, then using `-1..1` would make it visible. In my implementation I was trying to make it not visible with a small change.

My suggestion is to make the tests individually, if you change all those aspects together you are not understanding why something happens.

I think that the shuffle amount for each component is changing within a too small range, I will make some changes to that aspect. Do you want to test it? I have added the additional patch here: https://github.com/bromite/bromite/blob/master/wip/Tune-canvas-randomisation.patch

**Comment by Slaviro** [comment]
I tried your new patch and it looks like the situation became worth. 4 times the same value in a row. Do you have any ideas how to pass the values to logcat so I could see what exactly happens?

**Comment by Slaviro** [comment]
I made some changes to your work. Please, have a look.

[Upd-Further-investingations-on-canvas-randomization.txt](https://github.com/bromite/bromite/files/2110961/Upd-Further-investingations-on-canvas-randomization.txt)

For me, it gives 100% random value on Pixel without any visible effects for the image. Feel free to modify it.

**Comment by Slaviro** [comment]
I made some changes to your work. Please, have a look. For me it gives 100% random without visible effects. 
[Upd-Further-investingations-on-canvas-randomization.txt](https://github.com/bromite/bromite/files/2110986/Upd-Further-investingations-on-canvas-randomization.txt)

**Comment by csagan5** [comment]
@Slaviro thanks for your patch and description, now I understand what you meant...you aim at changing the components by -1/+1 in most cases. I have adapted this idea of yours and now I also see that every time the canvas hash is different. I am going to include this in the next release and I would like to credit you in the commit message as `Slaviro (https://github.com/Slaviro)`, would that work for you?

You can see my changes in the updated patch here: https://github.com/bromite/bromite/blob/master/wip/Tune-canvas-randomisation.patch

I changed the way the maximum is being checked because the way you were doing it would not work for non-8bit color modes.

> P.S. I wonder if we can make something similar for WebGL...

It should be possible..although I wouldn't know where to start. In OpenGL there is a way to update a small rect of a texture, so hopefully the same should be possible for WebGL.

**Comment by Slaviro** [comment]
Yes, you can mention me like that if you want. I'm glad you improved my patch, thank you. I'll also test it later.

**Comment by csagan5** [comment]
Fixed in 67.0.3396.92
