### ISSUE TITLE
Disable history in normal mode

### ISSUE THREAD

**Issue by mihaiburlacu** [bromite/bromite#695]
### Is your feature request related to privacy?

Yes, browsing history definitely pertains to privacy.

### Is there a patch available for this feature somewhere?

Unsure.

### Describe the solution you would like

Option to disable history in normal tabs (just as there is an option to enable history in incognito tabs), or option to clear history / browsing data on exit.

### Describe alternatives you have considered

No real alternatives but to manually delete browsing data periodically. 

Incognito-always has several disadvantages:
- screenshots not allowed
- websites know when browsing is done incognito (e.g. newyorker.com, nytimes.com enforce paywall only in incognito tabs)

**Comment by csagan5** [comment]
> option to clear history / browsing data on exit.

It is already possible to clear cookies on exit or to use always-incognito mode.



> * screenshots not allowed

Screenshots are not allowed because otherwise other apps can take them as well. Bromite has a flag to toggle this.

**Comment by spinoza-dat** [comment]
@csagan5 there's an extra problem with incognito tabs: you cannot create a shortcut from an incognito tab.
Still, as stated above:
> Websites know when browsing is done incognito (e.g. newyorker.com, nytimes.com enforce paywall only in incognito tabs)

I already requested this feature for different reasons, I had to opt for always incognito and it's very, very uncomfortable for these issues. Please just consider adding a simple toggle to disable history, since there is a toggle even to enable history on incognito mode. Thanks for the attention

**Comment by spinoza-dat** [comment]
@csagan5 also there are no suggestions in incognito mode. Incognito mode cannot be considered a complete browsing experience for everyday usage

**Comment by csagan5** [comment]
> Please just consider adding a simple toggle to disable history

It may be "simple" from your perspective, but no change in the browser functionality is simple to implement.

> Incognito mode cannot be considered a complete browsing experience for everyday usage

Yet, if it is the best we have, that's what we have to use.

**Comment by spinoza-dat** [comment]
@csagan5 
> It may be "simple" from your perspective, but no change in the browser functionality is simple to implement.

Just as a question, not a provocation, is it so much more complicated than enabling history in incognito?

**Comment by csagan5** [comment]
> is it so much more complicated than enabling history in incognito?

It has to be changed in all places in the code where the profile is used, then tested. 

@uazo what do you think about this?

**Comment by uazo** [comment]
> what do you think about this?

I think it can be done... but, another flag?

just out of curiosity, why disable the history if it is only in your phone? that is, I can understand if it was synchronized with the cloud, but in bromite synchronization is disabled.

> nytimes.com enforce paywall only in incognito tabs

can you send a link for testing?

> Incognito mode cannot be considered a complete browsing experience for everyday usage

maybe there is something I don't know.
incognito is the same as normal navigation except that cookies, local storage, web sql and everything that can be used to track you are not kept. only history was missing, and now it can be kept.

> No real alternatives but to manually delete browsing data periodically.

sure, clean everything when the tab is closed ... sooner or later I'll do.
or option to clear history / browsing data on exit, as said here https://github.com/bromite/bromite/issues/530#issuecomment-617394818

**Comment by csagan5** [comment]
> I think it can be done... but, another flag?

A proliferation of flags can lead to user confusion or - equally bad - if users don't know about it they will never discover and use them.

> sure, clean everything when the tab is closed ... sooner or later I'll do.
> or option to clear history / browsing data on exit, as said here [#530 (comment)](https://github.com/bromite/bromite/issues/530#issuecomment-617394818)

A reminder that before developing these we need to agree that they are wanted features: if we make the settings confusing/conflicting we might end up with too many flags or inconsistent features.

**Comment by spinoza-dat** [comment]
> A reminder that before developing these we need to agree that they are wanted features

Well every other browser but jQuarks on F-Droid and IzzyOnDroid _does_ have this feature: Fennec, FOSS, Lightning, DuckDuckGo, Klar SmartCookieWeb, Privacy Browser... So it must be a frequently requested feature

**Comment by csagan5** [comment]
@spinoza-dat as explained in the feature request template features will not be added because they are requested by a lot of users or because another browser has them; if you like another browser, use it. Features are added if they are in line with the project goals (and if somebody makes a patch for them).

With "wanted" there I mean wanted for this project; there is plenty of features wanted by the users which unfortunately cannot be developed here for Bromite.

Two features have been recently added (enable history in incognito mode, delete cookies on session close) and here we have a new related feature request; we will not just add all features to tick boxes off a list, we need to see if they make sense first.

**Comment by mihaiburlacu** [comment]
> can you send a link for testing?
Any article on the New Yorker website will do, example [here](https://www.newyorker.com/books/under-review/has-self-awareness-gone-too-far-in-fiction) - _To continue using a private window, sign it or subscribe._ (not sure if this still goes for nytimes.com at the moment, but it's happened before)

> A proliferation of flags can lead to user confusion 
> we will not just add all features to tick boxes off a list, we need to see if they make sense first.
Fully agreed. You may have noticed this issue was opened right after support for enabling history in incognito mode was introduced. I simply fail to understand how this option makes sense for any browser, let alone for a privacy-oriented browser, when most requests (#224 #321 #530 #611 etc.) are towards having more control over normal browsing mode, without having to resort to incognito for all of the already mentioned inconveniences.

**Comment by csagan5** [comment]
> I simply fail to understand how this option makes sense for any browser, let alone for a privacy-oriented browser, when there's a clear demand (#224 #321 #530 #611 etc.) for having more control over normal browsing mode, instead of having to resort to incognito, for all of the already mentioned inconveniences.

Once again: "clear demand" does not justify adding a certain feature to a browser. As I wrote in [this comment](https://github.com/bromite/bromite/issues/321#issuecomment-502962874) there are privacy concerns when not using incognito mode because of the history: through some techniques it was/is possible for websites to know what sites you have visited.

Now imagine that Bromite had a feature to clear all data on exit, like asked in #611 (and like @uazo would like to add to continue the work done on #142): all users will start using it, ignoring the privacy problems related to **not** using incognito mode: incognito mode is much stricter than a "memory-less" normal browsing mode.

Once that happens you might have some happier users but you are just enabling the misuse of a browser with a combination of settings which give them a false sense of privacy.

This is why we need to think before adding such features, regardless of how many users ask for a certain feature.

**Comment by mihaiburlacu** [comment]
> Once that happens you might have some happier users but you are just enabling the misuse of a browser with a combination of settings which give them a false sense of privacy.

Ok, I now understand your point of view and actually fully agree with it.

> incognito mode is much stricter than a "memory-less" normal browsing mode

Then perhaps I was barking at the wrong tree with this, when a more suitable direction would be to make incognito mode more user-friendly. Sure, for some this might mean having the option to enable history, for others support for screenshots and adding to home screen would be welcome, and the incognito-based paywalls I mentioned can actually be bypassed by disabling JavaScript on those websites.

I guess I have nothing else to add to this then.

**Comment by uazo** [comment]
> Any article on the New Yorker website will do, example here - To continue using a private window, sign in or subscribe. (not sure if this still goes for nytimes.com at the moment, but it's happened before)

thank you so much.
however, it seems that by activating the incognito history that site is no longer able to detect incognito mode. 
could you confirm it too?
I would like to understand how he does it because it might be important to tell googlers via https://bugs.chromium.org/p/chromium/issues/list?q=component%3APrivacy%3EIncognito&sort=pri

> incognito mode is much stricter than a "memory-less" normal browsing mode

pure curiosity, what do you deduce it from?
from what I have seen in the code, incognito mode is related to the profile class with the difference that (in android) it has not set the destination folder on disk for the profile itself. I personally haven't seen anything else (look for profile-> IsRegularProfile() and IsOffTheRecord()). I found all other different are at ui level.

> A proliferation of flags can lead to user confusion or - equally bad - if users don't know about it they will never discover and use them

there is already
https://source.chromium.org/chromium/chromium/src/+/master:components/history/core/common/pref_names.cc

**Comment by mihaiburlacu** [comment]
> however, it seems that by activating the incognito history that site is no longer able to detect incognito mode.
could you confirm it too?

No actually, after activating incognito history (and making sure JavaScript is enabled) the site is still able to detect incognito mode.

**Comment by csagan5** [comment]
> Then perhaps I was barking at the wrong tree with this, when a more suitable direction would be to make incognito mode more user-friendly. Sure, for some this might mean having the option to enable history, for others support for screenshots and adding to home screen would be welcome, and the incognito-based paywalls I mentioned can actually be bypassed by disabling JavaScript on those websites.
> 
> I guess I have nothing else to add to this then.

On the contrary, the conversation should continue - and I am here to learn as much as (if not more than) everybody else. However I think it would be best that the conversation is about browser/privacy engineering and the unsolved questions.

> for others support for screenshots

This has been added many versions ago, see changelog.



> > incognito mode is much stricter than a "memory-less" normal browsing mode
> 
> pure curiosity, what do you deduce it from?
> from what I have seen in the code, incognito mode is related to the profile class with the difference that (in android) it has not set the destination folder on disk for the profile itself. I personally haven't seen anything else (look for profile-> IsRegularProfile() and IsOffTheRecord()). I found all other different are at ui level.

Mostly from updating the always-incognito patch, where I noticed the different interaction of the browser with activities and with integrations: for example tap -> web search would normally not be allowed in incognito because OEM integrations can intercept your search this way, I found this while making this patch: https://github.com/bromite/bromite/blob/84.0.4147.90/build/patches/Disable-smart-selection-by-default.patch (if you open those files you can find the comments that explain this "hole").

I currently expect that there are more of these behaviors which make incognito stricter; it would take a bit more research to figure out if I am mistaken or not (maybe they are not so many and not so important).

> > A proliferation of flags can lead to user confusion or - equally bad - if users don't know about it they will never discover and use them
> 
> there is already
> https://source.chromium.org/chromium/chromium/src/+/master:components/history/core/common/pref_names.cc

Never heard about this one; do you know how `history.saving_disabled` works? Is it something we could expose through settings if we agree that it makes sense to have it?

**Comment by MariojGG** [comment]
I think is better the implementation of firefox on this, clear history,cookies,cache... on exit.

**Comment by csagan5** [comment]
@uazo ok, thanks for confirming that. Have you seen the part about incognito != normal mode without "memory"? My example was referring to this: https://github.com/chromium/chromium/commit/48d4ae54f7565c429bf29cd63806aee5d7e93e69 and to the activities behaviors.

**Comment by uazo** [comment]
> about incognito != normal mode without "memory"?

https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/omnibox/suggestions/editurl/EditUrlSuggestionProcessor.java;l=87

just seen

**Comment by csagan5** [comment]
@uazo yes I saw that while porting the patches from v84 to v85, it looks like it's part of a new feature they are working on.

**Comment by alek3y** [comment]
### We just want it :I
@csagan5 
> Features are added if they are in line with the project goals

Well, the goal is "enhanced privacy" right? So it's definitely a project goal. Honestly it makes more sense to have this option rather than enabling history on incognito mode which was created to not store it. And if a lot of browsers have this options it means people want it, and thus shouldn't be ignored even if you don't understand the use of it. I do understand how it might become redundant tho, having the always on incognito but as I said this feature makes more sense than the others. Also, it makes no sense whatsoever to not add features if people want them (unless they go against the project goal), because if a feature no one uses is added then Bromite is going to become bloated. \
People would like to have a browser that works well without workarounds (like always incognito, which is still something that a lot of people might use tho) and might also want this to keep cookies and local storage while removing the history.

> As I wrote in [this comment](https://github.com/bromite/bromite/issues/321#issuecomment-502962874) there are privacy concerns when not using incognito mode because of the history

Then why do you allow browsing in normal mode at all? If it's a problem that occurs on normal mode too it has to be fixed regardless of this feature, it's not an excuse. And if this is a Chromium problem, a bug should probably be filed.

### Workaround
Since I don't expect the devs to actually add this feature I found a workaround (that for now works well) for **rooted phones** (sorry for you unrooted guys, but maybe it's time to root?). On Termux:
```bash
pkg install -y tsu e2fsprogs
tsu
cd /data/data/org.bromite.bromite/app_chrome/Default
```
Now, make sure to completely ignore the README file you find there, because we want this feature and the developers are of no help. Now you have to empty and make the history files immutable so that the app won't replace them (I don't actually know if they're all safe to empty out, for this purpose, tho).
```bash
for f in "History" "History Provider Cache" "History-journal"; do mv "$f" "$f.bak"; touch "$f"; chattr +i "$f"; done
```

I hope this works for you and I hope that the developers for both Chromium and Bromite won't try to find a way to prevent this. If there are some vulns that this process might cause please write them so people can decide wether they want to do this or not.

Just so the devs know, I was going to add a feature request to add an option to change (as url) the New Tab page, in the same way that Kiwi Browser does, but disabling history also disables the most visited pages (which were the only reason why I would've changed the new tab). I could do it anyway tho, I'll see.

P.S.: Sorry if I seemed rude, it's just that I'm tired of looking for a browser that has good features and respects privacy. Bromite is the closest to what I am looking for.

**Comment by csagan5** [comment]
@uazo I think it would be best to remove the session-only cookies patch and support only using incognito mode.

What is the point of normal mode which tries to mimic incognito mode? If websites are finding ways to detect incognito mode we should help upstream fix that as you explained.

**Comment by uazo** [comment]
> I think it would be best to remove the session-only cookies patch and support only using incognito mode.

I don't really agree. it is appropriate to understand incognito for whom:

1) incognito for other phone users
I think navigation is usually normal and the use of incognito mode without history is correct

2) incognito for websites
browsing should (need!) always be in incognito and the ability to keep history is simply a temporary workaround until all data can be easily cleared at the end of session (closing app cannot be intercepted by Android applications)

personally, for example, I always use the latter, but if Bromite had the possibility to delete all the data when the tab was closed, then the patch to keep history in incognito have to be deleted (rather than session-only cookies patch).
development is possible, It's not because we don't want to. you just need a little time and patience for everyone.

What I don't understand is why delete history all the time, even for "normal" browsing, it would make sense if it were possible to decide what to keep and what not, again through content-settings

> support only using incognito mode

So far, it's just work: patch maintenance, each new feature needs a change to make it fit for incognito mode.
we should list the disabled features with incognito browsing and then decide, but remember that even incognito mode keeps data (storage in memory and cookies on disk) until application is forcibly closed.

> What is the point of normal mode which tries to mimic incognito mode?

for me the best solution is to delete all navigation data when user close the tab.

> If websites are finding ways to detect incognito mode we should help upstream fix that as you explained.

https://bugs.chromium.org/p/chromium/issues/detail?id=959839
https://bugs.chromium.org/p/chromium/issues/detail?id=990731
these are things they already know

**Comment by csagan5** [comment]
> * incognito for other phone users
>   I think navigation is usually normal and the use of incognito mode without history is correct
> * incognito for websites
>   browsing should (need!) always be in incognito and the ability to keep history is simply a temporary workaround until all data can be easily cleared at the end of session (closing app cannot be intercepted by Android applications)

Not understanding what you mean here.

> if Bromite had the possibility to delete all the data when the tab was closed, then the patch to keep history in incognito have to be deleted (rather than session-only cookies patch).
> development is possible, It's not because we don't want to. you just need a little time and patience for everyone.

No point to develop it if we have not agreed that it will be used in Bromite.

**Comment by csagan5** [comment]
> > What is the point of normal mode which tries to mimic incognito mode?
> 
> for me the best solution is to delete all navigation data when user close the tab.

But you have not not answered the question. In which ways is one better than another?

**Comment by uazo** [comment]
> But you have not not answered the question. In which ways is one better than another?

Maybe then I don't understand what you are asking me.

Technically, I don't know what is disabled with incognito mode. The only thing I have seen is that all storages are kept in memory.
In practice, it allows me to close bromite via the android recents screen, much more practical than the Exit button.

in general, for me, anonymous browsing is better because it allows you to browse the web knowing that websites cannot reconnect my sessions to each other, so it is more difficult for them to be able to profile me.
Sure it's same as cleaning all browsing data at the end of the session, but, as Bromite don't know when session ends, I have to press Exit (for me it is boring and so I don't it, particularly if I think that it might be enough close the tab).

So, if bromite had a "normal" navigation without keeping cookies and webstorage across sessions would still be fine.

**Comment by csagan5** [comment]
Let's focus on improving the user experience for (always)-incognito mode.

I am against adding options to make the regular browsing more similar to incognito mode browsing, and it is not even "clean" as you said because of the way Android apps are closed (and your patch for the cookies also has this problem).

I am sorry for the hard work you put into it (#671), I hope we can re-use parts of it in future.
