### ISSUE TITLE
Backup & Restore Sync!

### ISSUE THREAD

**Issue by arya56-beta** [bromite/bromite#737]
**### Is your feature request related to privacy?**

Password, Browsing History, Bookmarks

**### Is there a patch available for this feature somewhere?**

Don't Know!

**### Describe the solution you would like**

Auto Backup Password And Other Data With Encryption To User's Cloud Storage(Google Drive)

**### Describe alternatives you have considered**

Just Add Import Password Options From Google Chrome. Many Of Us Use Inbuilt Password Manager! It's Hard To Import 25-30 Passwords Manually..

**Comment by Poopooracoocoo** [comment]
[The developer has turned down](https://github.com/bromite/bromite/issues/244#issuecomment-461148482) requests to add support for Firefox Sync, so I don't think Google Drive backups are likely to be added as it's a cloud service and because of the work involved. As you'll have read in that issue, Firefox Sync can be self-hosted but again, it comes down to the work involved. 

Bookmarks can already be imported and exported. You can export your passwords too although you can't import them as you said. [The developer said](https://github.com/bromite/bromite/issues/416#issuecomment-555210081) that they won't implement it but they will of course accept a patch. You cannot import or export tabs or history. There's a feature request asking for bookmark all tabs. You could make separate issues requesting the ability to import and export tabs and history.

**Comment by arya56-beta** [comment]
> [The developer has turned down](https://github.com/bromite/bromite/issues/244#issuecomment-461148482) requests to add support for Firefox Sync, so I don't think Google Drive backups are likely to be added as it's a cloud service and because of the work involved. As you'll have read in that issue, Firefox Sync can be self-hosted but again, it comes down to the work involved. 
> 
> Bookmarks can already be imported and exported. You can export your passwords too although you can't import them as you said. [The developer said](https://github.com/bromite/bromite/issues/416#issuecomment-555210081) that they won't implement it but they will of course accept a patch. You cannot import or export tabs or history. There's a feature request asking for bookmark all tabs. You could make separate issues requesting the ability to import and export tabs and history and automatic backup that deletes old backups. 

NeverMind🌞

**Comment by Poopooracoocoo** [comment]
@arya56-beta what about my comment confused you?

**Comment by arya56-beta** [comment]
@Poopooracoocoo no it's cool & Perfect!👍☻ ThanKs FoR Ur HeLP!
