### ISSUE TITLE
Free talk: Can i take some of your patches for my project?

### ISSUE THREAD

**Issue by bn0785ac** [bromite/bromite#75]
Can i take your counterfingerprint patches (and adblock at some time)
and use it for my web browser

**Comment by bn0785ac** [comment]
could  i use this patch without any changes at chromium (desktop)

https://github.com/bromite/bromite/blob/master/patches/BRM047_Bromite-adblock-engine.patch

**Comment by csagan5** [comment]
Sure, feel free to pick any patch - they are released under GNU GPL v3.

Is your browser publicly released? If yes I would kindly ask that you mention somewhere that you use some Bromite patches (no need to make a list) by csagan5.

I made all patches open source so that others can benefit from it! Enjoy and let me know in case it is a project or something available to public, I am genuinely curious.

**Comment by bn0785ac** [comment]
yeah https://aur.archlinux.org/packages/inox-edgy/

**Comment by bn0785ac** [comment]
also i've found a small orphan reference
https://p.teknik.io/Jdcaf


i've needed to patch this file (make right refs)

**Comment by csagan5** [comment]
You can export the patches and keep attribution with `git format-patch xxxx`.

Good luck with the project :+1:
