### ISSUE TITLE
Close all tabs on exit, closes tabs also when App isn't "closed"

### ISSUE THREAD

**Issue by NotSomeNoob** [bromite/bromite#852]
### Bromite version

Version: 87.0.4280.106
Arch: `arm64`
Android version: 10
Device model: Mi A2

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
"Close all tabs on exit" is enabled.
When I leave bromite open, and change to something like a messenger, all tabs are closed, when coming back to bromite.
This does not happen if ram usage of the app I use after bromite is not to great (whatsapp and threema are already over the freshhold). Though it also happens after just leaving bromite for itself after some time (when only bromite is open, but I'm on the home screen for example). -- this might also be not dierectly a bug but rather a false description of the setting, as this might be actually quit good for people that don't want their tabs to be cached in swap or whatever. But then the description is misleading

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to close all tabs on exit
2. enable it
3. have a smartphone with not much ram
4. switch to different app
5. come back (you didn't exit[you didn't close it] the app the session should be still ongoing)
6. now all tabs might be gone

### Expected behavior

The tabs should be still there after I'm coming back from whatever I've done, and only close when I close the app.

### Screenshots
Open Tab
![DuckDuckGoIsOpen](https://user-images.githubusercontent.com/74873866/101993317-d976f400-3cb9-11eb-830c-325b16dcac89.png)
Was then just looking at it
![ILookAtTheAppFromTask](https://user-images.githubusercontent.com/74873866/101993327-f27fa500-3cb9-11eb-9bad-9c954d2575b4.png)
Switched instantly back
![SwitchingBackAllIsGone](https://user-images.githubusercontent.com/74873866/101993332-00cdc100-3cba-11eb-807f-dd092202d54b.png)
Open tabs are gone
does just starring at the open App already count as session?

**Comment by csagan5** [comment]
@uazo I think this is due to the same code being run when it is the user or the OS closing the app: what do you think? The OS will close the app when there is not enough memory for example.

**Comment by uazo** [comment]
>  I think this is due to the same code being run when it is the user or the OS closing the app

yes, i think so too, you can see it from the log, but it's sure, considering that the patch acts at the init.
we could think of using the date/time of the serialized file of the tabs list, using that to understand whether to reload the tabs before an offset that need to be customizable.

among other things, if you agree, while we are at it, you could also think about re-enabling the loading of incognito ones (useful with the always-on), because currently, perhaps for some bugs, it doesn't work.

**Comment by NotSomeNoob** [comment]
Thanks for the suggestion.

Might I add:
1. My Smartphone uses only 2GB of ram for OS and background processes. Thus Bromite has 2 GB usable ram.
2. Bromite always closes all tabs with "Close all tabs on exit" enabled when switching to another app. 
maybe this clarification is helpfull, dunno

**Comment by csagan5** [comment]
> we could think of using the date/time of the serialized file of the tabs list, using that to understand whether to reload the tabs before an offset that need to be customizable.

No, this is a hack. It will lead to a poor user experience anyways; it is better to document it as a known issue. If the Android OS decides to close the app there is nothing we can do to track it. Unless you can think of a way to know whether app is closing because of an user request or an OS request (there is none, as far as I know).



> you could also think about re-enabling the loading of incognito ones (useful with the always-on), because currently, perhaps for some bugs, it doesn't work.

Those are not bugs, but rather us trying to force the incognito feature outside of its design. By attempting to restore the incognito tabs there will likely be more popping up; feel free but I do not give it a high confidence of success.

**Comment by uazo** [comment]
> My Smartphone uses only 2GB of ram for OS and background processes. Thus Bromite has 2 GB usable ram.

but 2gb is not enough? it seems strange to me that android is under memory pressure.
@NotSomeNoob could you provide the complete log (if you think there are no privacy issues)? "under memory pressure" will be recorded in the log I think.

>  or an OS request (there is none, as far as I know).

I confirm, no way

> Those are not bugs, but rather us trying to force the incognito feature outside of its design.

yes, always anonymous browsing is the reason to use bromite

**Comment by NotSomeNoob** [comment]
Sry, for the late answer, but the emails all landed in the spamfolder. 
I noticed now after not using the feature for multiple weeks that the bug is somhow fixed. I do not know what made that bug happen but I'm for that it's gone. Now the Browser seems to work as expected. Maybe the bug was caused by my particular android version, I don't know. 
Thanks for the help and the replies!
