### ISSUE TITLE
Disabled Features: multiple_raster_threads in chrome://gpu - what to do?

### ISSUE THREAD

**Issue by DAC324** [bromite/bromite#875]
Hello all,

playing around with Bromite, I also saw that on chrome://gpu,
Multiple Raster Threads is set to disabled, and consequently, "Disabled Features: multiple_raster_threads" appears in "Problems Detected".

In former times, there was chrome://flags#num_raster_threads but this flag seems to have disappeared in recent versions.

How can I enable multiple raster threads in Bromite?

**Comment by csagan5** [comment]
This issue is missing the template.

If multiple raster threads are disabled it means that with your specific hardware there are problems and thus it gets disabled automatically (without filling-in the issue template this cannot be further checked).

The flag was removed in https://github.com/chromium/chromium/commit/2a51528a1737e9038f7f96f29403032a6a845a25

**Comment by DAC324** [comment]
As there seem to be several templates:
1. Which one is to be used for this kind of question?
2. I was not aware that such a template is MANDATORY. I'd recommend to populate it in all new issues posted.

**Comment by csagan5** [comment]
Feature request, since it is not a bug.

**Comment by csagan5** [comment]
Fixed in `88.0.4324.95`.
