### ISSUE TITLE
Create a F-droid repo for updates

### ISSUE THREAD

**Issue by yasht2820** [bromite/bromite#88]
Currently users can only get updates by using XDA Labs which is owned by a commercial entity and requires signing up to download. It also has the limitation of not allowing different versions for different architectures and android sdk levels.

I'd like to propose creating a F-droid repo for binary distribution like the microG project and Retroarch.
[This guide](https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/) describes setting up a F-droid repository.

Alternatively, Bromite can be uploaded on Play Store which the users can access using Yalp or Aurora store which don't require signing up.

**Comment by antonin-lebrard** [comment]
While I would also like this magnicent repo on F-Droid, it has been discussed in this issue: https://github.com/bromite/bromite/issues/4
And I suspect the problems encountered has not changed since

**Comment by yasht2820** [comment]
In #4 , @csagan5 attempted to build the binaries himself in F-droid VMs, while what I'm proposing is to just distribute the already built binaries found on the website through a F-droid repo.

**Comment by csagan5** [comment]
@yasht2820 ah! That's a good idea, never thought of that. I had read instructions about how to host your own repo but I was focusing on the submission back then; I will surely give a look into this, it seems viable.

> Alternatively, Bromite can be uploaded on Play Store which the users can access using Yalp or Aurora store which don't require signing up.

This is however not possible, I already attempted a submission to Play Store. It was never published because the Play Store employee wanted the logo to be changed (he did not want to accept my description of derivative work from the [CreativeCommons/BSD original](https://commons.wikimedia.org/wiki/File:Chromium_11_Logo.svg)) and limitations to the ads blocked; I did not go forward and just stopped what I believed was a waste of time, as probably later on other issues would have been found if I had changed the logo and limited the adblocking (which I did not want to do anyways).

> Bromite was rejected from inclusion in this repo for its large size.

This is not really true, it was not rejected nor accepted :) I was tasked to make the build work and from there probably we would have had to remove all binary blobs used to build and the play services integrations (other binary blobs that would get embedded); nowadays Bromite is almost free of all of these. I encountered a kernel bug with the VM due to the large amount of data transferred, I lost interest in to this because it was excruciatingly slow and painful to improve as a build process.

If someone makes a Chromium-based browser build there (with snapshots, most likely) I will be happy to do the same for Bromite.

**Comment by yasht2820** [comment]
@csagan5 I meant that Bromite was rejected in the [izzysoft.de](https://apt.izzysoft.de/fdroid/) repo that distributes binaries from Github. [Here's](https://gitlab.com/IzzyOnDroid/repo/issues/21)  the issue where it was rejected.

**Comment by csagan5** [comment]
@yasht2820 thanks for the information. I will probably setup a similar repository one of these days.

For the records, the 100MB APK (SDK21+) and the smaller one (~46MB, SDK16+) will occupy the same size when installed; the former is optimized for SDK21+ and comes with an unpacked `libchrome.so` inside (an optimization).

(do not ask me why it is like that, because I do not know :) but it is explained here: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets)

**Comment by csagan5** [comment]
It took some work but I finally managed to create the F-Droid repository and arrange for stable and pre-releases to be released through it regularly.

https://www.bromite.org/fdroid

It seems to be working fine; you can install Beta builds (pre-releases here on Github) by picking the versions manually, as any other F-Droid released-app does. When you are on the stable version F-Droid will display "recommended" near the name of the app in the installed apps list.

**Comment by csagan5** [comment]
There is [discussion upstream](https://gitlab.com/fdroid/fdroidclient/issues/1164) about disabling redirects in the F-Droid client (which I just reported being a feature), if that is the case I will pull the plug on this repository, I have no intention to host the full downloads to adhere to this _weak_ privacy regulation.

**Comment by csagan5** [comment]
I have found a workaround to workaround the missing feature, the repository will be supported for the time being (at least until there is no other breakage).

**Comment by speednroll** [comment]
@csagan5 would it be possible to add webview to this repository? I use your webview but still have to update it manually from the page 😔

**Comment by dimqua** [comment]
@csagan5 could you please add webview package to the repository?

**Comment by csagan5** [comment]
@speednroll @dimqua I will add it with a "requires root" flag, this should avoid users trying to install it without root.

**Comment by csagan5** [comment]
It turns out F-Droid does not show that application requires root. The relative "requires root" is ignored, and the SUPERUSER permission also does not show up in the client app UI.

I have modified the SystemWebView APKs to require the SUPERUSER permission from latest release onwards, this will hopefully stop people from trying to install it without root (and reporting that it does not work), but the problem IMO is that F-Droid client should display very clearly that it requires root (it does not) so that users would not even download it if they do not have it.

I originally did not want to include SystemWebView in the F-Droid repo for this reason (user confusion), now I expect anyways some bogus reports about this.

@speednroll @dimqua let me know if the newly added SystemWebView works for you, but I still believe that this might affect negatively more users (e.g. those who do not know what root is) than those affected positively (those who root a phone).
