### ISSUE TITLE
No SystemWebView < Lollipop and above (SDK21)

### ISSUE THREAD

**Issue by nussbaumer** [bromite/bromite#89]
The SystemWebView download-page shows a "Jelly Bean and above (SDK16)" version,
but the apk is the same as "Lollipop and above (SDK21)" and can not be installed in Kitkat due to SDK mismatch.
I know < SDK21 is not supported by Google, but could you please try to build a SDK19 (Kitkat) version? May be it can be integrated in my custom CM11 rom somehow. 
Until then you could please remove the irritating option from the page.

Thank you very much for providing us with an excellent browser.

**Comment by csagan5** [comment]
> The SystemWebView download-page shows a "Jelly Bean and above (SDK16)" version,
but the apk is the same as "Lollipop and above (SDK21)" and can not be installed in Kitkat due to SDK mismatch.

Thanks for reporting, I fixed this.

> I know < SDK21 is not supported by Google, but could you please try to build a SDK19 (Kitkat) version? 

I looked into this. They moved minimum SDK from 19 to 21 five months ago: https://github.com/chromium/chromium/commit/1cf758f803a320fd2554b1e7aab8e2be550fb2cf

The stated reason is that SDK19 is no more tested. This is the same reason for the bump from SDK16 to SDK19 years before, but one has to expect failures to start to happen shortly after minimum version is bumped.

If you can reproducibly explain how to build the webview for SDK19 with a v68 Chromium (and it is not an insane process) then I will be happy to do something about it; otherwise the answer is no, unfortunately, as I checked how to do this and there is no documented example of how to arrange such build.
