### ISSUE TITLE
Scrolling lags on some (older) devices

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#90]
It has been reported that some devices, notably with not a lot of RAM/CPU power, are lagging for example when scrolling.

The issue has been verified to not be related to #61 so it seems to be about the adblock engine itself.

To reproduce this issue toggling the adblock engine should make a sensible difference.

**Comment by AndhikaWB** [comment]
Scrolling lags also happens on my Android 4.3 devices with 2 GB of RAM, but Chromium and Brave browser also do the same. Turning off 'Javascript' on Bromite (may) solve the issue for me.

Unless my issue is different, I think it's an issue from the Blink engine itself (for older devices only), turning off 'smooth scrolling' from 'chrome://flags' doesn't fix the issue.

**Comment by csagan5** [comment]
@AndhikaWB which version of Bromite are you using? And does it lag when turning off AdBlock (not Javascript)?

**Comment by AndhikaWB** [comment]
I installed Bromite on my old device since v67.0.3396.88 (ARM), right now I'm using v67.0.3396.107 and still experience the scrolling lags (but still acceptable for reading on news site etc, for me). Disabling Adblock doesn't seems to fix the lag issue.

Sometimes I also experienced another scrolling issue like: scrolling down a page will scroll the page down then up a little, especially when the page isn't fully loaded (or visiting a site with complex scripts like Google Images, etc). The scrolling lags doesn't happen when visiting simple sites like this Wikipedia (example: [this page](https://en.wikipedia.org/wiki/A)).

**Comment by csagan5** [comment]
@AndhikaWB since you tested with Chromium then your issue must be upstream. To confirm this: when you tested via Chromium, did you use the one matching the Bromite release and downloaded from [here](https://www.bromite.org/chromium)?

**Comment by AndhikaWB** [comment]
@csagan5 Yes, just tested it a minute ago using Chromium v67.0.3396.107 (the same version as Bromite) from the given link.

In case you still need it
-------------------------------------
**Version**
v67.0.3396.107 (ARM)

**Is the bug reproducible with latest version?**
Yes, on latest stable release

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Yes

**Is the bug a crash?**
No

**Describe the bug**
Scrolling lags when opening sites with complex scripts (ex: Facebook, Google, etc), also happens when the page is still not completely loaded (still loading some elements/scripts/images etc). Also, sometimes scrolling down a page will scroll the page down and then up (or otherwise). Disabling smooth scrolling from chrome://flags does not fix the issue.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to [link](https://www.google.com/search?q=a) (example)
2. Scroll down the page
3. Bug happened

**Expected behavior**
Scrolling shall to work normally.

**Comment by csagan5** [comment]
@AndhikaWB thanks, this means however that it is not a Bromite issue so we will not track it here. You could try checking on Chromium issue tracker/forums to see if other people have the problem.

This specific issue here (#90) is for those users that see the lagging go away when disabling AdBlock.

**Comment by csagan5** [comment]
An improvement to the adblock engine to tackle this issue will be released in 68.0.3440.72

**Comment by csagan5** [comment]
Another improvement for the adblocking has been released in 68.0.3440.121
