### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by stalkerandrew** [bromite/bromite#93]
sites like pugetsystems.com not able to show captcha, other sites also confirmed.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

Feel free to re-submit your issue after enabling desktop mode so that you will see and use the template.

(Issues not following the template are considered invalid)
