### ISSUE TITLE
V8 Zero Day (CVE-2021-21148)

### ISSUE THREAD

**Issue by Zoraver** [bromite/bromite#931]
### Bromite version

Version: `88.0.4324.149` and earlier
Arch: `arm`, `arm64`, and `x86`
Android version: N/A
Device model: N/A

### Is this bug about the SystemWebView?
I believe that it applies to the SystemWebView as well, but not exclusively so.

### Is the bug reproducible with latest version?

See bug description.

### Can the bug be reproduced with corresponding Chromium version?

Yes

### Describe the bug

A bit over a week ago, Google [fixed a heap buffer overflow vulnerability in V8](https://chromereleases.googleblog.com/2021/02/stable-channel-update-for-desktop_4.html) that was (and likely still is) being exploited in the wild. Based on my reading of the Chromium git log, this vulnerability is patched in Chromium 88.0.4324.150 and higher. Bromite is currently based on Chromium 88.0.4324.149, which is the newest stable tag of Chromium still vulnerable. In case you were not aware of this, I just wanted to give you a nudge to get a patched version of Bromite shipped.

**Comment by csagan5** [comment]
I was not aware, thanks for the information; after some investigation it looks like the corresponding V8 change is between `8.8.278.14` and `8.8.278.17`: https://chromium.googlesource.com/v8/v8.git/+/36abafa0a3168ef664a363fce8f9840b43daa2af%5E%21/

**Comment by Zoraver** [comment]
I suspect that this vulnerability does affect Android for the following reasons:

1. Chrome for Android has a pretty consistent release schedule; a new version is released every two weeks and a new major version is released every six weeks, typically on Monday or Tuesday. This schedule is typically only broken to patch zero-day exploits or fix major regressions. Chrome for Android v88.0.4324.141 was released on Monday, February 1, and Chrome for Android v88.0.4324.152 was released on Thursday, February 4. The Chrome for Android team had a reason to break their normal schedule to release v88.0.4324.152; I believe it was to patch the exploit in question.
2. I can only recall fixed vulnerabilities in Chrome for Android being documented on the Chrome Releases blog when the vulnerabilities are specific to Android and do not affect desktop versions of Chromium. The fact that the vulnerability is not mentioned in the blog post for Chrome for Android v88.0.4324.152 does not convince me that it does not affect Android. 
3. I do not believe V8 is significantly different between desktop platforms and Android, so I would expect V8 vulnerabilities that affect desktop platforms to also affect Android in most cases.

I do not know the details of the vulnerability, so I cannot be 100% sure that it does in fact affect Android. That being said, I think that it would be prudent to ship a patched version of Bromite sooner rather than later.

**Comment by csagan5** [comment]
Sorry @Zoraver, these are all speculations. In the communities we are involved, which is open source Chromium forks and in the security community in general, we all benefit from clarity on security issues like this one.

I suspect upstream has not been open about the Android situation for valid reasons, some examples:
* the sandbox protects from this vulnerability, although possibly not in the same way for all Android versions
* the impact on Android is not yet fully clear
* waiting on some vendor to release patches
* there is a related CVE yet to be announced on Android only, with different impact

@thestinger what do you think? We will know if CVE-2021-21148 affects Android only after [issue ](https://bugs.chromium.org/p/chromium/issues/detail?id=1170176) becomes public?

**Comment by thestinger** [comment]
Chrome for Android release notes don't explicitly announce vulnerabilities that were disclosed in the desktop release notes. Take a look at the past releases. They only talk about Android-specific changes.

**Comment by thestinger** [comment]
By the way, for everyone that's not aware, you can follow the stable releases for Android at https://chromiumdash.appspot.com/releases?platform=Android. You don't need to use their blog posts to figure it out. That site tells you the latest version for the stable channel so you can know which is the appropriate tag to use.

**Comment by uazo** [comment]
i know i am saying obvious things, but reading the patch, the vulnerability seems to be related to webasm and the way memory is convisible with javascript. in particular it seems that the "shared" option is always set, allowing the sending (and maybe even the modification) of the buffer between service workers, for example, those instantiated by extensions.

i think this is particularly serious, for example, for client-side Blazor (a microsoft project that uses mono-webasm in the browser) because it makes the whole environment insecure, since the wasm memory is fundamental, because it contains the code and obviously all the variables .

probably for sites that do not use webasm (ie for now, most, but that technology will become the future of client programming) nothing changes, but for the others it is a serious fact.

> https://chromiumdash.appspot.com/releases?platform=Android

@csagan5 can't we do something automatic, I don't know, an issue every time there is a new release?

**Comment by csagan5** [comment]
> Chrome for Android release notes don't explicitly announce vulnerabilities that were disclosed in the desktop release notes. Take a look at the past releases.

That is very disappointing. Is there a source for their policy on the disclosure for Desktop/Android versions? If I look at past blog posts, like [this one](https://chromereleases.googleblog.com/2020/11/chrome-for-android-update.html), I would instead say that they would mention when a CVE affects Chrome for Android.

> You don't need to use their blog posts to figure it out. That site tells you the latest version for the stable channel so you can know which is the appropriate tag to use.

I do not use the blog; I am aware of https://chromiumdash.appspot.com/releases?platform=Android; there is also:
* https://chromestatus.com/features/schedule
* https://omahaproxy.appspot.com/

In none of these 3 the security issues are properly highlighted for Android.

> can't we do something automatic, I don't know, an issue every time there is a new release?

It would be beneficial for transparency, in the past I have complained about the security of Chromium forks that are several versions behind upstream; however not all releases require an urgent follow-up release, and to identify those that need an urgent release it is first necessary to get clear communication about the security problems and their severity.

I prefer to invest time in Bromite rather than messing with GitHub actions and permissions; see also: https://thenewstack.io/github-actions-design-flaw-leaves-security-hole-for-remote-code-execution/

Bromite is already being released very frequently, on average every ~2 weeks. The next release was already being prepared before this issue was opened; the response has been adequate also for past upstream security issues.

Please stay vigilant, but I do not see the problem here - except that it is still impossible for me to find an authoritative source that CVE-2021-21148 affects Android. I guess I can try a PoC myself or wait for the issue embargo to be removed.

**Comment by csagan5** [comment]
Fixed by the release of `88.0.4324.185`.

**Comment by thestinger** [comment]
> That is very disappointing. Is there a source for their policy on the disclosure for Desktop/Android versions? If I look at past blog posts, like this one, I would instead say that they would mention when a CVE affects Chrome for Android.

I don't know what's disappointing about it. They disclose the list of vulnerabilities in the initial blog post for the desktop release. The Android blog post discloses additional Android-specific issues. The post you linked is an example of that. It says this, referring to it listing an additional fix beyond the generic fixes announced for the desktop release: "Security fixes in this release are listed in the corresponding Desktop Release. In addition, this Android release contains:".

They don't split up the generic fixes by operating system. There isn't a list of fixes for Chrome Windows, macOS and Linux as part of the blog post. Similarly, they don't differentiate which ones apply only to Android. Android-specific issues will sometimes be announced as part of the Android post instead of the desktop / generic post. What you need to understand is that the desktop one is treated as the generic post applying to everything. The other posts can add to it, but don't bother repeating the content there.

**Comment by thestinger** [comment]
Every vulnerability listed in the generic (desktop) announcements should be considered to impact Android. Some of them may only impact Windows, some may only impact macOS, some may only impact desktop Linux, etc. but most will be generic issues across all platforms.

**Comment by thestinger** [comment]
It is possible that a vulnerability impacts all desktop releases but not Android but they reuse the bulk of the code everywhere other than iOS.

**Comment by csagan5** [comment]
> I don't know what's disappointing about it.

I am getting different information quality/density/presentation if compared to the individual issues: https://bugs.chromium.org/p/chromium/issues/list?q=Type%3DBug-Security%20-Status%3DWontFix&can=2

There you can see that each of them specifies which OSes are affected; I expect [issue 1170176](https://crbug.com/1170176) to mention all OSes once it is disembargoed.

> It is possible that a vulnerability impacts all desktop releases but not Android

It would be nice to know this in the blog posts, explicitly, and viceversa; my bias.

Only alternative is to apply for having early access to the embargoed issues as explained here (bottom paragraph): https://www.chromium.org/Home/chromium-security

> Every vulnerability listed in the generic (desktop) announcements should be considered to impact Android.

That is fine, I understand it. I would expect to find this fact mentioned here somewhere (or in the FAQs): https://www.chromium.org/Home/chromium-security

**Comment by thestinger** [comment]
The vulnerabilities generally impact multiple OSes. Ideally, the Android tags would be the same as the desktop tags and the releases would be announced in the same posts. It's unfortunate that they have diverging stable branches / tags for it at all. It does make sense considering how much of the higher level code is different, etc. but it's still unfortunate. Having all the separate SKUs rather than a unified codebase at all times isn't very good.

**Comment by thestinger** [comment]
Pretend for a moment that they announced the Android releases together with the others. After all, they're putting Windows, macOS and Linux desktop releases in the same post already. It's a completely separate build. It would be entirely possible for them to support Android via the same source tree rather than it being at all separate.

The issue for Android Chromium is that it inherited constraints on publishing code based on the next major stable release of Android publicly due to a lot of that development not happening in AOSP. It ended up inheriting a culture of doing things internally. It isn't as public as the rest of Chromium development and as you've seen they end up with issues where internal code that was intended to be published is mistakenly overlooked and not pushed upstream. Since it has these different constraints and a more internal development model, it usually diverges to some extent from the generic tags. On some occasions, the Android tags are the same as the desktop ones. Ideally, that would *always* be guaranteed to be the case because they would develop it more openly and in sync with the rest of Chromium. The situation of it being separate in that way is problematic. The separate release announcements is a symptom of a problem rather than something good. It would ideally be a single post for desktop + Android + ChromeOS because they'd ideally use the same tag. Ideally, ChromeOS and to a lesser extent Android wouldn't have downstream forks.

**Comment by csagan5** [comment]
> It's unfortunate that they have diverging stable branches / tags for it at all. It does make sense considering how much of the higher level code is different, etc. but it's still unfortunate. Having all the separate SKUs rather than a unified codebase at all times isn't very good.

These are the differences between the current stable versions of Desktop vs Android: https://chromium.googlesource.com/chromium/src/+log/88.0.4324.181..88.0.4324.182?pretty=fuller&n=10000

The only relevant issue seems to be about [issue 1172192](https://bugs.chromium.org/p/chromium/issues/detail?id=1172192), also embargoed so probably a security one.

I have never dug deeply into these differences and always assumed that they would be tailored with the results of testing. So their release process is:
1. wrap up Android release, mark the tag as stable
2. fix Linux/Windows/Mac problems, mark the tag as stable

ChromeOS is currently at `88.0.4324.153` so it seems to have its own separate cycle.

> The separate release announcements is a symptom of a problem rather than something good. It would ideally be a single post for desktop + Android + ChromeOS because they'd ideally use the same tag. Ideally, ChromeOS and to a lesser extent Android wouldn't have downstream forks.

Yes, I can see that. I have been loosely following the development of Fuchsia, I wonder whether they will "pull the plug" on AOSP once they replace the Linux kernel with it.
